"""LLM-as-a-judge baseline (zero-shot). Reads data/judge_input.jsonl (blind: ids and text only).
  set OPENROUTER_API_KEY=...
  python judge.py --model openai/gpt-4o --out data/judge/gpt4o.jsonl --limit 5
Resumable; records p_ai (0-100), seconds and cost per excerpt. The prompt is fixed and identical for every judge."""
import argparse, json, os, re, time, threading, requests
from concurrent.futures import ThreadPoolExecutor

PROMPT = ("Below is an excerpt from a scientific paper. Decide whether it was written by a human researcher or generated by an AI "
          "language model. Reply with JSON only, in exactly this form: {\"p_ai\": <number from 0 to 100, your probability that the "
          "excerpt is AI-generated>, \"reason\": \"<one sentence>\"}\n\nExcerpt:\n\n")

def parse(raw):
    """Extract p_ai in [0,100] from a model reply; None if not parseable."""
    if not raw: return None
    m = re.search(r"\{.*?\}", raw, re.S)
    if m:
        try:
            v = json.loads(m.group(0)).get("p_ai")
            if isinstance(v, (int, float)) and 0 <= v <= 100: return float(v)
            if isinstance(v, str): return float(v.strip().rstrip("%"))
        except Exception: pass
    m = re.search(r'"?p_ai"?\s*[:=]\s*"?(\d+(?:\.\d+)?)', raw)
    if m and 0 <= float(m.group(1)) <= 100: return float(m.group(1))
    return None

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", required=True); ap.add_argument("--out", required=True)
    ap.add_argument("--input", default="data/judge_input.jsonl"); ap.add_argument("--limit", type=int, default=0)
    ap.add_argument("--workers", type=int, default=3); ap.add_argument("--max-tokens", type=int, default=400)
    a = ap.parse_args()
    key = (os.environ.get("OPENROUTER_API_KEY") or "").strip().strip('"').strip("'").strip()
    print(f"key loaded: {len(key)} chars, starts with {key[:6]!r}", flush=True)
    if not key.isascii() or len(key) < 40: raise SystemExit("The key looks wrong. Set OPENROUTER_API_KEY to your REAL key (no placeholder text, no spaces).")
    os.makedirs(os.path.dirname(a.out) or ".", exist_ok=True)
    done = {json.loads(l)["id"] for l in open(a.out, encoding="utf-8")} if os.path.exists(a.out) else set()
    rows = [json.loads(l) for l in open(a.input, encoding="utf-8")]
    rows = [r for r in rows if r["id"] not in done][: a.limit or None]
    print(f"already done: {len(done)}; to judge: {len(rows)} with {a.model}", flush=True)
    lock = threading.Lock(); n = [0]

    def call(text):
        r = requests.post("https://openrouter.ai/api/v1/chat/completions", timeout=300,
            headers={"Authorization": f"Bearer {key}"},
            json={"model": a.model, "temperature": 0, "max_tokens": a.max_tokens, "messages": [{"role": "user", "content": PROMPT + text}]})
        if r.status_code != 200: raise RuntimeError(f"HTTP {r.status_code}: {r.text[:300]}")
        j = r.json(); return j["choices"][0]["message"].get("content") or "", j.get("usage", {})

    def work(r):
        for attempt in range(10):
            try:
                t0 = time.time(); raw, usage = call(r["text"]); dt = time.time() - t0; break
            except Exception as e:
                if any(c in str(e)[:12] for c in ("401", "402", "403")):
                    print("FATAL (key/credit problem), stopping:", str(e)[:300], flush=True); os._exit(1)
                wait = 20 if "429" in str(e) else min(2 ** attempt * 3, 60)
                print(f"  wait {wait}s ({str(e)[:70]})", flush=True); time.sleep(wait)
        else:
            return
        with lock:
            with open(a.out, "a", encoding="utf-8") as f:
                f.write(json.dumps(dict(id=r["id"], p_ai=parse(raw), seconds=dt, usage=usage, raw=raw[:400]), ensure_ascii=False) + "\n")
            n[0] += 1; print(f"{n[0]}/{len(rows)} {r['id']} p_ai={parse(raw)} {dt:.1f}s", flush=True)

    with ThreadPoolExecutor(max_workers=a.workers) as ex: list(ex.map(work, rows))
