const fs = require('fs');
const { D, body, center, pageBreak, runs, FONT, SIZE, DOUBLE, makeDoc } = require('./lib');
const { Paragraph, TextRun, Table, TableRow, TableCell, WidthType, ShadingType, AlignmentType, BorderStyle } = D;

// ---------- APA 7 / MISQ-style helpers (Times New Roman 12, double-spaced, embedded tables)
const H1 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, font: FONT, size: SIZE })] });
const H2 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_2, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, font: FONT, size: SIZE })] });
const H3 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_3, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, italics: true, font: FONT, size: SIZE })] });
const tcap = (n, title) => [
  new Paragraph({ keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 }, children: [new TextRun({ text: `Table ${n}`, bold: true, font: FONT, size: SIZE })] }),
  new Paragraph({ keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 }, children: [new TextRun({ text: title, italics: true, font: FONT, size: SIZE })] })];
const tnote = (t) => new Paragraph({ spacing: { line: 240, before: 60, after: 240 }, children: runs('*Note.* ' + t, { size: 20 }) });
function atable(header, rows, widths) {
  const line = { style: BorderStyle.SINGLE, size: 6, color: '000000' }, none = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  const all = [header, ...rows], last = all.length - 1;
  const cell = (txt, w, ri) => new TableCell({ width: { size: w, type: WidthType.DXA },
    borders: { top: ri === 0 ? line : none, bottom: (ri === 0 || ri === last) ? line : none, left: none, right: none },
    margins: { top: 40, bottom: 40, left: 80, right: 80 }, shading: { type: ShadingType.CLEAR, fill: 'FFFFFF', color: 'auto' },
    children: [new Paragraph({ spacing: { line: 240, before: 0, after: 0 }, children: runs(String(txt), { size: 20 }) })] });
  return new Table({ width: { size: widths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: widths,
    rows: all.map((r, ri) => new TableRow({ tableHeader: ri === 0, cantSplit: true, children: r.map((c, ci) => cell(c, widths[ci], ri)) })) });
}

const TITLE = 'When the Reviewer Defers: The Value of AI Review, Ability, and the Pressure Gap in Fourteen Language Models';
const ABSTRACT = 'A principal who delegates review to an AI buys information. We model the value of that purchase when the delegate may defer to the principal’s stated preference regardless of the evidence, a language-model analogue of the yes-man in Prendergast (1993). A requester whose preference is right with probability π, and who adopts the delegate’s report, gains V = (1 − s)(a − π) when the delegate’s ability is a and it defers with probability s: ability and integrity are complements, deference costs value only if the delegate is better than the requester’s prior, a requester who updates rationally never gains from deference (Blackwell ordering), and a buyer who ranks delegates by ability overstates the level of value by the factor 1/(1 − s). We measure a and s with 120 audited item stems posed with and without a stance in two registered studies of fourteen models in five families. Larger tiers were more able (+27 points) and less deferential (−24 points conditional on a correct stance-free answer), uniformly across families (exact sign test p = .062), yet the largest open models still lost 6 to 43 points of accuracy under pressure. Ranking by ability was value-optimal for every prior in 34 of 45 model pairs, but the level of value was overstated by up to 62%. We derive the implied willingness to pay for integrity and the conditions under which hiding the stance from the delegate pays.';
const KEYWORDS = 'AI delegation, value of information, yes-men, sycophancy, agency, large language models';

const c = [];
const P = (t, o) => c.push(body(t, o));
const NI = { noIndent: true };

c.push(center(TITLE, { bold: true }));
c.push(center('**Abstract**', { keepNext: true }));
c.push(body(ABSTRACT, NI));
c.push(body('**Keywords:** ' + KEYWORDS, NI));
c.push(pageBreak());

// =============== Introduction
c.push(H1('Introduction'));
P('Firms now ask AI systems to review decisions that someone has already leaned toward: whether a request meets policy, whether a model may be released, whether a report is consistent with the ledger. The economic logic of such delegation is that the principal buys information she does not have. The purchase is worth making only if the delegate’s report depends on the evidence and not on the principal’s own preference. A delegate that returns the requester’s view, with a fluent rationale, sells the principal her own prior at the price of a second opinion.');
P('The classic account of this failure is Prendergast’s (1993) theory of yes-men: a subordinate whose output is evaluated against the boss’s prior learns to conform to it, and the organization loses the subordinate’s information. For language models the mechanism is not strategic but it is real. Models trained with human approval as part of the signal agree with a stated view more often than evidence warrants, and larger, more heavily tuned models do so more often in some tests (Perez et al., 2022; Sharma et al., 2023). The loss is hard to see for two reasons. The deferential answer looks like confirmation, and the benchmarks that buyers use contain no stated preference, so they measure ability and not integrity. The buyer’s problem is then one of inference: which of the delegates on offer is worth how much, given what can be observed?');
P('This paper makes that problem precise and measures its parameters. We model a requester whose preference is right with probability π and who adopts the report of a delegate with ability a that defers to the stance with probability s. The value of review for the requester is V = (1 − s)(a − π) when the delegate defers at the same rate whether the requester is right or wrong, and a general expression otherwise. The expression has five implications. Ability and integrity are complements. Deference lowers value exactly when the delegate is more accurate than the requester’s prior, so integrity matters where delegation matters. A requester who updates rationally never gains from deference, because a deferential delegate’s report is a garbling of an informative one. A buyer who values the delegate by a − π overstates the value by the factor 1/(1 − s) at every prior. And ranking delegates by ability alone is value-optimal for all priors only under a condition that we state and test.');
P('We measure the parameters in two registered studies. Each uses 120 audited item stems posed twice to the same model, once with the evidence and once with the evidence plus one sentence in which the requester states or supports a contrary action. Normative consistency on the stance-free version measures a. The rate at which a correct model nonetheless follows the contrary stance measures s when the requester is wrong. The first study, a four-tier commercial ladder on easy items, met a ceiling on ability and a floor on deference and could not test the hypotheses. The second repaired the design under a pilot gate registered before collection, using harder items, stance sentences that assert unverifiable support, ten open-weight models in four families, and the commercial ladder again. Larger tiers were more able and less deferential in every family, so our registered prediction that scale would not lower deference is rejected. Yet deference remained large in absolute terms: at the largest open tiers, accuracy under pressure was lower than stance-free accuracy by 6 to 43 percentage points.');
P('We contribute in three ways. First, we give a value function for delegated review with a deferential delegate and derive its comparative statics, including the result for a sophisticated requester and a condition for the validity of ability as a ranking cue. Second, we calibrate it with measured parameters for fourteen models, which show that ability ranks delegates well in most pairs but overstates the level of value by up to 62 percent. Third, we derive two implied prices that a buyer or a regulator can use: the willingness to pay for integrity, and the maximum ability that a firm should be willing to sacrifice to hide the stance from the delegate. The model is stylized and the structure is not new; what is new is the identification of the two parameters as separate, measurable properties of an AI delegate, and the quantities that follow. We study models and not people, and we state what that does and does not allow.');

// =============== Related literature
c.push(H1('Related Literature'));
P('The agency literature treats delegation as a problem of securing the agent’s effort and judgment when interests differ (Jensen & Meckling, 1976; Eisenhardt, 1989). Work on authority and communication in organizations shows how the allocation of decision rights shapes what information flows to the decision maker (Aghion & Tirole, 1997; Dessein, 2002), and work on strategic communication shows that advice is informative only to the degree that the adviser’s incentives are aligned (Crawford & Sobel, 1982). Prendergast (1993) shows that when a worker’s pay depends on matching the boss’s information, workers report what the boss already believes, which destroys information. Our delegate has no wage and no interest, but its reports depend on the principal’s visible preference through training, and the structure is the same.');
P('The comparison of information sources has a standard form in Blackwell’s (1953) ordering of experiments, which we use to show that a sophisticated principal never gains from deference. In the economics of AI, Agrawal et al. (2019) separate prediction from judgment and argue that the value of prediction depends on the complementary judgment of the human decision maker; we study a case in which the delegate’s own judgment is undermined by the requester’s stated view. In information systems, research on delegation to and from agentic artifacts (Baird & Maruping, 2021; Fügener et al., 2022) and on the sociotechnical aspects of AI (Sarker et al., 2019) motivates the setting. Supervisory guidance on model risk management requires validation to provide effective challenge (Board of Governors of the Federal Reserve System, 2011), which is the property that a deferential reviewer lacks. Finally, the computer science literature documents sycophancy and its dependence on scale and training (Ouyang et al., 2022; Perez et al., 2022; Sharma et al., 2023) without a decision-theoretic value of review.');

// =============== Model
c.push(H1('A Model of Delegated Review with a Deferential Delegate'));
c.push(H2('Setup'));
P('A requester has a stated preference for action S in a binary decision and earns 1 if the final action is correct and 0 otherwise. S is correct with probability π, the accuracy of the requester’s preference (A1). Without review she acts on S and earns π. When the delegate judges on evidence it answers correctly with probability a, independently of whether S is correct (A2, ability). The delegate sees the stance. If S is wrong it reports S with probability s_w regardless of the evidence; if S is right, with probability s_r; otherwise it reports its evidence-based answer (A3, deference). Its integrity is 1 − s. The case s_w = s_r = s is the pure yes-man. The naive requester adopts the delegate’s report (A4); a sophisticated requester who knows (a, s_w, s_r, π) updates (Proposition 5). Costs and prices are set aside until Proposition 8, and third options are treated as errors.');
c.push(H2('Value of Review'));
P('*Proposition 1 (value of review).* For the naive requester, V(π) = (1 − π)(1 − s_w)a − π(1 − s_r)(1 − a). With s_w = s_r = s, V = (1 − s)(a − π). The value is linear in π and is zero at π* = (1 − s_w)a / [(1 − s_w)a + (1 − s_r)(1 − a)], which equals a in the symmetric case. All proofs are in Appendix A.');
P('*Proposition 2 (complementarity).* In the symmetric case, with integrity i = 1 − s, V = i(a − π), so the cross-partial derivative with respect to a and i is one. Neither ability nor integrity is valuable alone.');
P('*Proposition 3 (the sign of the value of integrity).* dV/ds = −(a − π). Deference lowers the naive requester’s value if and only if the delegate is more accurate than her preference, a > π. If a < π, deference raises her value, because it moves the outcome back toward her prior. Integrity matters exactly where delegation is worth doing.');
P('*Proposition 4 (overstatement).* The share of the ability-based value a − π that is lost to deference is s, whatever π. A buyer who values a delegate by a − π overstates its value by the factor 1/(1 − s).');
P('*Proposition 5 (a sophisticated requester).* If the requester knows the parameters and updates, her value is weakly decreasing in s, and strictly where the report would change her decision. Hence the benefit of deference in Proposition 3 belongs to the naive requester alone. The reason is that the report of a deferential delegate is a garbling of the report of a non-deferential one, which Blackwell (1953) ranks as less informative for every decision maker.');
P('*Proposition 6 (ranking reversals).* For two delegates with a_1 > a_2, V_1 − V_2 = N + π(s_1 − s_2) with N = (1 − s_1)a_1 − (1 − s_2)a_2. If s_1 > s_2 the less able delegate is better for requesters with weak priors, π < −N/(s_1 − s_2). If s_1 < s_2 the less able delegate is better only for π > N/(s_2 − s_1), a region at or beyond π = a_1 in all our data, where review has no value to begin with.');
P('*Proposition 7 (validity of ability as a ranking cue).* Ranking by ability is value-optimal for every prior in [0, 1] if and only if, for every pair with a_1 > a_2, (1 − s_1)a_1 ≥ (1 − s_2)a_2 and (1 − s_1)(1 − a_1) ≤ (1 − s_2)(1 − a_2). The first inequality compares integrity-weighted ability, the second integrity-weighted error.');
P('*Proposition 8 (implied prices).* Suppose the process can hide the stance from the delegate at a cost of δ in ability, so that a blinded delegate does not defer and yields a − δ − π. Blinding is better if and only if δ < s(a − π); it never helps when a ≤ π. The same expression, s(a − π), is the largest amount of value that a buyer who observes s should be willing to pay for a non-deferential version of the same delegate, that is, the willingness to pay for integrity, in units of the requester’s accuracy.');

// =============== Empirical design
c.push(H1('Measurement'));
c.push(H2('Items, Channels, and Parameters'));
P('Each bank has 120 stems, 20 in each of six domains, crossed with two channels. Every stem has three options with fixed roles: the gold action, the unsupported action that the stance endorses, and a third option. In the normative channel the model sees the evidence only. In the stance channel it sees the evidence plus one of four sentences supporting the unsupported action; in Study 1 the sentences state a preference, and in Study 1b they assert unverifiable support (a colleague has reviewed it, long experience, a lawyer’s confirmation, precedent). Letters are assigned to roles by a hash of the stem identifier and are identical in both channels. The parameters map to the model as follows: a is the share correct in the normative channel (RN); the pressure gap is RN minus the share correct in the stance channel (CorrectSocial); and s_w is the share of correct stance-free answers that become the stance-endorsed answer under the stance (conditional deference, CondRS, which equals Flip divided by RN). Under the model the pressure gap equals s_w·a.');
P('The easy bank (Study 1) used domains such as expected value, policy lookup, ledger consistency, fine-tune authorization, eligibility, and prohibited assurance. The hard bank (Study 1b) replaced them with a two-stage gamble with a launch cost, a rule with an exception and a cap, a ledger with a credit and tax, an under-determined case in which the decisive fact is missing, a versioned rule with an effective date, and unit conversion and ratios. Each bank was audited with an independent re-solver that parses the stem text, and gold letters are balanced. The registered blind human review of the keys was not carried out. Study 1b followed a registered plan with a pilot gate on a different seed (mean accuracy between .35 and .90, at least four of six domains between .15 and .95, and at least one model with conditional deference of at least .05); the gate passed at the first attempt and no parameter was changed.');
c.push(H2('Models'));
P('Study 1 queried one commercial ladder (Claude Haiku 4.5, Sonnet 5.5, Opus 5.5, Fable 5.1). Study 1b added ten open-weight dense instruct models served through a hosted aggregator (Qwen2.5 7B and 72B; Llama-3.1 8B and 70B; Gemma-3 4B, 12B, and 27B; Ministral 3B, 8B, and 14B) and queried the commercial ladder again. Reasoning-first models were left out so that reasoning would not be confounded with size. Tiers are within-family orderings, not independent variation in size: families differ in generation and post-training, and the aggregator does not let us control hardware or quantization. The runner omits the temperature argument for the Sonnet, Opus, and Fable tiers, which the provider’s documentation lists as rejecting it. One completion was drawn per query, with a limit of 512 tokens and the same system prompt for every model.');
c.push(H2('Estimation and Registered Hypotheses'));
P('The registered hypotheses concern the comparative statics of the parameters in size within a family: H1, the larger tier has higher a; H2, it is not less deferential, tested against a margin of five percentage points; H3, conditional deference rises with tier. We estimate linear probability models with family and domain fixed effects, standard errors clustered by stem, and Holm adjustment for RN and Flip. Because clustering by stem treats the models as fixed, we also report within-family Large-minus-Small differences with bootstrap intervals over stems and an exact sign test over families; with five families the smallest attainable two-sided p value is .0625. Failed parses are coded zero and also dropped in a sensitivity analysis. The open-weight sample and the commercial ladder are analyzed separately. A registered informativeness rule required mean accuracy in the open sample between .35 and .95 and conditional deference above .02 in at least one tier.');

// =============== Results
c.push(H1('Results'));
c.push(H2('Study 1: A Ceiling and a Floor'));
P('In the commercial ladder on the easy bank, a was .992 for Haiku and 1.000 for the three larger tiers, and deference was .025, .025, .017, and .000 (eight deferring answers in 480). The Large-minus-Small difference in RS was −0.008 with a 90 percent interval of [−0.040, +0.023], but the interval describes two tiers with two or three deferring answers each. The only significant contrast was in CorrectSocial, explained by the smallest tier choosing the third option on 10 of 120 stems and not by deference. Study 1 was uninformative about the comparative statics, and the follow-up replaced the bank under the registered gate.');
c.push(H2('Study 1b: Comparative Statics in Size'));
P('The informativeness rule was met: mean a across the ten open models was .75 (range .53 to .91). In the open-weight sample, larger tiers had higher a (Large +0.265, Mid +0.199; both p < .001; H1 supported) and lower deference: RS fell by 0.292 and conditional deference by 0.238 for Large (90 percent interval [−0.297, −0.179]; H2 not supported, because the interval lies wholly below −5 points; H3 not supported). Flip fell by 0.077 (p = .009). With failed rows dropped the estimates were similar (RS −0.319, conditional deference −0.238). The direction held in every family (Table 1): a was higher in the larger tier in four of five families (the commercial ladder was at ceiling in both), and RS and conditional deference were lower in all five (exact sign test p = .062). Gemma-3 was the exception in one respect: from the 12B to the 27B variant a rose from .783 to .883 and RS stayed at .525, so accuracy and deference separated.');
c.push(...tcap(1, 'Large Minus Small by Family (95% Bootstrap Interval over Stems)'));
c.push(atable(['Family', 'a (RN)', 'RS', 'Conditional RS (s_w)', 'Flip'], [
  ['Claude', '+0.000 [+0.000, +0.000]', '−0.050 [−0.092, −0.017]', '−0.050 [−0.092, −0.017]', '−0.050 [−0.092, −0.017]'],
  ['Gemma-3', '+0.358 [+0.258, +0.458]', '−0.183 [−0.292, −0.083]', '−0.128 [−0.262, +0.004]', '+0.108 [−0.000, +0.225]'],
  ['Llama-3.1', '+0.142 [+0.042, +0.242]', '−0.217 [−0.317, −0.108]', '−0.183 [−0.291, −0.069]', '−0.117 [−0.208, −0.017]'],
  ['Ministral', '+0.192 [+0.083, +0.292]', '−0.275 [−0.392, −0.150]', '−0.209 [−0.351, −0.072]', '−0.092 [−0.192, +0.008]'],
  ['Qwen2.5', '+0.367 [+0.267, +0.467]', '−0.492 [−0.583, −0.400]', '−0.453 [−0.584, −0.326]', '−0.208 [−0.308, −0.108]'],
], [1200, 2000, 2000, 2200, 1960]));
c.push(tnote('Failed rows coded zero (registered primary). Sign test across the five families: a higher in 4 of 5 (p = .125); RS lower in 5 of 5 (p = .062); conditional RS lower in 5 of 5 (p = .062).'));
c.push(H2('Calibration: Ability, Deference, and the Value of Review'));
P('Table 2 gives the measured a, the implied s_w = Flip / RN, and the pressure gap, and then the value of review in the symmetric case, V = (1 − s)(a − π), at three priors. Here s_w is used as the common deference rate s; this is a maintained assumption that the aligned-stance design described below is built to test. The pressure gap lies close to the Flip rate across the fourteen models (r = .98; mean absolute difference .025), as the model implies. Three features stand out. First, the share of ability-based value lost to deference, s, runs from 0 for three commercial tiers to .62 for Gemma-3-4B, and among the large open models from .10 (Qwen2.5-72B) to .49 (Gemma-3-27B). Second, at weak and moderate priors the value of the large open models differs widely at similar ability: at π = .5, Ministral-14B (a = .825) yields .256 and Gemma-3-27B (a = .883) yields .195. Third, at a strong prior (π = .9) the value of review is near zero or negative for every open model, since no open model is clearly more accurate than a requester who is right nine times in ten, and deference then reduces the harm in the small models (Proposition 3).');
c.push(...tcap(2, 'Ability, Deference, Pressure Gap, and Value of Review at Three Priors (Symmetric Case)'));
c.push(atable(['Model (tier)', 'a', 's = Flip/RN', 'Pressure gap', 'V(π = .5)', 'V(π = .7)', 'V(π = .9)'], [
  ['Qwen2.5-7B (S)', '.542', '.554', '.350', '+.019', '−.071', '−.160'],
  ['Qwen2.5-72B (L)', '.908', '.101', '.058', '+.367', '+.187', '+.007'],
  ['Llama-3.1-8B (S)', '.758', '.340', '.200', '+.170', '+.038', '−.094'],
  ['Llama-3.1-70B (L)', '.900', '.158', '.108', '+.337', '+.168', '+.000'],
  ['Gemma-3-4B (S)', '.525', '.619', '.300', '+.010', '−.067', '−.143'],
  ['Gemma-3-12B (M)', '.783', '.457', '.333', '+.154', '+.045', '−.064'],
  ['Gemma-3-27B (L)', '.883', '.490', '.425', '+.195', '+.093', '−.009'],
  ['Ministral-3B (S)', '.633', '.422', '.241', '+.077', '−.039', '−.154'],
  ['Ministral-8B (M)', '.783', '.298', '.225', '+.199', '+.058', '−.082'],
  ['Ministral-14B (L)', '.825', '.212', '.200', '+.256', '+.098', '−.059'],
  ['Claude Haiku (S)', '1.000', '.050', '.092', '+.475', '+.285', '+.095'],
  ['Claude Sonnet (M)', '1.000', '.000', '.008', '+.500', '+.300', '+.100'],
  ['Claude Opus (L)', '1.000', '.000', '.000', '+.500', '+.300', '+.100'],
  ['Claude Fable (XL)', '1.000', '.000', '.008', '+.500', '+.300', '+.100'],
], [2300, 800, 1400, 1400, 1150, 1150, 1160]));
c.push(tnote('a = share correct without a stance; s = conditional deference = Flip divided by RN; pressure gap = RN minus the share correct under the stance; V = (1 − s)(a − π) under the symmetric assumption. Registered coding (failed rows coded zero). Values are point estimates without intervals.'));
c.push(H2('Is Ability a Valid Ranking Cue?'));
P('Across the ten open models the relation between a and s was strong (Pearson r = −.83, Spearman ρ = −.88), stronger within families (r = −.93 after centering on the family mean) than between family means (r = −.73 across four families, not distinguishable from zero). About 37 percent of the variance in RS among the ten models lies between families. Applying Proposition 7 to the 45 pairs of open models, ranking by ability is value-optimal for every prior in [0, 1] in 34 pairs. The eleven exceptions are reversals in which a less able delegate is better for some priors; the economically relevant ones (reversal at π below a) involve Gemma-3: for Gemma-3-27B against Ministral-14B the less able Ministral is better for π < .72, and against Llama-3.1-8B for π < .33. The regret of ranking by ability is small, averaging .003 of accuracy at π = .5 and .0005 at π = .7, with 9 and 7 percent of pairs misranked and a maximum of .061. Ability is therefore a good ranking cue among these models and a poor predictor of the level of value, which it overstates by the factor 1/(1 − s) (Proposition 4).');
c.push(H2('Implied Prices'));
P('Proposition 8 gives the willingness to pay for integrity, s(a − π), and the largest ability sacrifice worth making to blind the delegate to the stance. At π = .5 these are .041 for Qwen2.5-72B, .063 for Llama-3.1-70B, .069 for Ministral-14B, and .188 for Gemma-3-27B; at π = .7 they are .021, .032, .027, and .090. A buyer comparing Gemma-3-27B with a non-deferential version of itself should pay up to 19 points of accuracy for the difference at a moderate prior; for Qwen2.5-72B the figure is 4 points.');
c.push(H2('The Case in Which the Requester Is Right'));
P('[To be completed when the registered aligned-stance channel (Addendum 3 of the Study 1b plan) has been run: the share correct when the stance supports the gold action, P_a; the follow rate under a right stance among stems the model otherwise misses, Rescue; their comparison with the follow rate under a wrong stance, which tests s_w = s_r; the model-free value V_obs(π) = π·P_a + (1 − π)·P_w − π with bootstrap intervals; and the same analyses with failed rows dropped and with Domain 6 excluded. If Rescue and s_w differ, Table 2 and Propositions 2 and 4 are restated with the asymmetric rates of Proposition 1.]');

// =============== Discussion
c.push(H1('Discussion'));
P('The registered prediction that scale would not lower deference is rejected. Larger tiers were more able and less deferential in every family, and the relation between the two was strong across models, so ability is an informative cue for the buyer. The informativeness is limited in two ways that the model makes precise. The cue ranks well but misstates levels: the value of a delegate falls short of its ability-based value by the share s, which in our data reaches .49 among the largest open models and .62 among small ones. And the cue fails in a particular direction, since the exceptions involve the model with high ability and high deference, the case in which a naive buyer pays for ability that the requester cannot use.');
P('The model sharpens how deference should be thought of. It is a cost only when the delegate is better than the requester’s prior, and it can be a benefit, for a naive requester, when the delegate is worse; but a rational requester never benefits (Proposition 5), so the policy question is whether the requester can be assumed to discount the report. Where a firm cannot assume this, the relevant quantity is the pressure gap, the accuracy lost when the preference is visible, and our measurements show that it is 20 points or more for two of the four largest open models and below 10 points for all four commercial tiers.');
P('Two implications for practice follow from Proposition 8 and apply within the evidence we have. A pressure test, which measures s and the pressure gap by posing the firm’s own decisions with and without a stated preference, has a quantifiable value: it identifies delegates for which the ability-based valuation is overstated by a large share. And blinding the delegate to the requester’s preference, where the process allows, is worth up to s(a − π) in accuracy for each delegate, which in our data ranges from 4 to 19 points for the large open models at a moderate prior. We did not test blinding itself, and the actual cost δ depends on how much context the delegate loses.');
c.push(H2('Limitations'));
P('We study models, not people, and the model assumes either a naive requester who adopts the report or a Bayesian who knows the parameters; we make no claim about how people behave. The actions are binary and the evidence signal is symmetric; the delegate’s deference is treated as independent of the stem; costs and prices enter only through Proposition 8. Parameters come from synthetic template-generated items, one stance format per study, single-turn first choices, and hosted inference without control of hardware or quantization. Tiers differ in more than size, and five families do not support a claim about scale in general. The calibration in Table 2 is a set of point estimates without intervals and rests on the symmetric assumption until the aligned-stance channel is run. The registered blind review of the keys was not carried out. The hard bank was built after seeing that the easy bank had no variance; it was fixed under a pre-registered gate and not tuned on hypothesis-test results, but the two banks are not directly comparable. A defect in the frozen hard bank was found afterwards: the stance phrase of the stems in Domain 6 is ungrammatical in the stance-against-evidence channel (for example, “we should outside the policy limit”); it was not changed, and sensitivity analyses that exclude Domain 6 are specified in advance.');
c.push(H2('Future Research'));
P('The aligned-stance channel identifies the follow rate under a right stance and tests the symmetric case. A wording-robustness replication with alternative system prompts and the second stance list, and three further families, are registered and would raise the number of families to eight. Within a vendor, pairs of models that differ in post-training at a fixed size would separate scale from recipe. The most direct test of the buyer’s problem is a study of how people choose and rely on delegates given cues of ability and an unobserved integrity, which would test the behavioral side that the model sets aside.');
c.push(H1('Conclusion'));
P('A delegate that defers sells the principal her own prior. In an economic model of delegated review, its value is (1 − s)(a − π): ability and integrity are complements, integrity matters where delegation matters, and ranking by ability alone preserves the order of delegates in most pairs of real models but overstates the level of value by the share s. In fourteen models, larger tiers were more able and less deferential in every family, so the buyer’s heuristic is informative; yet the largest open models still lost 6 to 43 points of accuracy under pressure. We derive the prices that follow, the willingness to pay for integrity and the value of blinding, and state the restriction that the registered aligned-stance channel will test.');

// =============== Appendix
c.push(pageBreak());
c.push(H1('Appendix A. Proofs'));
P('*Proof of Proposition 1.* Accuracy with review is π[s_r + (1 − s_r)a] + (1 − π)(1 − s_w)a, because when S is right the delegate reports S with probability s_r and otherwise reports the correct answer with probability a, and when S is wrong the delegate reports the correct answer, which is not S, with probability (1 − s_w)a. Subtracting π gives V = (1 − π)(1 − s_w)a − π(1 − s_r)(1 − a), since π[s_r + (1 − s_r)a] − π = −π(1 − s_r)(1 − a). With s_w = s_r = s, V = (1 − s)[(1 − π)a − π(1 − a)] = (1 − s)(a − π). The zero of V solves (1 − π)(1 − s_w)a = π(1 − s_r)(1 − a).');
P('*Proof of Propositions 2 to 4.* V = i(a − π) with i = 1 − s. The cross-partial ∂²V/∂a∂i equals one. dV/ds = −(a − π) has the sign of π − a. The loss share is 1 − V/(a − π) = s for a ≠ π.');
P('*Proof of Proposition 5.* Let the report be r ∈ {S, not S}. With probability 1 − s the delegate reports a binary signal that equals the correct action with probability a; with probability s it reports S. The experiment E_s is therefore E_0 followed by a garbling that replaces the signal by the constant S with probability s. By Blackwell (1953), for every decision problem the value of E_s is weakly below that of E_0, and the same argument orders E_s and E_s′ for s < s′. The inequality is strict when the signal would have changed the decision.');
P('*Proof of Proposition 6.* V_1 − V_2 = (1 − s_1)(a_1 − π) − (1 − s_2)(a_2 − π) = N + π(s_1 − s_2). It is negative iff π < −N/(s_1 − s_2) when s_1 > s_2, and iff π > N/(s_2 − s_1) when s_1 < s_2.');
P('*Proof of Proposition 7.* V_1 − V_2 is linear in π, so it is nonnegative on [0, 1] if and only if it is at both endpoints. At π = 0 it equals (1 − s_1)a_1 − (1 − s_2)a_2; at π = 1 it equals −(1 − s_1)(1 − a_1) + (1 − s_2)(1 − a_2).');
P('*Proof of Proposition 8.* The blinded delegate does not defer, so its value is a − δ − π. It exceeds (1 − s)(a − π) iff a − δ − π > (1 − s)(a − π), that is, iff δ < s(a − π). If a ≤ π the right side is nonpositive and the inequality fails for δ ≥ 0. The willingness to pay for a non-deferential version of the same delegate, in units of the requester’s accuracy, is the difference of values, (a − π) − (1 − s)(a − π) = s(a − π). A numerical check of all propositions on 20,000 random parameter draws is in the replication package (model_check.py).');

// =============== References
c.push(pageBreak());
c.push(H1('References'));
const refs = [
  'Aghion, P., & Tirole, J. (1997). Formal and real authority in organizations. *Journal of Political Economy, 105*(1), 1–29.',
  'Agrawal, A., Gans, J. S., & Goldfarb, A. (2019). Exploring the impact of artificial intelligence: Prediction versus judgment. *Information Economics and Policy, 47*, 1–6.',
  'Baird, A., & Maruping, L. M. (2021). The next generation of research on IS use: A theoretical framework of delegation to and from agentic IS artifacts. *MIS Quarterly, 45*(1), 315–341.',
  'Blackwell, D. (1953). Equivalent comparisons of experiments. *Annals of Mathematical Statistics, 24*(2), 265–272.',
  'Board of Governors of the Federal Reserve System. (2011). *Supervisory guidance on model risk management* (SR Letter 11-7).',
  'Crawford, V. P., & Sobel, J. (1982). Strategic information transmission. *Econometrica, 50*(6), 1431–1451.',
  'Dessein, W. (2002). Authority and communication in organizations. *Review of Economic Studies, 69*(4), 811–838.',
  'Eisenhardt, K. M. (1989). Agency theory: An assessment and review. *Academy of Management Review, 14*(1), 57–74.',
  'Fügener, A., Grahl, J., Gregory, A., & Kühl, N. (2022). Cognitive challenges in human–artificial intelligence collaboration: Investigating the path toward productive delegation. *Information Systems Research, 33*(2), 678–696.',
  'Hoffmann, J., Borgeaud, S., Mensch, A., et al. (2022). Training compute-optimal large language models. *Advances in Neural Information Processing Systems, 35*.',
  'Holm, S. (1979). A simple sequentially rejective multiple test procedure. *Scandinavian Journal of Statistics, 6*(2), 65–70.',
  'Jensen, M. C., & Meckling, W. H. (1976). Theory of the firm: Managerial behavior, agency costs and ownership structure. *Journal of Financial Economics, 3*(4), 305–360.',
  'Kaplan, J., McCandlish, S., Henighan, T., Brown, T. B., Chess, B., Child, R., Gray, S., Radford, A., Wu, J., & Amodei, D. (2020). *Scaling laws for neural language models* (arXiv:2001.08361). arXiv.',
  'Lakens, D. (2017). Equivalence tests: A practical primer for t tests, correlations, and meta-analyses. *Social Psychological and Personality Science, 8*(4), 355–362.',
  'Ouyang, L., Wu, J., Jiang, X., et al. (2022). Training language models to follow instructions with human feedback. *Advances in Neural Information Processing Systems, 35*.',
  'Perez, E., Ringer, S., Lukošiūtė, K., et al. (2022). *Discovering language model behaviors with model-written evaluations* (arXiv:2212.09251). arXiv.',
  'Prendergast, C. (1993). A theory of “yes men.” *American Economic Review, 83*(4), 757–770.',
  'Sarker, S., Chatterjee, S., Xiao, X., & Elbanna, A. (2019). The sociotechnical axis of cohesion for the IS discipline: Its historical legacy and its continued relevance. *MIS Quarterly, 43*(3), 695–719.',
  'Sharma, M., Tong, M., Korbak, T., et al. (2023). *Towards understanding sycophancy in language models* (arXiv:2310.13548). arXiv.',
];
for (const r of refs) c.push(new Paragraph({ spacing: { line: DOUBLE, before: 0, after: 0 }, indent: { left: 720, hanging: 720 }, children: runs(r) }));

const doc = makeDoc(c, { title: TITLE });
D.Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2], b); console.log('abstract words:', ABSTRACT.split(/\s+/).length); });
