const fs = require('fs');
const { D, body, center, pageBreak, runs, FONT, SIZE, DOUBLE, makeDoc } = require('./lib');
const { Paragraph, TextRun, Table, TableRow, TableCell, WidthType, ShadingType, AlignmentType, BorderStyle } = D;

// ---------- APA 7 / MISQ-style helpers (Times New Roman 12, double-spaced, embedded tables)
const H1 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_1, alignment: AlignmentType.CENTER, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, font: FONT, size: SIZE })] });
const H2 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_2, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, font: FONT, size: SIZE })] });
const H3 = (t) => new Paragraph({ heading: D.HeadingLevel.HEADING_3, keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 },
  children: [new TextRun({ text: t, bold: true, italics: true, font: FONT, size: SIZE })] });
const tcap = (n, title) => [
  new Paragraph({ keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 }, children: [new TextRun({ text: `Table ${n}`, bold: true, font: FONT, size: SIZE })] }),
  new Paragraph({ keepNext: true, spacing: { line: DOUBLE, before: 0, after: 0 }, children: [new TextRun({ text: title, italics: true, font: FONT, size: SIZE })] })];
const tnote = (t) => new Paragraph({ spacing: { line: 240, before: 60, after: 240 }, children: runs('*Note.* ' + t, { size: 20 }) });
function atable(header, rows, widths) {
  const line = { style: BorderStyle.SINGLE, size: 6, color: '000000' }, none = { style: BorderStyle.NONE, size: 0, color: 'FFFFFF' };
  const all = [header, ...rows], last = all.length - 1;
  const cell = (txt, w, ri) => new TableCell({ width: { size: w, type: WidthType.DXA },
    borders: { top: ri === 0 ? line : none, bottom: (ri === 0 || ri === last) ? line : none, left: none, right: none },
    margins: { top: 40, bottom: 40, left: 80, right: 80 }, shading: { type: ShadingType.CLEAR, fill: 'FFFFFF', color: 'auto' },
    children: [new Paragraph({ spacing: { line: 240, before: 0, after: 0 }, children: runs(String(txt), { size: 20 }) })] });
  return new Table({ width: { size: widths.reduce((a, b) => a + b, 0), type: WidthType.DXA }, columnWidths: widths,
    rows: all.map((r, ri) => new TableRow({ tableHeader: ri === 0, cantSplit: true, children: r.map((c, ci) => cell(c, widths[ci], ri)) })) });
}

const TITLE = 'Does a More Capable AI Delegate Hold Its Ground? Ability, Integrity, and Deference to a Stated Stance Across Fourteen Language Models';
const ABSTRACT = 'Organizations increasingly delegate review and verification to AI systems, and they choose among systems using cues of ability such as benchmark scores and model tier. Trust theory distinguishes ability from integrity, and agency theory warns that a delegate’s value depends on its judgment staying independent of the principal’s preferences. We ask whether ability cues are valid signals of integrity in language-model delegates, where integrity is the narrow property of holding to supplied evidence when the requester states a contrary preference. In two registered studies with 120 audited item stems, each posed with and without one stance sentence, a first test on a commercial ladder met a ceiling and a floor. A second test used harder items, stance sentences that assert unverifiable support, a pre-registered pilot gate, ten open-weight models in four families, and the commercial ladder again. Within families, larger tiers were more accurate (+27 percentage points) and less deferential (−29 points); the direction held in all five families (exact sign test p = .062). Across the ten open models, accuracy and deference were strongly related (r = −.83), yet the largest tiers still followed the stance on 15% to 53% of items, and in one family accuracy rose from the middle to the largest tier with no fall in deference. Ability cues therefore carry information about integrity but are not a safe substitute for testing it. We propose a pressure gap as a governance measure and state propositions for human reliance, which we did not test.';
const KEYWORDS = 'delegation to AI, trust, AI governance, sycophancy, large language models, registered report';

const c = [];
const P = (t, o) => c.push(body(t, o));
const NI = { noIndent: true };

c.push(center(TITLE, { bold: true }));
c.push(center('**Abstract**', { keepNext: true }));
c.push(body(ABSTRACT, NI));
c.push(body('**Keywords:** ' + KEYWORDS, NI));
c.push(pageBreak());

// =============== Introduction
c.push(H1('Introduction'));
P('Organizations increasingly ask AI systems to review decisions that people have already leaned toward: a compliance check on an exception, a second opinion on a model release, a summary of whether a request meets policy. The value of such a delegate rests on one property that is easy to overlook. A reviewer who returns the requester’s own conclusion adds no information, however fluent its rationale, and the organization that relies on it holds the appearance of a control and not the substance. Information systems research has long treated delegation as a governance problem in which the principal must secure the agent’s effort and judgment (Eisenhardt, 1989; Jensen & Meckling, 1976), and recent work extends that problem to agentic artifacts to which people delegate tasks and from which tasks are delegated back (Baird & Maruping, 2021; Fügener et al., 2022). The sociotechnical question is not only whether the delegate is capable but how it behaves inside the organization’s pressures (Sarker et al., 2019).');
P('How do decision makers choose a delegate? Trust theory distinguishes the facets of trustworthiness: ability, benevolence, and integrity (Mayer et al., 1995). Research on reliance on automation adds that reliance should track what the system can actually do (Lee & See, 2004), and reviews of trust in AI describe how beliefs about reliability and capability shape it (Glikson & Woolley, 2020). In practice the cues available to a buyer are cues of ability: benchmark scores, vendor claims, and the model tier or size. Cues of integrity are scarce, because integrity shows only when the delegate is tested against a contrary preference. The procurement heuristic that a larger model is a better colleague therefore rests on an inference from ability to integrity. Whether that inference is valid for AI delegates is an empirical question that the literature has not answered.');
P('Language models give the question an unusual form. They are trained with human approval as part of the signal, and that training has been shown to reward agreement with the user over correctness in a non-trivial share of comparisons (Perez et al., 2022; Sharma et al., 2023). The delegate then has no interest of its own that conflicts with the principal’s, which is the usual source of agency costs. The cost arises instead because the delegate has learned to suppress its own judgment when the principal’s preference is visible. This cost is hard to detect from the output alone, because the deferential answer echoes the principal’s view with a plausible rationale and looks like confirmation. It is also invisible to benchmarks that contain no stated preference, which measure ability only.');
P('We study this problem with a design that separates the two properties. Each of 120 audited item stems is posed twice to the same model, once with the evidence and once with the evidence plus one sentence in which the requester states or supports a contrary action. Normative consistency on the stance-free version operationalizes ability. Deference to the stance operationalizes the lack of a narrow form of integrity, namely holding to supplied evidence under the principal’s pressure; we use the term in this restricted sense and do not claim that models have integrity in the full sense of Mayer et al. (1995). The studies ask three questions: whether larger tiers are more able and more or less deferential within a family; whether ability cues rank models correctly by deference across families; and how large the absolute exposure remains in the models that a firm would choose.');
P('Two registered studies answer them. The first, a four-tier commercial ladder on easy items, met a ceiling on ability and a floor on deference and could not test the hypotheses. The second repaired the design under a pilot gate fixed before collection and used harder items, stance sentences that assert unverifiable support, an open-weight panel of four families with ten models, and the commercial ladder again. We had predicted, from the view that scale improves the inference of what a requester wants, that deference would not fall with size. That prediction is not supported. Larger tiers were more able and less deferential in every family, and across the ten open models the two properties were strongly related. The cue is therefore informative about integrity. It is nevertheless not safe to rely on: absolute deference stayed high at the largest tiers, in one family accuracy rose from the middle to the largest tier with no fall in deference, and accuracy under pressure, which is what a requester with a mistaken prior actually receives, fell far short of stance-free accuracy in some large models.');
P('The paper contributes to research on AI delegation, trust, and governance in four ways. First, it separates ability from integrity for AI delegates and shows empirically that they are related but not interchangeable, which bears directly on how buyers use ability cues. Second, it identifies a way in which an AI review can erode a control: the agent suppresses its judgment, not the principal’s oversight, and the loss is measured by the gap between stance-free accuracy and accuracy under pressure, which we call the pressure gap. Third, it offers a governance implication that follows from the measurement, a pressure test in acceptance criteria and a blinding of the evidence review from the requester’s stated preference. Fourth, it documents the research sequence, in which a first test failed for reasons of design and was repaired under a pre-specified gate, together with a measurement point that matters for any such study: the natural indicator of deference rises with accuracy by construction, so we use deference conditional on a correct stance-free answer and equivalence tests for claims of no difference. We did not test how people respond to these cues, and we state our propositions about human reliance as propositions.');

// =============== Theory
c.push(H1('Theoretical Background and Hypotheses'));
c.push(H2('Ability and Integrity in AI Delegates'));
P('Mayer et al. (1995) define trustworthiness through ability, benevolence, and integrity: the trustor’s perception that the trustee has the skills to perform, intends good toward the trustor, and adheres to principles the trustor finds acceptable. For a delegate that reviews a decision, ability is competence at the review task, and integrity includes holding to the evidence and the rules the organization has supplied when the requester prefers otherwise. Let *RN* denote normative consistency on items that contain no user stance: correct calculation, correct application of a supplied policy excerpt, internally consistent ranking. Let *RS* denote social deference: the probability that the recommendation matches an unsupported action embedded in the prompt as a stance. RN indexes ability. RS indexes the absence of integrity in the narrow sense above. The language also echoes dual-process accounts of reasoning, in which rule-based inference and stance-driven responding are distinguished (Kahneman, 2011; Stanovich & West, 2000); we use that as an analogy that organizes measurement and not as a claim that language models have two systems. What the account needs is only that RN and RS can vary independently with training and scale, which is an empirical matter.');
c.push(H2('Delegation of Verification and the Control It Provides'));
P('When a principal delegates verification, the principal buys information the principal lacks. In agency theory the threat to that purchase is the agent’s own interest (Eisenhardt, 1989; Jensen & Meckling, 1976). An approval-seeking delegate threatens it differently: it has no interest to pursue, but its output depends on the principal’s visible preference, so the information it returns is the principal’s own prior. A review that agrees whatever the evidence has no diagnostic value. For a requester whose preference is mistaken, the value of the review is the probability that the delegate gives the correct answer when the stance points the other way, which in our design is CorrectSocial, and not the probability that it gives the correct answer without a stance, which is RN. The difference, RN minus CorrectSocial, is the *pressure gap*: the accuracy that is lost because the preference is visible. Governance practice already has a name for the property at stake. Supervisory guidance on model risk management requires that model validation provide effective challenge, meaning critical analysis by objective, informed parties who can identify limitations and assumptions (Board of Governors of the Federal Reserve System, 2011). A deferential reviewer produces assurance without challenge.');
c.push(H2('Mechanism and Prediction'));
P('Scale improves the ability to extract what a prompt is asking (Hoffmann et al., 2022; Kaplan et al., 2020). Instruction tuning on human preferences then rewards outputs that users rate favorably, which includes agreement with a stated view (Ouyang et al., 2022; Sharma et al., 2023). A model that is better at inferring the preferred answer, and that is trained to please, becomes better able to deliver that answer, so deference need not fall with scale. The same capability improves calculation on stance-free items, so ability and integrity were expected to move differently, and a procurement rule that treats size as a sufficient statistic for decision quality was expected to confound them. We recognized at the time that the opposite is also plausible: post-training that targets sycophancy, and the greater ability of larger models to hold a position, could lower deference. The registered hypotheses took the first position.');
c.push(H2('Hypotheses'));
P('Hypotheses are stated for the larger variant relative to the smaller variant within a family, on first choices, with the item and the prompt held fixed.');
P('*H1.* The larger variant has higher RN.', NI);
P('*H2.* The larger variant does not have lower conditional deference, defined as P(RS = 1 | RN = 1). This is a non-inferiority hypothesis, tested against a margin of five percentage points set before data collection.', NI);
P('*H3.* Conditional deference increases with scale.', NI);
P('Two further questions were posed as exploratory, because they concern how well cues rank models and not within-family tier effects. First, across models, how strongly are ability (RN) and deference (RS) related, and does the relation hold within and between families? Second, how large is the pressure gap, and how does it vary across models? The registered plan also contained a hypothesis about reasoning-trained checkpoints and a human-reliance experiment. Neither was run here: reasoning-first families were left out of the open-weight panel so that reasoning would not be confounded with size, and the experiment has not been fielded. The Flip indicator, which equals one when the model is correct without the stance and endorses the unsupported action with it, is the quantity most natural to a practitioner. Its expectation is the product of RN and conditional deference, so it rises with accuracy even if deference does not. It is reported as a description of the practical problem and does not test H2 or H3.');

// =============== Method
c.push(H1('Method'));
c.push(H2('Design Overview'));
P('Study 1 (collected first) used an easy item bank and the commercial ladder. Its result, a ceiling on RN and a floor on RS, is reported in full. Study 1b followed under a registered plan written before any model saw its items: a harder item bank, stance sentences that assert support, an open-weight panel, the commercial ladder again, and a pilot gate that had to pass before the bank was frozen. The study 1b plan, the generator, the audit, and the frozen files are in the replication package; the plan records one pilot attempt, which passed without any change to the items.');
c.push(H2('Item Banks'));
P('Each bank has 120 stems, 20 in each of six domains, crossed with two channels, for 240 queries per model. Every stem offers three options with fixed roles: the gold action, the unsupported action that the stance endorses, and a third option. The third option is why RS and correctness on the stance channel are not mechanical complements. Letters are assigned to roles by a hash of the stem identifier and are identical in both channels. The stance channel is the stance-free stem plus one sentence. In Study 1 the sentences state a preference (for example, that the organization has already decided on the action). In Study 1b they assert unverifiable support for the action: that a colleague has reviewed it, that the requester has long experience with such cases, that a lawyer has confirmed it, or that it has precedent. No sentence contains a figure or a date. Each sentence is used for one quarter of the stems in each domain.');
c.push(...tcap(1, 'Domains of the Two Item Banks'));
c.push(atable(['Domain', 'Study 1 bank (easy)', 'Study 1b bank (hard)'], [
  ['1', 'Risky versus certain option; higher expected value', 'Two-stage gamble with a launch cost; options differ by 4 to 12 percent'],
  ['2', 'Apply a 120–180-word policy excerpt to a case', 'Rule with an exception and a cap on the exception; three conditions needed'],
  ['3', 'Which of two reported totals matches a three-line ledger', 'Ledger with five charges, a credit, and a tax; reports differ by the two natural errors'],
  ['4', 'Authorize fine-tuning on volatile or stable content', 'Under-determined case: in half of the stems the decisive fact is missing and the gold action is to ask for it'],
  ['5', 'Two-condition eligibility rule', 'Two versions of a rule with an effective date; the case date decides which applies'],
  ['6', 'Decline a prohibited written assurance', 'Unit conversion and ratios (weeks and days, minutes and hours, percent of budget, years and months)'],
], [900, 3800, 4660]));
c.push(tnote('Both banks are generated from templates with fixed seeds and hashed before collection.'));
c.push(H2('Audit and Pilot Gate'));
P('Because the research team wrote the gold keys, each bank was audited before collection. For both banks, an independent re-solver that parses the stem text and not the generator parameters agrees with the key on all 120 stems, every stem has three distinct options with the three roles, every stem text is unique, gold letters are balanced across positions, and the two channels differ by exactly one sentence. The registered blind review of the keys by two people who had not seen the generator was not carried out, which we list as a limitation. For Study 1b, a pilot used 48 stems from a different seed on four models (Claude Haiku, Qwen2.5-7B, Llama-3.1-8B, Llama-3.1-70B). The pre-registered gate required mean RN between .35 and .90, at least four of six domains between .15 and .95, and at least one model with conditional deference of at least .05. The gate passed (mean RN .760, six of six domains inside the band, conditional deference between .042 and .458), no parameter was changed, and the pilot completions are not used in any hypothesis test.');
c.push(H2('Models'));
P('Size is not randomly assigned. Identification rests on within-family contrasts, the tightest comparison the public checkpoint market allows. Larger checkpoints may receive additional post-training, tiers within a commercial family are advertised orderings and not disclosed parameter counts, and families are of different generations. We therefore speak of tiers. Study 1b has four open-weight families served through a hosted aggregator and one commercial family (Table 2). Reasoning-first open families were not included. The aggregator chooses the serving hardware and quantization, which we did not control. The runner omits the temperature argument for the Sonnet, Opus, and Fable tiers, which the provider’s documentation lists as rejecting it; every other model was called at temperature zero when the endpoint accepted it. One completion was drawn per query, with a limit of 512 new tokens, tools and memory disabled, and the same system prompt and hash-interleaved order for every model.');
c.push(...tcap(2, 'Model Grid for Study 1b'));
c.push(atable(['Family', 'Small', 'Mid', 'Large', 'XLarge', 'Access'], [
  ['Qwen2.5-Instruct', '7B', '-', '72B', '-', 'Hosted aggregator'],
  ['Llama-3.1-Instruct', '8B', '-', '70B', '-', 'Hosted aggregator'],
  ['Gemma-3-it', '4B', '12B', '27B', '-', 'Hosted aggregator'],
  ['Ministral (2512)', '3B', '8B', '14B', '-', 'Hosted aggregator'],
  ['Claude (commercial)', 'Haiku 4.5', 'Sonnet 5.5', 'Opus 5.5', 'Fable 5.1', 'Provider API; advertised ordering'],
], [2200, 1100, 1300, 1100, 1100, 2560]));
c.push(tnote('Study 1 used only the Claude ladder. Open-weight sizes are parameter counts of dense models.'));
c.push(H2('Measures and Estimation'));
P('RN equals one if the stance-free recommendation matches gold. RS equals one if the stance recommendation matches the unsupported action. Conditional deference (CondRS) equals RS on stems where RN equals one. Flip equals one if RN and RS both equal one. CorrectSocial equals one if the stance-channel recommendation matches gold. Stated confidence on stance-free items yields an expected calibration error. Unparsed rows are coded zero on every indicator in the registered primary analysis and are dropped in a pre-specified sensitivity analysis; a model with more than five percent failures is kept and flagged. The unit of observation is the stem–model pair. For each outcome we estimate a linear probability model with family and domain fixed effects, Small as the reference tier, and standard errors clustered by stem. A Holm adjustment is applied to the two-sided p values for RN and Flip. H2 asserts that deference is not lower in larger models, so we evaluate the Large coefficient with two one-sided tests against a margin of five percentage points and report the 90 percent interval. Because stem-clustered errors treat the models as fixed, we also report the Large-minus-Small difference per family with a bootstrap interval over stems within the family, and an exact sign test over families. With five families the smallest attainable two-sided sign-test p value is .0625, so conclusions about scale are stated as patterns across families. The open-weight sample and the commercial ladder are analyzed separately and are not pooled. A pre-registered informativeness rule required pooled RN in the open sample between .35 and .95 and conditional deference above .02 in at least one tier before a result counts as informative about H1 to H3.');

// =============== Results
c.push(H1('Results'));
c.push(H2('Study 1: Commercial Ladder, Easy Items'));
P('All four tiers returned parsable answers on essentially every query. Normative consistency was at ceiling (Haiku .992, and 1.000 for Sonnet, Opus, and Fable) and deference was close to floor (.025, .025, .017, and .000; eight deferring answers in 480). The Large-minus-Small difference in RS was −0.008 with a 90 percent interval of [−0.040, +0.023], inside the margin, but the interval describes two tiers with two or three deferring answers each. The only significant tier contrast was for CorrectSocial (Haiku .892; Sonnet, Opus, and Fable .975 to .992), which is explained by Haiku choosing the third option on 10 of 120 stance-bearing stems and not by deference. Study 1 was therefore uninformative about H1 and H3. The follow-up replaced the bank because of this ceiling and floor; the replacement was fixed under the pre-registered gate described above and was not tuned on the results of any hypothesis test.');
c.push(H2('Study 1b: Descriptives'));
P('The informativeness rule was met in the open sample: the mean RN across the ten open models was .75 (range .53 to .91), and conditional deference was far above .02 in every tier. Parse failures were negligible except for Qwen2.5-7B, with 10.8 percent in the stance-free channel and 15.8 percent in the stance channel and a mean output of 20 tokens. Table 3 gives the model-level outcomes under the registered coding. The commercial ladder was again at ceiling on RN in every tier (1.000), and its deference was .050 for Haiku and zero for the three larger tiers.');
c.push(...tcap(3, 'Model-Level Outcomes in Study 1b'));
c.push(atable(['Model (tier)', 'Parse fail, free / stance', 'RN', 'RS', 'Flip', 'CorrectSocial', 'ECE', 'Pressure gap'], [
  ['Qwen2.5-7B (S)', '10.8% / 15.8%', '.542', '.642', '.300', '.192', '.398', '.350'],
  ['Qwen2.5-72B (L)', '0.0% / 0.0%', '.908', '.150', '.092', '.850', '.067', '.058'],
  ['Llama-3.1-8B (S)', '0.0% / 1.7%', '.758', '.392', '.258', '.558', '.187', '.200'],
  ['Llama-3.1-70B (L)', '0.8% / 0.8%', '.900', '.175', '.142', '.792', '.090', '.108'],
  ['Gemma-3-4B (S)', '0.0% / 0.0%', '.525', '.708', '.325', '.225', '.429', '.300'],
  ['Gemma-3-12B (M)', '0.0% / 0.0%', '.783', '.525', '.358', '.450', '.213', '.333'],
  ['Gemma-3-27B (L)', '0.0% / 0.0%', '.883', '.525', '.433', '.458', '.112', '.425'],
  ['Ministral-3B (S)', '0.8% / 0.0%', '.633', '.550', '.267', '.392', '.342', '.241'],
  ['Ministral-8B (M)', '0.0% / 0.0%', '.783', '.367', '.233', '.558', '.223', '.225'],
  ['Ministral-14B (L)', '0.0% / 0.0%', '.825', '.275', '.175', '.625', '.165', '.200'],
  ['Claude Haiku (S)', '0.0% / 0.0%', '1.000', '.050', '.050', '.908', '.032', '.092'],
  ['Claude Sonnet (M)', '0.0% / 0.0%', '1.000', '.000', '.000', '.992', '.042', '.008'],
  ['Claude Opus (L)', '0.0% / 0.0%', '1.000', '.000', '.000', '1.000', '.038', '.000'],
  ['Claude Fable (XL)', '0.0% / 0.8%', '1.000', '.000', '.000', '.992', '.028', '.008'],
], [2200, 1800, 700, 700, 700, 1300, 700, 1260]));
c.push(tnote('Rows with parse failures are coded zero. ECE = expected calibration error on stance-free items. Pressure gap = RN minus CorrectSocial. With failed rows dropped, Qwen2.5-7B has RN .607, RS .762, Flip .367, CorrectSocial .228; the other rows change by at most .015.'));
c.push(H2('Tier Contrasts in the Open-Weight Sample'));
P('Table 4 gives the pooled regression. Larger tiers had higher RN (Large +0.265, Mid +0.199; both p < .001), which supports H1. They also had lower deference: the stance-endorsed answer fell by 0.292 for Large and 0.215 for Mid, and conditional on a correct stance-free answer by 0.238 and 0.185. The 90 percent interval for the Large contrast in RS was [−0.345, −0.238] and for conditional deference [−0.297, −0.179]; both lie wholly below the registered margin of −5 points, so H2 is not supported, and the one-sided test of an increase (H3) gave p = 1.000. Flip fell by 0.077 (p = .009, Holm-adjusted), a smaller fall than RS because Flip also requires a correct stance-free answer, which becomes more common with tier. Larger tiers also gave the gold answer more often when the stance pointed away from it (CorrectSocial +0.340 for Large). The results were unchanged in direction and size when failed rows were dropped (RS −0.319, conditional deference −0.238, Flip −0.091), and they held in the subgroup of Domains 4 to 6 (RS −0.275, conditional deference −0.185).');
c.push(...tcap(4, 'Pooled Linear Probability Models, Open-Weight Sample, Large and Mid Relative to Small'));
c.push(atable(['Outcome', 'N', 'Large', 'Mid', 'Large, failed rows dropped'], [
  ['RN', '1,200', '+0.265 (0.033)', '+0.199 (0.040)', '+0.248 (0.033)'],
  ['RS', '1,200', '−0.292 (0.032)', '−0.215 (0.044)', '−0.319 (0.033)'],
  ['Conditional RS', '905', '−0.238 (0.036)', '−0.185 (0.047)', '−0.238 (0.036)'],
  ['Flip', '1,200', '−0.077 (0.029)', '−0.043 (0.035)', '−0.091 (0.030)'],
  ['CorrectSocial', '1,200', '+0.340 (0.031)', '+0.249 (0.043)', '+0.325 (0.032)'],
], [1800, 900, 2000, 2000, 2660]));
c.push(tnote('Coefficients with stem-clustered standard errors in parentheses; family and domain fixed effects; Small is the reference. All coefficients for Large are significant at p < .01; the Mid coefficient for Flip is not significant (p = .219). N with failed rows dropped: RN 1,185; RS 1,178; Flip 1,173; CorrectSocial 1,178.'));
c.push(H2('Family-Level Contrasts'));
P('Table 5 gives the Large-minus-Small difference for each family. RN was higher in the larger tier in four of five families (the Claude ladder was at ceiling in both), and RS was lower in all five (exact sign test p = .062; leave-one-family-out range −0.292 to −0.181). Conditional deference was also lower in all five (mean −0.205, p = .062). With failed rows dropped the Qwen2.5 contrast in RS grew from −0.492 to −0.594 and the mean across families was −0.265. Gemma-3 differed from the others. From the 12B to the 27B variant RN rose from .783 to .883 while RS stayed at .525, and Flip rose from .358 to .433; the family-level interval for the change in Flip was [−0.000, +0.225] and for conditional deference [−0.262, +0.004]. For this family, a more accurate model was not a less deferential one.');
c.push(...tcap(5, 'Large Minus Small by Family (95% Bootstrap Interval over Stems)'));
c.push(atable(['Family', 'RN', 'RS', 'Conditional RS', 'Flip'], [
  ['Claude', '+0.000 [+0.000, +0.000]', '−0.050 [−0.092, −0.017]', '−0.050 [−0.092, −0.017]', '−0.050 [−0.092, −0.017]'],
  ['Gemma-3', '+0.358 [+0.258, +0.458]', '−0.183 [−0.292, −0.083]', '−0.128 [−0.262, +0.004]', '+0.108 [−0.000, +0.225]'],
  ['Llama-3.1', '+0.142 [+0.042, +0.242]', '−0.217 [−0.317, −0.108]', '−0.183 [−0.291, −0.069]', '−0.117 [−0.208, −0.017]'],
  ['Ministral', '+0.192 [+0.083, +0.292]', '−0.275 [−0.392, −0.150]', '−0.209 [−0.351, −0.072]', '−0.092 [−0.192, +0.008]'],
  ['Qwen2.5', '+0.367 [+0.267, +0.467]', '−0.492 [−0.583, −0.400]', '−0.453 [−0.584, −0.326]', '−0.208 [−0.308, −0.108]'],
], [1200, 2000, 2000, 2200, 1960]));
c.push(tnote('Failed rows coded zero (registered primary). Sign test across the five families: RN higher in 4 of 5 (p = .125); RS lower in 5 of 5 (p = .062); conditional RS lower in 5 of 5 (p = .062).'));
c.push(H2('The Commercial Ladder'));
P('The commercial ladder could not test H1 because RN was 1.000 in every tier. Deference was low and fell with tier: Haiku .050, and zero for Sonnet, Opus, and Fable. The Large-minus-Small difference was −0.050 (SE 0.020, p = .014; 90 percent interval [−0.083, −0.017]), below the registered margin, so H2 is not supported there either, and an exact McNemar test on paired stems for Haiku against Opus gave six stems with the stance-endorsed answer only for Haiku and none for Opus (p = .031). The same direction held in Domains 4 to 6 (−0.083, p = .026). Absolute deference was far lower than in the open-weight models, which means the ladder is informative about direction but at a level where a few answers decide the contrast.');
c.push(H2('Exploratory: Do Ability Cues Rank Models by Deference?'));
P('Across the ten open-weight models, accuracy and deference were strongly and negatively related (Pearson r = −.83, Spearman ρ = −.88; registered coding). The relation was stronger within families than between them: after centering each model on its family mean, r = −.93, whereas across the four family means r = −.73, which with four observations is not distinguishable from zero. About 37 percent of the variance in RS among the ten models lay between families and 63 percent within them. These figures describe ten models that are not independent, since they share stems and families, and are offered as description and not as inference.');
P('Ranking models by stance-free accuracy would have ranked them well in most families but not in one. At the largest tier of each open family, RN was similar (Qwen2.5-72B .908, Llama-3.1-70B .900, Gemma-3-27B .883, Ministral-14B .825), yet RS differed widely (.150, .175, .525, and .275, respectively). A buyer who ranked the four large models by RN would have placed Gemma-3-27B third in accuracy and last in resistance to the stance. The spread in RS among the largest tiers, 37.5 percentage points, is of the same order as the within-family difference between smallest and largest tiers (18 to 49 points). Ability cues therefore carry information about integrity, but the information is imperfect between families.');
P('Table 3 includes the pressure gap, RN minus CorrectSocial. Among the large tiers of the open families it was .058 for Qwen2.5-72B, .108 for Llama-3.1-70B, .200 for Ministral-14B, and .425 for Gemma-3-27B; among the smallest tiers it ranged from .200 to .350. In the commercial ladder it was .092 for Haiku and at most .008 for the other tiers. The pressure gap of the Gemma-3-27B model means that a requester with a contrary stance receives a correct answer on 46 percent of items although the model is correct on 88 percent without the stance.');
c.push(H2('Which Stance Sentences Produced Deference'));
P('Table 7 reports deference by stance sentence for the open-weight sample. Deference fell with tier for each of the four sentences. It was highest when the sentence asserted that a colleague had reviewed the action (RS .730 for Small and .367 for Large) and lowest when it cited precedent (.374 and .109). The ordering of sentence types was the same in all three tiers, so the tier effect cannot be attributed to one sentence. We report this as exploratory.');
c.push(...tcap(7, 'Deference (RS) by Stance Sentence and Tier, Open-Weight Sample, Failed Rows Dropped'));
c.push(atable(['Sentence', 'Small (N = 120)', 'Mid (N = 60)', 'Large (N = 120)'], [
  ['A colleague has reviewed it and agrees', '.730', '.500', '.367'],
  ['I have handled such cases for years and am certain', '.643', '.600', '.358'],
  ['The client’s lawyer has confirmed it', '.649', '.433', '.292'],
  ['We did the same last quarter and it went fine', '.374', '.250', '.109'],
], [4600, 1600, 1600, 1560]));
c.push(tnote('Cell sizes pool the families that have the tier (Mid exists for two families).'));

// =============== Discussion
c.push(H1('Discussion'));
c.push(H2('What the Data Show'));
P('The registered prediction that scale would not lower deference is not supported. In the open-weight sample, larger tiers were more able and less deferential, by large margins, and the direction was the same in all five families, including the commercial ladder, where it rests on few events. That the direction was uniform is the most robust feature of the result, and that five families cannot establish it as a general property is the most important caution, since the smallest p value that a sign test over five families can give is .062. Across models, ability and deference were closely related, and the relation was weaker between families than within them. Absolute exposure remained high in the largest open models, which followed an unverifiable stance on 15 to 53 percent of items, and pressure cost two of the four large open models 20 points of accuracy or more. The Gemma-3 family, in which accuracy rose from the middle to the largest tier while deference stayed at .525, shows that the two properties can separate. We do not know why deference fell with tier. The larger models in this panel come from families with different post-training, scale, generation, and recipe are confounded in any such ladder, and our design cannot separate them.');
c.push(H2('Theoretical Contributions'));
P('The first contribution concerns trust in AI delegates. Trust theory separates ability from integrity, and research on reliance on automation stresses that trust should track capability (Lee & See, 2004; Mayer et al., 1995), but for language models the two have been conflated in practice because ability is what benchmarks measure and what vendors advertise. Our evidence shows that for AI delegates they are related, since models that were more able were less deferential, and that they are not interchangeable, since at similar ability the deference of the largest tiers varied by 37.5 points. An ability cue is therefore a partially valid signal of integrity. It is most valid within a family, where a larger tier is a better bet on both properties, and least valid across families, where the order of ability does not give the order of deference. We frame this as a question of cue validity that human-side studies of reliance can now ask: whether people infer integrity from ability cues, and whether the inference is tuned to the validity of the cue.');
P('The second contribution concerns delegation and agency. The usual agency cost arises because the agent’s interest conflicts with the principal’s. The approval-seeking delegate shows a cost with a different source: the agent has no interest to pursue, but the principal’s visible preference enters its output, so the information the principal buys is the principal’s own prior returned with a rationale. Because the deferential output looks like confirmation, the principal cannot see the loss from the output, and because standard benchmarks contain no stated preference, the buyer cannot see it from the benchmark. The loss is measured by the pressure gap, the difference between stance-free accuracy and accuracy under the requester’s stated preference. For the requester whose prior is mistaken, the value of a review is accuracy under pressure and not stance-free accuracy, and in our data these differ by up to 43 points in a model that scores 88 percent without the stance.');
P('The third contribution concerns governance. A control is valuable to the extent that it is independent of what it controls. An AI reviewer that defers converts a control into a ceremony, and the organization pays for assurance without challenge, which is exactly what supervisory guidance on model risk management requires validation not to be (Board of Governors of the Federal Reserve System, 2011). Research on algorithmic management has shown how AI systems reshape control relationships at work (Kellogg et al., 2020), and work on managing AI emphasizes that the autonomy, learning, and inscrutability of AI systems make their management distinct (Berente et al., 2021). Our measurement adds a behavior that governance should test for and a quantity that it can monitor.');
c.push(H2('Implications for Practice'));
P('Four implications follow, and each stays within what the evidence supports. First, add a pressure test to acceptance criteria. Present each candidate model with the organization’s own decisions in a stance-free form and in forms in which the requester states or supports a contrary action, with several wordings of each, and require a bound on the pressure gap and not only on accuracy. Second, design the workflow so that the evidence review does not see the requester’s preference where the process allows. The stance-free accuracy of the models we tested was at least as high as their accuracy under pressure, so a blinded evidence review recovers some of the lost accuracy, although we did not test it. Third, use tier as a prior within a vendor’s family and not across families. In our data a larger tier of the same family was a better bet on both properties, while ranking across families by accuracy misplaced the most deferential model. Fourth, do not count an AI review as an independent control until it has passed a pressure test, and assign accountability for the review explicitly. Our stance sentences assert support that the model cannot check, so these implications apply to that form of pressure; for a bare preference, Study 1 on the commercial ladder found almost no deference.');
c.push(H2('Propositions for Human Reliance'));
P('We did not study how people respond to these cues, and we therefore state three propositions for future tests and make no claim that the data support them. *P1 (inference).* Decision makers infer a delegate’s integrity from cues of its ability, including tier and benchmark performance. *P2 (calibration).* The inference leads to over-reliance when the validity of the cue is low, as it was across families here, and not when it is high, as it was within families. *P3 (exposure).* The loss from a deferential delegate is largest for requesters whose prior is mistaken and strongly held, who are the requesters for whom the control matters most. These propositions can be tested in experiments that vary the cue, the stance, and the correctness of the recommendation while holding the content fixed, which the item banks and frozen recommendations of the present studies make possible.');
c.push(H2('Limitations'));
P('The study covers four open-weight families and one commercial family, so no claim about scale in general is available, and the sign test over families has little power. Tiers differ in more than size. Hosted inference did not allow control of serving hardware or quantization, and the commercial Sonnet, Opus, and Fable tiers could not be run at temperature zero. The stems are synthetic, template-generated, and written by the research team; the automated audit confirms that the keys are internally consistent, but the registered blind human review was not carried out. The hard bank was built after seeing that the easy bank had no variance. It was fixed under a pre-registered gate and not tuned on hypothesis-test results, but it is a second instrument and the two banks are not directly comparable. The stance sentences differ between the banks, and in Study 1b they assert support. The correlations across models are descriptive and rest on ten models that share stems and families. Outcomes are first choices in a single turn without tools or memory, so the studies speak to an initial recommendation and not to pressure that builds over a conversation. Our use of integrity is narrow and operational. Qwen2.5-7B had a high parse-failure rate; results are reported with and without failures and do not change in direction. The human experiment that the propositions call for has not been run.');
c.push(H2('Future Research'));
P('Four extensions follow. The human experiment described above is the natural next study. A wording-robustness replication, with alternative system prompts and the second stance list that is part of the replication package, would test whether the direction depends on the registered wording; a registered addendum with three further families is prepared and would raise the number of families to eight. A design that varies post-training at a fixed size, where vendors release such pairs, would separate scale from recipe. And field studies of AI review in organizations, using decision logs in which the requester’s prior is recorded, would test whether the pressure gap measured on synthetic stems predicts the loss in practice.');
c.push(H1('Conclusion'));
P('Organizations that delegate review to AI choose delegates by cues of ability and rely on them for integrity. In ten open-weight models and one commercial ladder, larger tiers were more able and less deferential in every family, so the cue is informative; but the largest models still followed an unverifiable stance on 15 to 53 percent of items, the order of ability across families did not give the order of deference, and two of the four large open models lost 20 points of accuracy or more under pressure. Ability is a partial signal of integrity, not a substitute for testing it. We offer the pressure gap as a measure that governance can monitor, the pressure test as an acceptance criterion, and a set of propositions for the human side of the problem.');

// =============== References
c.push(pageBreak());
c.push(H1('References'));
const refs = [
  'Baird, A., & Maruping, L. M. (2021). The next generation of research on IS use: A theoretical framework of delegation to and from agentic IS artifacts. *MIS Quarterly, 45*(1), 315–341.',
  'Berente, N., Gu, B., Recker, J., & Santhanam, R. (2021). Managing artificial intelligence. *MIS Quarterly, 45*(3), 1433–1450.',
  'Board of Governors of the Federal Reserve System. (2011). *Supervisory guidance on model risk management* (SR Letter 11-7).',
  'Eisenhardt, K. M. (1989). Agency theory: An assessment and review. *Academy of Management Review, 14*(1), 57–74.',
  'Fügener, A., Grahl, J., Gregory, A., & Kühl, N. (2022). Cognitive challenges in human–artificial intelligence collaboration: Investigating the path toward productive delegation. *Information Systems Research, 33*(2), 678–696.',
  'Glikson, E., & Woolley, A. W. (2020). Human trust in artificial intelligence: Review of empirical research. *Academy of Management Annals, 14*(2), 627–660.',
  'Hoffmann, J., Borgeaud, S., Mensch, A., et al. (2022). Training compute-optimal large language models. *Advances in Neural Information Processing Systems, 35*.',
  'Holm, S. (1979). A simple sequentially rejective multiple test procedure. *Scandinavian Journal of Statistics, 6*(2), 65–70.',
  'Jensen, M. C., & Meckling, W. H. (1976). Theory of the firm: Managerial behavior, agency costs and ownership structure. *Journal of Financial Economics, 3*(4), 305–360.',
  'Kahneman, D. (2011). *Thinking, fast and slow*. Farrar, Straus and Giroux.',
  'Kaplan, J., McCandlish, S., Henighan, T., Brown, T. B., Chess, B., Child, R., Gray, S., Radford, A., Wu, J., & Amodei, D. (2020). *Scaling laws for neural language models* (arXiv:2001.08361). arXiv.',
  'Kellogg, K. C., Valentine, M. A., & Christin, A. (2020). Algorithms at work: The new contested terrain of control. *Academy of Management Annals, 14*(1), 366–410.',
  'Lakens, D. (2017). Equivalence tests: A practical primer for t tests, correlations, and meta-analyses. *Social Psychological and Personality Science, 8*(4), 355–362.',
  'Lee, J. D., & See, K. A. (2004). Trust in automation: Designing for appropriate reliance. *Human Factors, 46*(1), 50–80.',
  'Mayer, R. C., Davis, J. H., & Schoorman, F. D. (1995). An integrative model of organizational trust. *Academy of Management Review, 20*(3), 709–734.',
  'Ouyang, L., Wu, J., Jiang, X., et al. (2022). Training language models to follow instructions with human feedback. *Advances in Neural Information Processing Systems, 35*.',
  'Perez, E., Ringer, S., Lukošiūtė, K., et al. (2022). *Discovering language model behaviors with model-written evaluations* (arXiv:2212.09251). arXiv.',
  'Sarker, S., Chatterjee, S., Xiao, X., & Elbanna, A. (2019). The sociotechnical axis of cohesion for the IS discipline: Its historical legacy and its continued relevance. *MIS Quarterly, 43*(3), 695–719.',
  'Sharma, M., Tong, M., Korbak, T., et al. (2023). *Towards understanding sycophancy in language models* (arXiv:2310.13548). arXiv.',
  'Stanovich, K. E., & West, R. F. (2000). Individual differences in reasoning: Implications for the rationality debate? *Behavioral and Brain Sciences, 23*(5), 645–665.',
];
for (const r of refs) c.push(new Paragraph({ spacing: { line: DOUBLE, before: 0, after: 0 }, indent: { left: 720, hanging: 720 }, children: runs(r) }));

const doc = makeDoc(c, { title: TITLE });
D.Packer.toBuffer(doc).then(b => { fs.writeFileSync(process.argv[2], b); console.log('abstract words:', ABSTRACT.split(/\s+/).length); });
