const fs=require('fs');
const {Document,Packer,Paragraph,TextRun,Table,TableRow,TableCell,WidthType,ShadingType,AlignmentType,HeadingLevel,BorderStyle,Footer,PageNumber,LineRuleType}=require('docx');
const F='Times New Roman';
const DBL={line:480,lineRule:LineRuleType.AUTO};
const SGL={line:240,lineRule:LineRuleType.AUTO};
// inline markup: *italic*  **bold**
function runs(t,o={}){const out=[];const re=/(\*\*[^*]+\*\*|\*[^*]+\*)/g;let last=0,m;
 while((m=re.exec(t))){if(m.index>last)out.push(new TextRun({text:t.slice(last,m.index),font:F,size:o.size||24,...o}));
  const s=m[0];if(s.startsWith('**'))out.push(new TextRun({text:s.slice(2,-2),bold:true,font:F,size:o.size||24,...o}));
  else out.push(new TextRun({text:s.slice(1,-1),italics:true,font:F,size:o.size||24,...o}));last=m.index+s.length;}
 if(last<t.length)out.push(new TextRun({text:t.slice(last),font:F,size:o.size||24,...o}));return out;}
const P=(t)=>new Paragraph({children:runs(t),spacing:{...DBL,after:0},indent:{firstLine:720},alignment:AlignmentType.LEFT});
const H1=(t)=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:t,bold:true,font:F,size:24,allCaps:true})],spacing:{before:360,after:120,...SGL},keepNext:true});
const H2=(t)=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun({text:t,bold:true,font:F,size:24})],spacing:{before:240,after:120,...SGL},keepNext:true});
const H3=(t)=>new Paragraph({heading:HeadingLevel.HEADING_3,children:[new TextRun({text:t,bold:true,italics:true,font:F,size:24})],spacing:{before:200,after:100,...SGL},keepNext:true});
const EQ=(t,n)=>new Paragraph({children:[new TextRun({text:t,italics:true,font:F,size:24}),new TextRun({text:'\t('+n+')',font:F,size:24})],tabStops:[{type:'right',position:9360}],spacing:{before:120,after:120,...SGL},alignment:AlignmentType.CENTER});
const CAP=(t)=>new Paragraph({children:runs(t,{size:22}),spacing:{before:240,after:80,...SGL},keepNext:true,alignment:AlignmentType.CENTER});
const NOTE=(t)=>new Paragraph({children:runs(t,{size:20}),spacing:{before:60,after:200,...SGL}});
const C=(t)=>new Paragraph({children:[new TextRun({text:'',font:F})],spacing:SGL});
const bd={style:BorderStyle.SINGLE,size:4,color:'000000'},nb={style:BorderStyle.NONE,size:0,color:'FFFFFF'};
function TBL(widths,rows,hdr=true){const tot=widths.reduce((a,b)=>a+b,0);
 return new Table({width:{size:tot,type:WidthType.DXA},columnWidths:widths,rows:rows.map((r,i)=>new TableRow({tableHeader:i===0&&hdr,cantSplit:true,children:r.map((c,j)=>new TableCell({width:{size:widths[j],type:WidthType.DXA},
  borders:{top:i===0?bd:nb,bottom:(i===0||i===rows.length-1)?bd:nb,left:nb,right:nb},margins:{top:50,bottom:50,left:90,right:90},
  shading:i===0?{fill:'EDEDED',type:ShadingType.CLEAR,color:'auto'}:undefined,
  children:[new Paragraph({children:runs(c,{size:20,bold:i===0}),spacing:SGL})]}))}))});}
const REF=(t)=>new Paragraph({children:runs(t),spacing:{...SGL,after:120},indent:{left:720,hanging:720}});
const TODO='[TO BE COMPLETED AFTER ESTIMATION]';

const body=[];
const add=(...x)=>body.push(...x);

add(new Paragraph({children:[new TextRun({text:'Generative Visual AI and the Demand for Creative Labor: A Task-Based Model and Exploratory Evidence',bold:true,font:F,size:32})],alignment:AlignmentType.CENTER,spacing:{before:1200,after:240,...SGL}}),
 new Paragraph({children:[new TextRun({text:'Manuscript prepared in the format of Information Systems Research',font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:120,...SGL}}),
 new Paragraph({children:[new TextRun({text:'[Author names and affiliations removed for double-blind review]',font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:480,...SGL}}),
 new Paragraph({children:[new TextRun({text:'Status of this draft. ',bold:true,font:F,size:22}),new TextRun({text:'This is a working-paper draft, not a submission-ready empirical paper. It contains a task-based model, a measurement design, and exploratory evidence from three open data sources: UK online job adverts by occupation, US postings by sector, and European employment by industry. Firm-level data and licensed posting data (for example Lightcast) were not available. The evidence is exploratory and mixed, and it does not identify an effect of generative visual AI. The O*NET-based classification of visual-content-creation tasks is not validated (Section 4.3), and no result in this draft depends on it. Model release dates and bibliographic details marked † must be verified before circulation.',font:F,size:22})],spacing:{...SGL},shading:{fill:'F5F5F5',type:ShadingType.CLEAR,color:'auto'}}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(new Paragraph({children:[new TextRun({text:'Abstract',bold:true,font:F,size:24})],alignment:AlignmentType.CENTER,spacing:{after:120,...SGL}}),
 new Paragraph({children:runs('Generative AI that creates images and video makes visual content nearly free to produce, but whether it displaces creative workers depends on whether its output is good enough and on how much extra content cheaper production induces. We model each visual asset as a choice between human production and AI production with human review: substitution requires an acceptance rate above a threshold set by review cost relative to human cost, while cheaper assets raise demand for direction and curation. Using UK online job adverts by occupation (2017–2026), US postings by sector, and European employment by industry, we find that adverts for image-production occupations fell 0.2 to 0.4 log points more than for other occupations after mid-2022, concentrated in web and graphic design. Creative-direction roles fell less, European creative-industry employment did not decline, and placebo design occupations also fell, so we do not attribute the decline to generative AI.'),spacing:{...SGL,after:200},alignment:AlignmentType.JUSTIFIED}),
 new Paragraph({children:[new TextRun({text:'Keywords: ',bold:true,font:F,size:24}),new TextRun({text:'generative AI; image generation; video generation; creative labor; task-based model; automation; online job postings; technology diffusion; complementary assets',font:F,size:24})],spacing:{...SGL,after:120}}),
 new Paragraph({children:[new TextRun({text:'History: ',bold:true,font:F,size:24}),new TextRun({text:'[to be completed by the journal].',font:F,size:24})],spacing:SGL}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(H1('1. Introduction'),
P('Until recently, producing a new image, illustration, photograph, or piece of video required skilled labor. Generative AI systems that create images from text prompts, released from 2022, and systems that create video, released from 2024, make a first draft of such content almost costless. This raises an obvious question for research on AI and work: do these systems displace the people who produce visual content, or do they change what those people do?'),
P('Existing evidence on AI and labor is dominated by exposure measures, which describe the technical overlap between AI capabilities and tasks (Webb 2020; Felten et al. 2021; Eloundou et al. 2023), and by studies of vacancies that infer effects from AI-related skill demand (Acemoglu et al. 2022). Exposure alone cannot answer our question, for two reasons. First, a generated image is useful only if it is good enough for its purpose: brand-critical, legal, or distinctive work may still need a human, while stock imagery and routine graphics may not. Second, cheaper content can raise the quantity demanded, which creates work for people who direct, select, edit, and integrate content even as it removes work from those who produce each asset by hand.'),
P('We make three contributions. First, we propose a task-level model in which substitution is governed by an acceptance-rate threshold rather than by a task-volume threshold, and in which the net effect on creative labor combines a substitution effect and a scale effect. This differs from fixed-cost models of AI adoption, in which a high cost of building a bespoke system is spread over task volume. For generative visual AI the fixed and marginal costs of producing an asset are both small, so the binding constraint is quality. Second, we design a measurement approach based on O*NET task statements that classifies tasks by whether they involve producing or editing visual content. Third, we bring together three open data sources, UK online job adverts by occupation, US postings by sector, and European employment by industry, and report what they do and do not show.'),
P('We are explicit about what the evidence supports. In UK adverts by occupation, image-production occupations fell more than other occupations from mid-2022 onward, and creative-direction roles fell less. But the decline is concentrated in web and graphic design, design occupations that image generators do not target also fell, and image-production occupations were already declining relative to others in the COVID period. In US sector postings, creative sectors fell no more than technology sectors. In European employment, creative industries did not decline. None of the sources separates image-generation effects from concurrent macroeconomic and text-generation effects. We therefore treat the empirical section as exploratory.'),
P('The remainder of the paper is organized as follows. Section 2 reviews related work. Section 3 presents the model and hypotheses. Section 4 describes the data and measures. Section 5 sets out the empirical strategy. Section 6 reports results. Section 7 discusses contributions, implications, and limitations.'));

add(H1('2. Related Literature'),
H2('2.1 AI Exposure and Labor Demand'),
P('A large literature measures how closely AI capabilities map onto occupational tasks. Webb (2020)† links patent text to task descriptions, Felten et al. (2021) link AI application progress to workplace abilities, and Eloundou et al. (2023) assess the exposure of occupations to large language models. Acemoglu et al. (2022) use online vacancies to show that establishments with more AI-exposed task content reduce hiring for other positions. These studies describe where AI could matter or infer effects from skill demand. We study a specific class of tasks, producing visual content, and ask how output quality and induced demand determine the net effect.'),
H2('2.2 The Economics of Cheaper Prediction and Cheaper Content'),
P('Agrawal et al. (2018) frame AI as a fall in the cost of prediction that raises the value of complements such as judgment. Generative AI lowers the cost of producing a draft, which resembles a fall in the price of an input. The standard implication, that a cheaper input raises demand for its complements and expands output, motivates our scale and complement predictions. We do not review the growing empirical literature on generative AI and creative or freelance work in detail here; positioning against recent work in Information Systems Research, MIS Quarterly, and Management Science is to be completed.'));

add(H1('3. Theory and Hypotheses'),
H2('3.1 A Task-Level Model of Visual Asset Production'),
P('A firm needs *Q* visual assets per period, such as images, layouts, short videos, or edited photographs. Producing an asset with human labor costs *θ*. Producing it with generative AI costs *c* for generation plus *r* for human review. With probability *a*, the output is accepted. With probability 1 − *a* it fails the quality requirement and the human must produce the asset, at cost *θ*. The expected cost of the AI route is *c* + *r* + (1 − *a*)*θ*, so the firm substitutes AI for human production of the asset when this falls below *θ*, that is, when the acceptance rate exceeds a threshold:'),
EQ('a > a* = ( c + r ) / θ',1),
P('Equation (1) has three implications. First, the threshold falls as human cost *θ* rises, so substitution is more likely for expensive assets such as video than for cheap ones such as simple graphics. Second, the acceptance rate *a* depends on the task’s quality requirement, which varies across assets: stock imagery and routine social-media graphics have low requirements, while brand-defining or legally sensitive work has high requirements. Third, because *c* and the fixed cost of access are small, the volume of assets plays little role in the decision, unlike in fixed-cost models of bespoke AI systems.'),
P('Cheaper assets also raise the quantity demanded. If the effective unit cost of an asset falls, the firm commissions more assets (a scale effect), and the extra assets need direction, selection, editing, and integration. Human labor in a creative sector therefore changes by a substitution effect, which is negative where *a* > *a**, plus a scale effect, which is positive and raises demand for complementary roles. The net effect on employment in a sector is ambiguous, and it can differ between hiring (the flow of postings) and the stock of employment.'),
H2('3.2 Hypotheses'),
CAP('**Table 1.** Hypotheses and observable predictions'),
TBL([900,4000,4460],[
 ['','Hypothesis','Prediction in available or future data'],
 ['H1','Substitution: after image-generation releases, hiring falls in activities dominated by visual content production.','Postings in creative sectors fall relative to comparable sectors after 2022.'],
 ['H2','Quality threshold: declines are concentrated in tasks with low acceptance thresholds.','Occupation-level adverts fall more for production roles than for creative-direction roles (testable with UK occupation data); within production, they fall most for stock imagery and routine graphics (not testable with current data).'],
 ['H3','Scale and complements: employment in creative industries need not fall, and demand for direction and curation rises.','Industry employment is flat or rising; the share of postings requiring direction, curation, and integration skills rises. Only the first part is testable with current data.'],
 ['H4','Staging: effects appear in steps at image-generation (2022) and video-generation (2024) releases.','Gap between creative and other occupations widens after each release, with video roles responding to video releases. Partly testable with UK occupation data.']]),
C());

add(H1('4. Data and Measures'),
H2('4.1 Sources'),
P('*UK online job adverts by occupation.* We use the Office for National Statistics (ONS) experimental series Labour Demand Volumes by Standard Occupational Classification (SOC 2020), built from Textkernel data. It reports the number of new online job adverts in the United Kingdom each month from January 2017 to August 2026 for 413 four-digit SOC unit groups. The ONS assigns each advert to an occupation by matching its job title to a taxonomy. The series is experimental. Several months have suppressed or missing cells (all occupations for March 2026; many occupations for June and July 2025 and June 2026), which we fill by linear interpolation for up to two consecutive months. The data are released under the Open Government Licence.'),
P('*US job postings by sector.* We use the Indeed Hiring Lab Job Postings Index, which reports the seasonally adjusted number of total postings on Indeed in the United States relative to February 1, 2020 (index = 100), daily, for 47 occupational sectors from February 2020 to September 2026. Sectors are an Indeed categorization based on normalized job titles. The sector Arts & Entertainment is illustrated by job titles such as designer and artist, Media & Communications by photographer and writer, and Marketing by marketing manager and digital marketer. We aggregate to monthly means of the log index. The data are released under a Creative Commons Attribution 4.0 license.'),
P('*European employment by industry.* We use the Eurostat Labour Force Survey series on employed persons by detailed economic activity (NACE Rev. 2, two-digit level), annual, for the EU27 from 2015 to 2025. Creative activities are NACE J59 (motion picture, video and television programme production, sound recording and music publishing), M73 (advertising and market research), and M74 (other professional, scientific and technical activities, which includes specialized design and photographic activities). We use the 88 two-digit activities with complete data.'),
H2('4.2 Treatment and Comparison Definitions'),
P('We fix the treated groups before looking at outcomes. In the US data, the treated sectors are Arts & Entertainment, Media & Communications, and Marketing. This definition is coarse. Arts & Entertainment is the closest to visual content production, whereas Media & Communications and Marketing also contain text-producing roles that are exposed to text-generation AI. In the Eurostat data, the treated activities are J59, M73, and M74, which also mix creative and non-creative work. For both sources we compare treated groups with all other sectors and with a restricted set. In the US data, the restricted set excludes the four information-technology and data sectors (software development, IT infrastructure, IT systems, data and analytics), whose postings fell sharply for reasons unrelated to image generation. In the Eurostat data, it is the knowledge-service activities (NACE J, K, L68, M, N).'),
P('In the UK data we fix three occupational groups from occupation labels alone, before looking at outcomes. *Image and video production* comprises graphic and multimedia designers (SOC 2142), artists (3411), photographers and audio-visual and broadcasting equipment operators (3417), and web design professionals (2141). *Creative direction and production* comprises arts officers, producers and directors (3416), advertising accounts managers and creative directors (2494), and managers and directors in the creative industries (1255). *Text production* comprises authors, writers and translators (3412), journalists and reporters (2492), and editors (2491). The comparison pool is all other occupations with at least 1,000 new adverts in the base year (395 occupations), and a restricted pool of managerial, professional, and associate-professional occupations (SOC major groups 1 to 3; 249 occupations). As a placebo we use design occupations that image generators do not target: interior designers (3421), clothing, fashion and accessories designers (3422), and design occupations not elsewhere classified (3429).'),
H2('4.3 Task-Based Measure of Visual Content Creation'),
P('To measure occupational exposure to visual content production we classify O*NET task statements (version 29.1, 18,796 statements) with a large language model. Each task is scored 0, 1, or 2: 2 if producing or editing visual content (graphics, illustrations, photographs, video, animation, layouts) is central, 1 if visual content is a partial or supporting product, and 0 otherwise. The rubric excludes looking at or inspecting things, writing, and audio production. In a pilot on a random sample of 400 task statements, 15 (3.8%) scored 1 and 8 (2.0%) scored 2, so visual content production is a small share of all tasks. Occupation-level exposure would be the share of an occupation’s tasks scoring 1 or 2, weighted by task importance.'),
P('This measure has not yet been validated. A full-sample classification is in progress. Validation requires human coding of a stratified sample (tasks scored 1 or 2 plus a sample of tasks scored 0, because a simple random sample would contain almost no positive tasks) and a report of agreement. An earlier attempt to measure a broader construct, dependence of tasks on visual perception, showed weak agreement between a language model and a human coder (Cohen’s κ about 0.2 on 200 tasks) and was discontinued. The creation construct is narrower and more concrete, but we do not assume that it will agree better. No result in Section 6 uses this measure. The treated occupational groups in the UK data are instead chosen from occupation labels.'));

add(H1('5. Empirical Strategy'),
H2('5.1 US Sector Event Study'),
P('Let *L_{s,m}* be the log of the monthly mean postings index for sector *s* in month *m*. We use the window January–March 2022 as the base, because it precedes the public release of text-to-image systems in 2022 and of ChatGPT in November 2022. For each of four later windows (October 2022–March 2023, October 2023–March 2024, October 2024–March 2025, and October 2025–March 2026) we compute the change in *L* from the base for each sector, and the difference between the mean change of the three treated sectors and the mean change of the comparison sectors. The windows correspond to: after image-generation releases and ChatGPT, after the release of a further generation of image generators, after the release of video-generation systems, and a later follow-up. Release dates are to be verified.'),
P('Because only three sectors are treated, conventional standard errors would be unreliable. We use randomization inference: the p-value is the share of all possible sets of three sectors among the 47 (16,215 sets) that produce a difference at least as large in absolute value as the observed one. We assess pre-trends with the same statistic for January–March 2021 to January–March 2022.'),
H2('5.2 European Industry Employment'),
P('For each activity we compute the change in the log of EU27 employment between the mean of 2019–2021 and the mean of 2023–2025, and a pre-trend statistic between 2015–2017 and 2019–2021. We compare the mean change of the three treated activities with that of the others, with randomization inference over all sets of three activities in the comparison pool (88 activities in the full pool, 23 in the restricted pool).'));

add(H2('5.3 UK Occupation-Level Event Study'),
P('For each occupation we compute the sum of new adverts over each twelve-month window from July to June, and take logs. The base year is July 2021 to June 2022, which precedes the public release of text-to-image systems (July to August 2022) and of ChatGPT (November 2022). For each later year we compute the log change from the base year for each occupation, and the difference between the mean log change of the occupations in a group and that of the comparison pool. Using annual sums removes seasonality. Inference is by randomization: the p-value is the share of 10,000 random sets of occupations of the same size drawn from the comparison pool that produce a difference at least as large in absolute value. We report leave-one-occupation-out estimates, individual occupations with their rank among all occupations, and the placebo group. Because the series starts in 2017, the pre-period contains the COVID shock, so we cannot use it to test parallel trends cleanly; we report the path of the group gap from 2019 as descriptive evidence.'),
H1('6. Results'),
H2('6.1 UK Occupation-Level Evidence'),
P('Table 2 reports the main result. Relative to other occupations, adverts for image and video production occupations fell by 0.20 log points in the first year after the base year (July 2022 to June 2023; randomization p = 0.032) and by 0.38 log points in the third and fourth years (p = 0.011), when all other occupations are the comparison. The estimates are similar when the comparison is limited to managerial, professional, and associate-professional occupations (−0.22 to −0.39; p between 0.007 and 0.044). Creative direction and production occupations fell by less (−0.11 in the first year and −0.23 in the third; p between 0.15 and 0.27). The difference between image and video production and creative direction is about −0.15 log points in the third year, which has the sign predicted by the quality-threshold hypothesis, but the direction group has only three occupations. Text production occupations did not differ from other occupations in the first two years (−0.10 and +0.03) and fell later (−0.33 in the third year, p = 0.046; −0.47 in the fourth, p = 0.008), led by journalists and editors.'),
CAP('**Table 2.** UK occupations: change in log new adverts (twelve-month sums) from July 2021–June 2022, group minus other occupations'),
TBL([2660,1675,1675,1675,1675],[
 ['Group (comparison pool)','Jul22–Jun23','Jul23–Jun24','Jul24–Jun25','Jul25–Jun26'],
 ['Image and video production (all)','−0.196 (0.032)','−0.262 (0.047)','−0.378 (0.011)','−0.384 (0.011)'],
 ['Image and video production (SOC 1–3)','−0.217 (0.016)','−0.294 (0.044)','−0.381 (0.008)','−0.389 (0.007)'],
 ['Creative direction (all)','−0.113 (0.225)','−0.159 (0.268)','−0.230 (0.168)','−0.210 (0.224)'],
 ['Creative direction (SOC 1–3)','−0.134 (0.149)','−0.191 (0.211)','−0.233 (0.159)','−0.216 (0.179)'],
 ['Text production (all)','−0.098 (0.279)','+0.029 (0.839)','−0.333 (0.046)','−0.473 (0.008)'],
 ['Text production (SOC 1–3)','−0.119 (0.201)','−0.003 (0.982)','−0.336 (0.049)','−0.478 (0.005)']]),
NOTE('*Note.* Entries are the mean log change of the group minus that of the comparison pool, with randomization p-values in parentheses. Comparison pools: all other occupations with at least 1,000 new adverts in the base year (395), and the subset in SOC major groups 1 to 3 (249). Months with missing cells are interpolated (see text). The last column includes the imputed month of March 2026.'),
P('Four checks limit the interpretation. First, the decline in image and video production is concentrated in some occupations. Web design professionals fell most, ranking first or third among 405 occupations in the later years (log changes of −1.45 and −1.36 against a comparison median of −0.43 and −0.46), and graphic and multimedia designers ranked 32nd to 38th (−0.86 and −0.89). Artists and photographers were close to the median. When web design professionals are dropped, the third- and fourth-year differences fall to −0.16 and −0.21. Second, the placebo design occupations also fell relative to others (−0.16, −0.20, and −0.06 in the first, third, and fourth years), so the fall in design hiring is not specific to occupations that image generators target. Third, the pre-period is contaminated by COVID: image and video production fell by 0.32 log points relative to other occupations between June 2019 and June 2021 (the creative direction and text groups fell by 0.36 and 0.31), so these groups were already losing ground before generative AI. Fourth, the timing does not show steps at release dates; the gap widens gradually, and the decline of text production occurs later than that of image production, which is the opposite of the order in which the public text and image tools appeared.'),
H2('6.2 US Postings'),
P('Table 3 reports the difference in log change between creative and other sectors. Creative sectors fell relative to other sectors in every window after the base. The difference is −0.23 log points in October 2022–March 2023 (randomization p = 0.018) and about −0.31 to −0.33 in later windows (p between 0.049 and 0.077) when all other sectors are the comparison. When the technology and data sectors are excluded from the comparison, the differences are larger and the p-values smaller (−0.26 to −0.39, p between 0.003 and 0.011). The difference between the third and second windows is close to zero (−0.316 versus −0.328 for all other sectors), so there is no additional widening after the release of video-generation systems.'),
CAP('**Table 3.** US sectors: change in log postings index from January–March 2022, creative sectors minus other sectors'),
TBL([3860,2750,2750],[
 ['Window','All other sectors (randomization p)','Excluding IT and data sectors (randomization p)'],
 ['Oct 2022–Mar 2023','−0.232 (0.018)','−0.262 (0.003)'],
 ['Oct 2023–Mar 2024','−0.328 (0.049)','−0.386 (0.004)'],
 ['Oct 2024–Mar 2025','−0.316 (0.063)','−0.373 (0.007)'],
 ['Oct 2025–Mar 2026','−0.305 (0.077)','−0.362 (0.011)']]),
NOTE('*Note.* Treated sectors: Arts & Entertainment, Media & Communications, Marketing. Entries are the mean change in log postings of treated sectors minus the mean change of comparison sectors. Randomization p-values are over all 16,215 possible sets of three sectors among 47. Pre-trend (January–March 2021 to January–March 2022): +0.109, p = 0.248.'),
P('Three features limit the interpretation. First, creative sectors were not on a flat pre-trend: they rose by 0.109 log points more than other sectors between the first quarter of 2021 and the first quarter of 2022 (p = 0.248), so part of the later decline may be mean reversion after a faster post-pandemic recovery. Second, creative sectors were not the largest decliners. Between the base and October 2024–March 2025, the log change was −0.829 for Marketing (rank 5 of 47, where 1 is the largest fall), −0.821 for Media & Communications (rank 6), and −0.535 for Arts & Entertainment (rank 15), against a sector median of −0.361. Software Development fell by 1.220 (rank 1) and Data & Analytics by 1.066 (rank 2). The drop in creative postings is therefore of similar size to that of technology sectors over the same period, which points to a broad knowledge-work hiring slowdown rather than something specific to visual generation. Third, the sector closest to visual content production, Arts & Entertainment, fell by less than the other two creative sectors, which include text-producing roles. This ordering does not support a visual-generation story over a text-generation story.'),
H2('6.3 European Industry Employment'),
P('European creative-industry employment did not fall. Between 2019–2021 and 2023–2025, the log change in employment was +0.130 for J59, +0.106 for M73, and +0.148 for M74, compared with a median of +0.038 across 88 activities. Relative to all other activities the treated activities gained 0.086 log points (randomization p = 0.202), and relative to knowledge-service activities they gained 0.038 (p = 0.518). Pre-trends were close to zero (+0.028 and −0.011). Employment in J59 rose from about 417 thousand in 2019 to 495 thousand in 2025, in M73 from 890 to 1,015 thousand, and in M74 from 1,205 to 1,324 thousand. None of these differences is distinguishable from zero. The treated activities are broad, the Labour Force Survey counts the self-employed, and employment is a stock, so these figures need not conflict with a fall in postings.'),
CAP('**Table 4.** EU27 industries: change in log employment, 2019–2021 to 2023–2025'),
TBL([3860,2750,2750],[
 ['Statistic','All 88 activities','Knowledge-service activities (23)'],
 ['Creative minus others, change','+0.086 (p = 0.202)','+0.038 (p = 0.518)'],
 ['Creative minus others, pre-trend','+0.028 (p = 0.531)','−0.011 (p = 0.845)'],
 ['J59, M73, M74 individual changes','+0.130, +0.106, +0.148','median of all activities: +0.038']]),
NOTE('*Note.* Treated activities: NACE J59, M73, M74. Randomization p-values are over all sets of three activities in the comparison pool.'),
H2('6.4 What the Evidence Does and Does Not Show'),
P('For H1, UK adverts by occupation are directionally consistent with substitution in image and video production, and US sector postings and UK placebo design occupations show that the decline is not specific to visual generation. European employment shows no decline. For H2, the contrast between production and creative-direction occupations has the predicted sign but is not statistically distinguishable from zero and rests on three direction occupations. For H3, European employment is compatible with a scale effect, but the test is weak because activities are broad. For H4, no step appears at video-generation releases in any source, and the later decline of text production than of image production does not fit a simple release-order story. Overall, the evidence is consistent with a relative decline in hiring for image and video production work, concentrated in web and graphic design, but it does not identify an effect of generative AI, because design occupations unrelated to image generation also declined and the pre-period already shows relative decline. The binding limitation is the identification, not the sign of any estimate.'),
H2('6.5 Pre-Specified Tests for Richer Data'),
P('With posting data that include occupations, tasks, and employers (for example, licensed data with skills and firm identifiers), the model implies the following tests, which we pre-specify here. Occupations with a high share of tasks scoring 2 on the visual content creation measure should show a larger fall in postings after each release than comparable occupations with low scores (H1), and the fall should be larger within the group where acceptance thresholds are likely to be low, such as stock imagery and routine graphics (H2). The share of postings requiring direction, curation, and integration skills should rise in creative occupations (H3). Differences should widen after video-generation releases for video-related occupations (H4). Comparison groups should have similar exposure to text-generation tools but low visual content production, so that the visual channel can be separated from the text channel.'));

add(H1('7. Discussion'),
H2('7.1 Contributions'),
P('The paper offers a task-level model of generative visual AI in which the acceptance rate relative to a review-cost threshold, rather than task volume, governs substitution, and in which a scale effect can offset or exceed substitution in sector employment. It proposes a measure of visual content creation based on O*NET tasks and a design for occupation-level tests. It also reports exploratory evidence from three open data sources. The evidence shows a relative decline in hiring for image and video production occupations in the UK, but it identifies no effect of generative visual AI on creative labor.'),
H2('7.2 Implications'),
P('For managers and policy makers, the model implies that the relevant question about creative labor is not whether AI can generate an image, but for which tasks the output meets the quality requirement at the cost of review. It also implies that the effect on a creative sector’s hiring and the effect on its employment can differ, so single indicators can mislead. Information systems research on platforms for creative work could use the model to ask how quality verification and review shape substitution on those platforms.'),
H2('7.3 Limitations'),
P('The UK data are by occupation but not by firm or task, are experimental, and have missing months that we interpolate. US postings are by sector, which mixes visual and text-producing roles, and European employment is by broad industry. The treated groups are chosen a priori from labels and are coarse: there are four production, three direction, and three text occupations in the UK data, and three treated units in each of the other sources, so inference relies on randomization over occupation or sector sets. Concurrent shocks, including the post-pandemic recovery, higher interest rates, a slowdown in technology hiring, and text-generation tools, cannot be separated from image generation. Postings measure hiring intent and not employment, and the Labour Force Survey includes the self-employed, who may respond differently. Model release dates are approximate and must be verified. The visual content creation measure is not yet validated against human coders. The pre-period contains the COVID shock, so parallel trends cannot be tested cleanly. The theoretical model is a stylized single-asset model and abstracts from changes in the quality and variety of assets.'),
H1('8. Conclusion'),
P('Generative AI makes visual content cheap to produce, but the effect on creative labor depends on whether output is good enough and on whether cheaper content creates enough extra demand. In open data we find that UK adverts for image and video production occupations fell relative to other occupations after mid-2022, concentrated in web and graphic design, that US creative-sector postings fell by about as much as technology-sector postings, and that European creative-industry employment did not fall. Because design occupations that image generators do not target also declined and the production occupations were already declining before 2022, we cannot attribute the decline to generative visual AI. Testing the model’s distinct predictions requires firm-level data and a validated task measure, which we specify.'));

add(new Paragraph({children:[],pageBreakBefore:true}),H1('References'),
REF('Acemoglu, D., Autor, D., Hazell, J., and Restrepo, P. 2022. Artificial intelligence and jobs: Evidence from online vacancies. *Journal of Labor Economics* 40(S1):S293–S340.†'),
REF('Agrawal, A., Gans, J., and Goldfarb, A. 2018. *Prediction Machines: The Simple Economics of Artificial Intelligence*. Boston: Harvard Business Review Press.†'),
REF('Eloundou, T., Manning, S., Mishkin, P., and Rock, D. 2023. GPTs are GPTs: An early look at the labor market impact potential of large language models. arXiv:2303.10130.†'),
REF('Eurostat. Labour Force Survey, employed persons by detailed economic activity (NACE Rev. 2 two-digit level), dataset lfsa_egan22d. Accessed via the Eurostat dissemination API.'),
REF('Felten, E., Raj, M., and Seamans, R. 2021. Occupational, industry, and geographic exposure to artificial intelligence. *Strategic Management Journal* 42(12):2195–2217.†'),
REF('Indeed Hiring Lab. Job Postings Index, by sector, United States (data repository hiring-lab/job_postings_tracker). Creative Commons Attribution 4.0 International License.'),
REF('National Center for O*NET Development. O*NET Database, version 29.1 (Task Statements; Abilities). Creative Commons Attribution 4.0 International License.'),
REF('Office for National Statistics. Labour demand volumes by Standard Occupation Classification (SOC 2020), UK: January 2017 to August 2026 (experimental statistics based on Textkernel data). Open Government Licence.'),
REF('Webb, M. 2020. The impact of artificial intelligence on the labor market. Working paper, Stanford University.†'),
new Paragraph({children:runs('† Details taken from the earlier research proposal without independent verification; to be checked before circulation.',{size:20}),spacing:{...SGL,before:200}}));

const doc=new Document({
 styles:{default:{document:{run:{font:F,size:24}}},paragraphStyles:[
  {id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:0}},
  {id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:1}},
  {id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,italics:true,font:F},paragraph:{outlineLevel:2}}]},
 sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,bottom:1440,left:1440,right:1440}}},
  footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],font:F,size:20})]})]})},
  children:body}]});
Packer.toBuffer(doc).then(b=>fs.writeFileSync('ISR_Paper_Generative_Visual_AI_Creative_Labor.docx',b));
