const fs=require('fs');
const {Document,Packer,Paragraph,TextRun,ImageRun,Table,TableRow,TableCell,WidthType,ShadingType,AlignmentType,HeadingLevel,BorderStyle,Footer,PageNumber,LineRuleType}=require('docx');
const F='Times New Roman';
const DBL={line:480,lineRule:LineRuleType.AUTO};
const SGL={line:240,lineRule:LineRuleType.AUTO};
// inline markup: *italic*  **bold**
function runs(t,o={}){const out=[];const re=/(\*\*[^*]+\*\*|\*[^*]+\*)/g;let last=0,m;
 while((m=re.exec(t))){if(m.index>last)out.push(new TextRun({text:t.slice(last,m.index),font:F,size:o.size||24,...o}));
  const s=m[0];if(s.startsWith('**'))out.push(new TextRun({text:s.slice(2,-2),bold:true,font:F,size:o.size||24,...o}));
  else out.push(new TextRun({text:s.slice(1,-1),italics:true,font:F,size:o.size||24,...o}));last=m.index+s.length;}
 if(last<t.length)out.push(new TextRun({text:t.slice(last),font:F,size:o.size||24,...o}));return out;}
const P=(t)=>new Paragraph({children:runs(t),spacing:{...DBL,after:0},indent:{firstLine:720},alignment:AlignmentType.LEFT});
const H1=(t)=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:t,bold:true,font:F,size:24,allCaps:true})],spacing:{before:360,after:120,...SGL},keepNext:true});
const H2=(t)=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun({text:t,bold:true,font:F,size:24})],spacing:{before:240,after:120,...SGL},keepNext:true});
const H3=(t)=>new Paragraph({heading:HeadingLevel.HEADING_3,children:[new TextRun({text:t,bold:true,italics:true,font:F,size:24})],spacing:{before:200,after:100,...SGL},keepNext:true});
const EQ=(t,n)=>new Paragraph({children:[new TextRun({text:t,italics:true,font:F,size:24}),new TextRun({text:'\t('+n+')',font:F,size:24})],tabStops:[{type:'right',position:9360}],spacing:{before:120,after:120,...SGL},alignment:AlignmentType.CENTER});
const CAP=(t)=>new Paragraph({children:runs(t,{size:22}),spacing:{before:240,after:80,...SGL},keepNext:true,alignment:AlignmentType.CENTER});
const NOTE=(t)=>new Paragraph({children:runs(t,{size:20}),spacing:{before:60,after:200,...SGL}});
const C=(t)=>new Paragraph({children:[new TextRun({text:'',font:F})],spacing:SGL});
const bd={style:BorderStyle.SINGLE,size:4,color:'000000'},nb={style:BorderStyle.NONE,size:0,color:'FFFFFF'};
function TBL(widths,rows,hdr=true){const tot=widths.reduce((a,b)=>a+b,0);
 return new Table({width:{size:tot,type:WidthType.DXA},columnWidths:widths,rows:rows.map((r,i)=>new TableRow({tableHeader:i===0&&hdr,cantSplit:true,children:r.map((c,j)=>new TableCell({width:{size:widths[j],type:WidthType.DXA},
  borders:{top:i===0?bd:nb,bottom:(i===0||i===rows.length-1)?bd:nb,left:nb,right:nb},margins:{top:50,bottom:50,left:90,right:90},
  shading:i===0?{fill:'EDEDED',type:ShadingType.CLEAR,color:'auto'}:undefined,
  children:[new Paragraph({children:runs(c,{size:20,bold:i===0}),spacing:SGL})]}))}))});}
const REF=(t)=>new Paragraph({children:runs(t),spacing:{...SGL,after:120},indent:{left:720,hanging:720}});
const TODO='[TO BE COMPLETED AFTER ESTIMATION]';

const IMG=(p,w,h)=>new Paragraph({children:[new ImageRun({type:'png',data:fs.readFileSync(p),transformation:{width:w,height:h}})],alignment:AlignmentType.CENTER,spacing:{before:120,after:60,...SGL},keepNext:true});
const body=[];
const add=(...x)=>body.push(...x);

add(new Paragraph({children:[new TextRun({text:'Early Adoption, Delayed Displacement? Generative Visual AI and Creative Work',bold:true,font:F,size:32})],alignment:AlignmentType.CENTER,spacing:{before:1200,after:240,...SGL}}),
 new Paragraph({children:[new TextRun({text:'Manuscript prepared in the format of Information Systems Research',font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:120,...SGL}}),
 new Paragraph({children:[new TextRun({text:'[Author names and affiliations removed for double-blind review]',font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:480,...SGL}}),
 new Paragraph({children:[new TextRun({text:'Status of this draft. ',bold:true,font:F,size:22}),new TextRun({text:'This draft reports a full analysis on open data, but it is not yet ready for submission. Three items remain open: (i) the large-language-model (LLM) measure of occupational exposure to visual content creation has not been validated against human coders; (ii) the evidence on labor effects is small and imprecise, and we do not claim a causal effect of generative visual AI; (iii) model release dates and the bibliographic details marked † must be verified. All reported numbers are produced by the code and data in the accompanying repository.',font:F,size:22})],spacing:{...SGL},shading:{fill:'F5F5F5',type:ShadingType.CLEAR,color:'auto'}}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(new Paragraph({children:[new TextRun({text:'Abstract',bold:true,font:F,size:24})],alignment:AlignmentType.CENTER,spacing:{after:120,...SGL}}),
 new Paragraph({children:runs('Does generative AI that creates images and video displace creative workers, or is its effect delayed? We model labor demand in visual-content occupations as the share of employers who have adopted times the net effect among adopters, where adoption requires output of acceptable quality at low review cost and is held back by expertise and legal frictions. Eurostat survey data show that adoption is already substantial (9.6% of European firms with ten or more employees use AI that generates pictures, video, or audio) and that firms that considered AI cite lack of expertise and legal and privacy uncertainty far more than lack of usefulness. In UK online job adverts for 403 occupations, occupational exposure to visual content creation is associated with small, imprecise declines after 2022 that follow a pre-existing COVID-era pattern, are not concentrated in low-quality-requirement tasks, and are too large to attribute to current adoption levels.'),spacing:{...SGL,after:200},alignment:AlignmentType.JUSTIFIED}),
 new Paragraph({children:[new TextRun({text:'Keywords: ',bold:true,font:F,size:24}),new TextRun({text:'generative AI; technology adoption; delayed diffusion; assimilation gap; creative labor; image and video generation; online job adverts; complementary assets',font:F,size:24})],spacing:{...SGL,after:120}}),
 new Paragraph({children:[new TextRun({text:'History: ',bold:true,font:F,size:24}),new TextRun({text:'[to be completed by the journal].',font:F,size:24})],spacing:SGL}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(H1('1. Introduction'),
P('Generative AI systems that create images from text prompts, released from 2022, and systems that create video, released from 2024, make a first draft of visual content almost costless. A natural expectation is that they will displace the people who produce such content. Yet general-purpose technologies have often shown a long gap between invention, adoption, and measurable labor-market effects: electric motors changed factory output decades after their introduction, and computers took years to show up in productivity (David 1990†; Brynjolfsson et al. 2021†). In information systems research, the same idea appears as the gap between a firm’s adoption of an innovation and its deeper assimilation into work (Fichman and Kemerer 1999†). Is generative visual AI displacing creative work today, or are we in an early-adoption phase in which displacement is still to come?'),
P('We study this question with open data and a model that separates adoption from displacement. The model treats the change in labor demand in an occupation as the product of two terms: the share of employers who have adopted the technology, and the net effect of adoption on hiring among those adopters, which combines substitution and a scale effect from cheaper content. Adoption of a visual generator for a task requires that its output meet the task’s quality requirement at a review cost below the cost of human production, and it is limited by frictions in expertise, legal clarity, and data protection. A small observed effect on labor demand is therefore consistent with several different states of the world: low adoption, low substitution among adopters, offsetting scale effects, or no effect at all. We use data to tell some of these apart.'),
P('We bring together three sources. First, Eurostat’s enterprise survey on AI, which in 2025 asks whether firms use AI that generates pictures, videos, or audio, and why firms that considered AI did not adopt it. Second, UK online job adverts by occupation from the Office for National Statistics (ONS), covering 413 four-digit occupations from 2017 to 2026. Third, an LLM-coded measure of occupational exposure to visual content creation built from O*NET task statements, which we map to UK occupations through the ISCO-08 classification. We also report, as supplementary evidence, US postings by sector and European employment by industry.'),
P('Our findings are as follows. Adoption is already substantial: 9.6% of European firms with ten or more employees use AI that generates pictures, video, or audio, rising to 27.9% among firms with 250 or more employees and to about 36% in publishing, film, and broadcasting. Among firms that considered AI but did not adopt it, 70% cite lack of expertise, 54% unclear legal consequences, and 53% data protection and privacy concerns, against 18% who consider AI not useful. In UK adverts, occupations with higher exposure to visual content creation show small declines after 2022 (about 2 to 3% per standard deviation of exposure by 2025 and 2026, with randomization p-values from 0.03 to 0.47 across years and specifications), but these declines resemble a reversal of a COVID-era pattern, are not concentrated in tasks with low quality requirements, vanish when one occupation is dropped, and are far too large, for the occupations with the highest exposure, to be explained by the observed adoption levels. We read the evidence as consistent with early adoption and little detectable displacement so far, and we do not claim that displacement is absent or will not come.'),
P('The paper contributes to information systems research in three ways. First, it offers a model that decomposes labor-demand effects into adoption and net effect among adopters, and uses it to turn a null-like estimate into a bound: the observed decline in the most exposed occupations is too large for current adoption to explain through substitution among adopters, which points to other causes. Second, it brings direct survey evidence on the frictions that delay adoption, expertise and legal and privacy uncertainty, rather than assuming them. Third, it documents a measurement strategy that links task-level data on visual content creation to occupation-level hiring data across countries, and is open and reproducible.'),
P('The remainder of the paper is organized as follows. Section 2 reviews related work. Section 3 presents the model and hypotheses. Section 4 describes the data and measures. Section 5 sets out the empirical strategy. Section 6 reports results. Section 7 discusses implications and limitations.'));

add(H1('2. Related Literature'),
H2('2.1 Delayed Adoption and Delayed Effects of General-Purpose Technologies'),
P('Research on general-purpose technologies argues that their effects arrive late because they require complementary investments in organization, skills, and processes (Bresnahan and Trajtenberg 1995†; David 1990†). Brynjolfsson et al. (2021)† formalize this as a productivity J-curve in which measured gains lag adoption because intangible complements are built first. Information systems research has a parallel tradition on diffusion and assimilation: Fichman and Kemerer (1999)† showed that organizations can acquire an innovation without deploying it, so that diffusion statistics overstate use. We apply these ideas to labor demand: counts of adopting firms may overstate the extent to which tasks have actually been shifted, and effects on hiring may follow adoption by years.'),
H2('2.2 AI Exposure and Labor Demand'),
P('A large literature measures how closely AI capabilities map onto occupational tasks (Webb 2020†; Felten et al. 2021†; Eloundou et al. 2023†). Acemoglu et al. (2022)† use online vacancies to study how AI-exposed establishments change hiring. Exposure measures describe where AI could matter; they do not say whether, or when, firms act on it. We use an exposure measure for a specific class of tasks, producing or editing visual content, and combine it with survey evidence on whether and why firms adopt.'),
H2('2.3 Cheaper Prediction, Cheaper Content, and Complements'),
P('Agrawal et al. (2018)† frame AI as a fall in the cost of prediction, which raises the value of complements such as judgment. Generative AI lowers the cost of producing a draft, so the standard implication is that cheaper content expands the quantity demanded and raises demand for direction, selection, and review. We do not review the growing empirical literature on generative AI and creative or freelance work in detail here; positioning against recent work in Information Systems Research, MIS Quarterly, and Management Science is to be completed before submission.'));

add(H1('3. Theory and Hypotheses'),
H2('3.1 Acceptance and Substitution at the Task Level'),
P('A firm needs visual assets such as images, layouts, or short videos. Producing an asset with human labor costs *θ*. Producing it with generative AI costs *c* for generation plus *r* for human review. With probability *a* the output is accepted. With probability 1 − *a* it fails the quality requirement and a human produces the asset at cost *θ*. The expected cost of the AI route is *c* + *r* + (1 − *a*)*θ*, so the firm substitutes AI when the acceptance rate exceeds a threshold:'),
EQ('a > a* = ( c + r ) / θ',1),
P('The acceptance rate *a* falls as the task’s quality requirement rises, so substitution is more likely for tasks with low quality requirements, such as routine graphics and internal-use visuals, than for brand-defining, technically exact, or legally sensitive work. The review cost *r* includes the cost of checking output for errors and for legal risks such as copyright and personal data, which depends on the clarity of the legal framework and on the firm’s expertise.'),
H2('3.2 From Task Substitution to Occupational Labor Demand'),
P('Let *A_ot* be the share of employers of occupation *o* that have adopted a visual generator for the occupation’s tasks by time *t*. If adopters change their demand for the occupation by a log amount *β_o* and non-adopters do not change, the aggregate log change in labor demand is approximately:'),
EQ('Δ ln N_ot ≈ A_ot · β_o',2),
P('The effect among adopters *β_o* combines a substitution effect, which is negative where *a* > *a**, and a scale effect, which is positive because cheaper assets raise the quantity demanded and create work in direction, selection, and review. Adoption *A_ot* follows a diffusion process. A firm adopts when the expected gain exceeds a fixed cost of adoption that covers expertise, workflow redesign, and legal and privacy compliance. Because these fixed costs differ across firms and fall over time, *A_ot* rises gradually. Two implications follow. First, a small aggregate effect is expected when *A_ot* is small, even if *β_o* is large. Second, effects on hiring should grow as adoption spreads.'),
P('Equation (2) also yields a bound. If we can estimate Δ ln N and have an estimate of the adoption share, then *β_o* ≈ Δ ln N / *A_ot*. If this ratio exceeds what substitution could plausibly deliver, the decline cannot be due to adoption alone, and other causes must be at work.'),
H2('3.3 Hypotheses'),
CAP('**Table 1.** Hypotheses and observable predictions'),
TBL([900,4000,4460],[
 ['','Hypothesis','Prediction in the data'],
 ['H1','Early adoption without detectable displacement: adoption of generative visual AI is substantial, while the aggregate labor-demand effect in exposed occupations is small relative to adoption.','Eurostat adoption is substantial and rising; the UK occupation-level effect of exposure is small and, scaled by adoption, bounded.'],
 ['H2','Quality threshold: declines concentrate in occupations whose visual tasks have low quality requirements.','Exposure to low-quality-requirement creation tasks predicts larger declines than exposure to high-requirement tasks.'],
 ['H3','Frictions: adoption is held back by expertise and legal and privacy uncertainty rather than perceived uselessness.','Firms that considered AI but did not adopt cite expertise and legal and privacy concerns more often than usefulness; countries with more such citations adopt less.'],
 ['H4','Delay: the effect of exposure on hiring grows over time as adoption spreads.','Coefficients on exposure become more negative in later years.']]),
C());

add(H1('4. Data and Measures'),
H2('4.1 Adoption and Barriers: Eurostat Enterprise Survey on AI'),
P('We use the Eurostat survey on ICT usage in enterprises, which covers firms with ten or more employees in EU member states and some other European countries. The 2025 wave includes an indicator for enterprises using AI technologies that generate pictures, videos, or sound and audio, which is the closest available measure of adoption of generative visual AI. The indicator is available only for 2025, so we use text generation (which was asked in 2021, 2023, 2024, and 2025) and image recognition and processing for time trends. The survey also asks enterprises that considered using AI but did not why they did not: lack of expertise, unclear legal consequences, data protection and privacy concerns, costs, data availability or quality, incompatibility with existing systems, ethical considerations, and the view that AI is not useful. We use results for the EU27 by size class and by NACE sector, and by country.'),
H2('4.2 Hiring: UK Online Job Adverts by Occupation'),
P('We use the ONS experimental series Labour Demand Volumes by Standard Occupational Classification (SOC 2020), which is based on Textkernel data. It gives the number of new online job adverts in the United Kingdom each month from January 2017 to August 2026 for 413 four-digit SOC unit groups. The ONS assigns each advert to an occupation by matching its job title to a taxonomy. Several months have suppressed or missing cells (all occupations for March 2026, and many for June and July 2025 and June 2026), which we fill by linear interpolation for up to two consecutive months. We sum adverts over twelve-month windows from July to June, which removes seasonality. The base year is July 2021 to June 2022, which precedes the public release of text-to-image systems in mid-2022 and of ChatGPT in November 2022 (dates to be verified). We keep occupations with at least 1,000 adverts in the base year, which leaves 403 occupations.'),
H2('4.3 Occupational Exposure to Visual Content Creation'),
P('We classify each of the 18,796 task statements in O*NET (version 29.1) with an LLM. The rubric scores a task 2 if producing or editing visual content (graphics, illustrations, photographs, video, animation, layouts) is central, 1 if visual content is a partial or supporting product, and 0 otherwise; it excludes looking at or inspecting things, writing, and audio production. The full rubric is in Appendix A. In total 859 tasks (4.6%) score 1 or 2, and 180 (1.0%) score 2. Occupation-level exposure is the mean over the occupation’s tasks of the score divided by two. We map O*NET occupations to UK SOC unit groups in two steps: O*NET to ISCO-08 using the crosswalk that O*NET publishes (ESCO occupations carry ISCO codes), and ISCO-08 to UK SOC 2020 using the ONS coding index, which records an ISCO-08 code for each indexed job title. A UK occupation’s exposure is the weighted mean over the ISCO codes attached to it. Exposure is highly skewed: its standard deviation across UK occupations is 0.037, the highest values are for graphic and multimedia designers (8.0 standard deviations above the mean), arts officers and producers, artists, web design professionals, and photographers. We control for occupational exposure to LLMs (Eloundou et al. 2023†), mapped in the same way.'),
P('The measure has not been validated against human coders. We provide convergent evidence from a transparent rule-based score built from the rubric text: its correlation with the LLM score across occupations is 0.71 in the first half and 0.91 in the second half of the data classified first (n = 196 and 192 occupations), and all main results are similar with the rule-based score. A second LLM pass codes the quality requirement of the 859 tasks that score 1 or 2 as low (237 tasks), medium (355), or high (267), using the rubric in Appendix A. An earlier attempt to measure a broader construct, dependence of tasks on visual perception, agreed poorly with a human coder (Cohen’s κ about 0.2 on 200 tasks) and was discontinued.'),
H2('4.4 Supplementary Data'),
P('We also use the Indeed Hiring Lab job postings index by sector for the United States (47 sectors, daily, 2020–2026) and Eurostat Labour Force Survey employment by NACE two-digit industry for the EU27 (2015–2025). Their results are reported in Section 6.6.'));

add(H1('5. Empirical Strategy'),
H2('5.1 Adoption and Barriers'),
P('We report adoption of generative visual AI and of text generation by size class and sector, and the share of enterprises that considered AI but did not adopt it and cite each barrier. To check whether our exposure measure predicts adoption, we compute sector-level exposure as the employment-weighted mean over ISCO major groups (from the Eurostat Labour Force Survey structure in 2021) and relate adoption to it across sectors and across country-sector cells with country fixed effects, with permutation inference over sector labels. We relate countries’ adoption to the share of considerers who cite each barrier.'),
H2('5.2 Dose-Response Event Study in UK Adverts'),
P('For each occupation *i* and year *t* we compute *y_it* = ln(adverts in year *t*) − ln(adverts in the base year). For each year other than the base year we estimate'),
EQ('y_it = α_t + b_t · z(E_i) + c_t · z(L_i) + μ_g(i),t + ε_it',3),
P('where *E_i* is occupational exposure to visual content creation, *L_i* is occupational exposure to LLMs, both standardized, and *μ_g(i),t* are fixed effects for SOC sub-major groups (two-digit), so that the comparison is between occupations in the same broad group. Standard errors are clustered by SOC minor group (three-digit). We also report specifications with major-group fixed effects and without the language control. Because exposure is a continuous, pre-determined characteristic, *b_t* for years before the base year provides a check on pre-existing differences, although the pre-period contains the COVID shock and cannot be used to test parallel trends cleanly. As an alternative to conventional standard errors we compute randomization p-values by permuting exposure across occupations within sub-major groups (2,000 draws). In Section 6.3 we also compare three occupation groups chosen from occupation labels before looking at outcomes: image and video production (graphic and multimedia designers, artists, photographers and audio-visual operators, web design professionals), creative direction and production, and text production (writers, journalists, editors).'),
H2('5.3 Quality-Requirement Heterogeneity'),
P('To test H2 we split exposure into components by the quality requirement of the creation tasks: *E_low* is the mean over an occupation’s tasks of the creation score divided by two, counting only tasks coded as low quality requirement, and *E_high* is the same for tasks coded high. We estimate equation (3) with both components and test whether the coefficient on *E_low* is more negative than that on *E_high*.'),
H2('5.4 Scaling by Adoption'),
P('To assess whether the observed declines are of a size that adoption could explain, we use equation (2). For selected occupations, we compute the predicted log change from the estimated coefficient and the occupation’s exposure, and divide it by assumed adoption shares of 10% (the EU27 average for firms using AI that generates pictures, video, or audio), 20% (professional, scientific and technical services), and 36% (publishing, film, and broadcasting). The calculation is a stylized plausibility check because adoption among employers of a specific occupation is not observed.'));

add(H1('6. Results'),
H2('6.1 Adoption and Barriers (H1, H3)'),
P('Adoption of generative visual AI is already substantial in Europe. In 2025, 9.6% of EU27 enterprises with ten or more employees used AI that generates pictures, videos, or audio, close to the 8.8% that used text-generation AI. Adoption rises steeply with size and varies by sector (Table 2). Text-generation adoption, which is available for earlier years, rose from 1.3% in 2021 to 2.1% in 2023, 5.4% in 2024, and 8.8% in 2025, and use of at least one AI technology rose from 7.7% to 20.0%. Image recognition, in contrast, grew slowly, from 2.1% to 3.8%. These patterns indicate that adoption is early and accelerating rather than absent.'),
CAP('**Table 2.** Adoption of AI by size class and sector, EU27, 2025 (percentage of enterprises with 10 or more employees)'),
TBL([3860,2750,2750],[
 ['Group','Picture, video, or audio generation','Text generation'],
 ['All enterprises (10+)','9.6','8.8'],
 ['10–49 employees','8.1','7.0'],
 ['50–249 employees','14.4','14.8'],
 ['250 or more employees','27.9','31.7'],
 ['Information and communication (J)','35.5','42.2'],
 ['Publishing, film, TV, music (J58–J60)','36.2','34.0'],
 ['Professional, scientific, technical (M)','18.7','17.7'],
 ['Construction (F)','4.5','3.2'],
 ['Transportation and storage (H)','4.0','3.9']]),
NOTE('*Note.* Eurostat, enterprise survey on ICT usage, indicators E_AI_TPVSG and E_AI_TNLG. The picture, video, or audio generation indicator is available only for 2025.'),
P('Table 3 reports why firms that considered AI did not adopt it. The most cited reasons are lack of expertise (70%), unclear legal consequences (54%), and data protection and privacy concerns (53%); costs are cited by 38% and the view that AI is not useful by 18%. The pattern is similar across size classes. These barriers are expressed in the language of capability and legal and privacy uncertainty rather than usefulness. They concern AI in general, not visual generators specifically, and they are answers from firms that considered AI, so they do not describe all non-adopters.'),
CAP('**Table 3.** Reasons for not using AI among enterprises that considered it, EU27, 2025 (percentage of such enterprises)'),
TBL([5360,4000],[
 ['Reason','Share citing (%)'],
 ['Lack of relevant expertise','70.3'],
 ['Unclear legal consequences','53.6'],
 ['Data protection and privacy concerns','52.7'],
 ['Difficulties with availability or quality of data','43.5'],
 ['Incompatibility with existing equipment, software, or systems','41.6'],
 ['Costs seem too high','38.4'],
 ['Ethical considerations','24.6'],
 ['AI is not useful for the enterprise','17.8']]),
NOTE('*Note.* Eurostat, enterprise survey on ICT usage, 2025, enterprises with 10 or more employees. Multiple answers allowed.'),
P('Across 23 countries, adoption of picture, video, or audio generation is negatively correlated with the share of considerers citing costs (r = −0.76) and weakly with the share citing unclear legal consequences (r = −0.24) and data protection (r = −0.02), and positively with the share citing lack of expertise (r = 0.46). The last correlation is plausible because countries with more adopters have more considerers who report the difficulty of doing it. With 23 countries these correlations are descriptive. They offer little support for the view that cross-country differences in legal concerns explain differences in adoption, although legal and privacy concerns are widespread. We therefore treat H3 as partly supported: firms report expertise and legal and privacy uncertainty as the main obstacles, but we cannot show that these obstacles explain who adopts.'),
P('Our exposure measure predicts adoption across sectors, but not specifically. Across the 11 sectors in the survey, sector-level exposure to visual content creation correlates with adoption of picture, video, or audio generation at 0.84, but also with adoption of text generation (0.83) and of image recognition (0.81). In country-sector cells with country fixed effects, a standard deviation of sector exposure is associated with 0.57 log points higher adoption of picture, video, or audio generation (permutation p = 0.006), 0.65 for text generation (p = 0.003), and 0.58 for image recognition (p = 0.005). Sectors with more creative and professional work are simply more digitally intensive and adopt every kind of AI more. The exposure measure thus carries a general adoption propensity, which is one reason we control for language exposure and use within-group comparisons in the labor-demand analysis.'),
H2('6.2 UK Adverts: Dose-Response (H1, H4)'),
P('Table 4 and Figure 1 report the coefficients on occupational exposure to visual content creation. With sub-major group fixed effects and the control for LLM exposure, a standard deviation of exposure is associated with 2.4% fewer adverts in the year ending June 2023 relative to the base year (standard error 1.2), 1.1% fewer in 2024 (1.9), 2.1% fewer in 2025 (1.6), and 3.3% fewer in 2026 (1.7). Randomization p-values are 0.47 for 2024, 0.16 for 2025, and 0.03 for 2026. Without the language control the coefficients are larger (−4.3% in 2025 and −5.2% in 2026, standard errors 1.6 and 1.8) because exposure to visual content creation and exposure to LLMs are positively correlated across occupations (0.25). With major-group fixed effects the estimates are between −2.3% and −3.1% in 2023–2026. Results are similar when exposure is the rule-based score (−2.0% in 2025, −3.4% in 2026, randomization p = 0.17 and 0.02).'),
CAP('**Table 4.** UK adverts: coefficient on occupational exposure to visual content creation (per standard deviation), change in log adverts relative to July 2021–June 2022'),
TBL([3160,1275,1275,1275,1275,1100],[
 ['Specification','2021','2023','2024','2025','2026'],
 ['Sub-major FE, LLM control','−0.030 (0.011)','−0.024 (0.012)','−0.011 (0.019)','−0.021 (0.016)','−0.033 (0.017)'],
 ['Sub-major FE, no LLM control','−0.033 (0.011)','−0.031 (0.012)','−0.024 (0.017)','−0.043 (0.016)','−0.052 (0.018)'],
 ['Major FE, LLM control','−0.027 (0.008)','−0.031 (0.010)','−0.023 (0.017)','−0.026 (0.016)','−0.026 (0.015)'],
 ['Randomization p (sub-major FE, LLM control)','','','0.467','0.157','0.029']]),
NOTE('*Note.* 403 UK occupations. Standard errors clustered by SOC minor group in parentheses. Columns are years ending in June; 2022 is the base. Pre-base coefficients for 2018, 2019, and 2020 (sub-major FE, LLM control) are +0.024 (0.014), +0.022 (0.014), and +0.005 (0.012).'),
IMG('data/ons/uk_dose_response_llm.png',576,312),
CAP('**Figure 1.** Coefficient on occupational exposure to visual content creation by year, with 95% confidence intervals (sub-major FE, LLM control)'),
P('Three features limit the interpretation. First, the coefficient for 2021 is also negative (−0.030, standard error 0.011), which means exposed occupations were lower in 2021 than in the 2022 base. Relative to 2019, exposed occupations lost about 5.2% per standard deviation by 2021, recovered to −2.2% in 2022, and then fell back to between −3.3% and −5.5% in 2023–2026. A substantial part of the post-2022 decline is therefore a reversal of the 2022 recovery from COVID, and the data cannot separate it from an effect of generative AI. Second, the result is fragile: with web design professionals dropped, the 2025 coefficient falls to −0.010 (0.013); with occupations weighted by base-year adverts it is −0.013 (0.016); with the share of tasks scoring one or more as exposure it is −0.017 (0.017). Third, the coefficients do not grow steadily: they are −0.024 in 2023, −0.011 in 2024, −0.021 in 2025, and −0.033 in 2026. A growing effect is what the delayed-adoption view predicts (H4), but the pattern is not monotone and the confidence intervals overlap. We conclude that the evidence is consistent with a small, growing effect but cannot reject no effect.'),
H2('6.3 UK Adverts: Occupation Groups'),
P('The three groups chosen from occupation labels show a similar story with larger numbers (Table 5). Relative to other occupations, adverts for image and video production occupations fell by 0.20 log points in the first year after the base year (randomization p = 0.032) and by 0.38 in the third and fourth (p = 0.011). Creative direction occupations fell by less (−0.11 in the first year and −0.23 in the third; p between 0.15 and 0.27). Text production occupations did not differ from others in the first two years (−0.10 and +0.03) and fell later (−0.33 in the third year, p = 0.046; −0.47 in the fourth, p = 0.008), led by journalists and editors. The decline in image and video production is concentrated in web design professionals, who rank first or third among 405 occupations in the later years (log changes of −1.45 and −1.36 against a comparison median of −0.43 and −0.46); graphic and multimedia designers rank 32nd to 38th (−0.86 and −0.89), and artists and photographers are close to the median. Without web design professionals the third- and fourth-year differences fall to −0.16 and −0.21. Placebo design occupations that image generators do not target (interior designers, fashion and accessories designers, design occupations not elsewhere classified) also fell relative to others (−0.16, −0.20, and −0.06 in the first, third, and fourth years). Between June 2019 and June 2021 the image and video production group had already fallen by 0.32 log points relative to others, and the other two groups by 0.36 and 0.31.'),
CAP('**Table 5.** UK occupation groups: change in log adverts from July 2021–June 2022, group minus other occupations'),
TBL([2660,1675,1675,1675,1675],[
 ['Group (comparison pool)','Jul22–Jun23','Jul23–Jun24','Jul24–Jun25','Jul25–Jun26'],
 ['Image and video production (all)','−0.196 (0.032)','−0.262 (0.047)','−0.378 (0.011)','−0.384 (0.011)'],
 ['Image and video production (SOC 1–3)','−0.217 (0.016)','−0.294 (0.044)','−0.381 (0.008)','−0.389 (0.007)'],
 ['Creative direction (all)','−0.113 (0.225)','−0.159 (0.268)','−0.230 (0.168)','−0.210 (0.224)'],
 ['Creative direction (SOC 1–3)','−0.134 (0.149)','−0.191 (0.211)','−0.233 (0.159)','−0.216 (0.179)'],
 ['Text production (all)','−0.098 (0.279)','+0.029 (0.839)','−0.333 (0.046)','−0.473 (0.008)'],
 ['Text production (SOC 1–3)','−0.119 (0.201)','−0.003 (0.982)','−0.336 (0.049)','−0.478 (0.005)']]),
NOTE('*Note.* Entries are the mean log change of the group minus that of the comparison pool, with randomization p-values in parentheses. Comparison pools: all other occupations with at least 1,000 adverts in the base year (395), and the subset in SOC major groups 1 to 3 (249). Months with missing cells are interpolated. The last column includes the imputed month of March 2026.'),
H2('6.4 Quality-Requirement Heterogeneity (H2)'),
P('H2 is not supported. Exposure to low-quality-requirement creation tasks is associated with declines in 2023 and 2024 (−0.026 and −0.019, standard errors 0.016 and 0.023), but the coefficient is close to zero in 2025 (−0.005) and small in 2026 (−0.017). Exposure to high-requirement tasks has coefficients near zero throughout. The difference between the low and high coefficients is −0.029 (standard error 0.025) in 2023, −0.028 (0.036) in 2024, 0.000 (0.033) in 2025, and −0.014 (0.036) in 2026 (Table 6). The difference has the same sign in the pre-period (−0.046 in 2018 and −0.031 in 2019), and none of the differences is statistically distinguishable from zero. Low- and high-requirement exposure are correlated across occupations (0.48), which limits power. We cannot reject that quality requirements matter, but we find no support for it.'),
CAP('**Table 6.** UK adverts: coefficients on exposure to low- and high-quality-requirement creation tasks (per standard deviation)'),
TBL([1360,2000,2000,2000,2000],[
 ['Year','Low requirement','High requirement','Low minus high','Pre-period or post'],
 ['2018','−0.012 (0.017)','+0.034 (0.019)','−0.046 (0.032)','pre'],
 ['2019','−0.006 (0.017)','+0.026 (0.018)','−0.031 (0.030)','pre'],
 ['2023','−0.026 (0.016)','+0.003 (0.012)','−0.029 (0.025)','post'],
 ['2024','−0.019 (0.023)','+0.009 (0.017)','−0.028 (0.036)','post'],
 ['2025','−0.005 (0.021)','−0.005 (0.018)','0.000 (0.033)','post'],
 ['2026','−0.017 (0.021)','−0.003 (0.020)','−0.014 (0.036)','post']]),
NOTE('*Note.* Sub-major group fixed effects and LLM control; standard errors clustered by SOC minor group. Quality requirement of the 859 creation tasks was coded by an LLM (Appendix A).'),
H2('6.5 Scaling by Adoption'),
P('Table 7 applies equation (2). For graphic and multimedia designers, who have the highest exposure (8.0 standard deviations above the mean), the coefficients imply a predicted log change of −0.17 in 2025 and −0.26 in 2026 (specification with the language control). If 36% of employers of this occupation had adopted, which is the EU27 rate in publishing, film, and broadcasting, the implied effect among adopters would be −0.46 and −0.73 log points, a fall in adverts of 37% to 52% among adopters. At the EU27 average adoption rate of 10% the implied effect among adopters is −1.7 and −2.6 log points, which means 81% to 93% fewer adverts. The lower end of the 95% interval is larger still. Without the language control the implied numbers are about twice as large. These magnitudes are implausibly large for substitution among adopters, who would have to cut hiring for the occupation sharply and persistently within a few years of a technology’s release, while still adopting less than the average firm in the professions that employ designers. Either adoption among employers of these occupations is far higher than the sector averages in Table 2, or most of the observed decline is not due to adoption of generative visual AI. The first reading is possible because designers are concentrated in sectors with higher adoption and in small firms that buy tools off the shelf. The second reading is consistent with the COVID-era pattern in Section 6.2 and with the decline of design occupations that image generators do not target.'),
CAP('**Table 7.** Implied effect among adopters for graphic and multimedia designers (log points)'),
TBL([3160,1550,1550,1550,1550],[
 ['Quantity','Adoption 10%','Adoption 20%','Adoption 36%','Predicted aggregate'],
 ['2025, point estimate','−1.67','−0.84','−0.46','−0.17'],
 ['2025, lower end of 95% CI','−4.14','−2.07','−1.15','−0.41'],
 ['2026, point estimate','−2.62','−1.31','−0.73','−0.26'],
 ['2026, lower end of 95% CI','−5.25','−2.62','−1.46','−0.52']]),
NOTE('*Note.* Predicted aggregate log change = coefficient per standard deviation × 8.0 standard deviations (sub-major FE, LLM control). Implied effect among adopters = predicted aggregate divided by the adoption share. Stylized calculation; adoption among employers of the occupation is not observed.'),
H2('6.6 Supplementary Evidence: US Sectors and European Employment'),
P('US sector postings (Indeed) show a similar relative decline in the sectors Arts & Entertainment, Media & Communications, and Marketing, chosen before looking at outcomes. Relative to the other 44 sectors, the log change in postings from January–March 2022 to October 2022–March 2023 was −0.23 (randomization p = 0.018), and by October 2024–March 2025 it was −0.32 (p = 0.063). The same sectors had risen 0.11 more than others in the year before the base period (p = 0.25). They were not the largest decliners: between the base and October 2024–March 2025 Marketing ranked fifth, Media & Communications sixth, and Arts & Entertainment fifteenth of 47 by size of fall, while Software Development ranked first and Data & Analytics second. In European Labour Force Survey data, employment in video and film production (NACE J59), advertising (M73), and other professional, scientific and technical activities including design and photography (M74) rose between 2019–2021 and 2023–2025 by 0.13, 0.11, and 0.15 log points against a median of 0.04 across 88 industries. The creative industries gained 0.09 log points relative to all other industries (randomization p = 0.20) and 0.04 relative to knowledge-service industries (p = 0.52). Neither source separates visual generation from the technology slowdown, and employment and adverts measure different things.'),
H2('6.7 Summary of Evidence Against the Hypotheses'),
P('H1 is supported in a limited sense: adoption is substantial and rising, while estimated labor-demand effects are small, imprecise, and partly a reversal of earlier trends; the scaling exercise shows that the largest observed declines are too large for current adoption to explain through substitution. H2 is not supported. H3 is partly supported: firms cite expertise and legal and privacy uncertainty far more than usefulness, but cross-country variation in these concerns does not clearly explain adoption. H4 is weakly supported: the coefficients are most negative in 2026, but the pattern is not monotone and the effect cannot be separated from the pre-existing pattern.'));

add(H1('7. Discussion'),
H2('7.1 Contributions'),
P('The paper offers a model that decomposes the labor-demand effect of a technology into adoption and the net effect among adopters, and uses it to bound what adoption can explain. It brings direct survey evidence on obstacles to adoption, which are expertise and legal and privacy uncertainty, and shows that adoption of generative visual AI is already substantial. It links task-level data on visual content creation to occupation-level hiring data across countries with an open and reproducible pipeline, and shows that estimated effects are small and sensitive to a few occupations. For research on delayed diffusion, the results illustrate how adoption statistics and labor outcomes can diverge: the adoption statistics are high enough to signal an early-adoption phase, while the labor outcomes have not yet moved in a way that can be attributed to the technology.'),
H2('7.2 Implications'),
P('For managers, the evidence on barriers suggests that the binding constraints on adopting generative visual AI are organizational: expertise, review and legal compliance, and data protection, rather than the capability of the tools. Investing in review capacity and in clear policies on copyright and personal data may therefore matter more than waiting for better models. For policy makers, the finding that effects on hiring are small so far should not be read as evidence that they will remain so. If adoption continues to rise at the pace seen for text generation, effects on hiring could appear within a few years, and monitoring should rely on occupation-level data that distinguish production roles from direction roles. For information systems research, the paper points to the assimilation gap as a way to interpret generative AI: counting adopters is not the same as measuring the shift of tasks.'),
H2('7.3 Limitations'),
P('The identification is weak. Exposure is a continuous measure, but the pre-period contains the COVID shock, and the post-2022 pattern resembles a reversal of the 2022 recovery; the coefficients are small and rely on a few occupations. We do not observe adoption by employers of each occupation, so the scaling exercise is a stylized check. The adoption survey covers Europe and asks about AI in general for the barriers, whereas the hiring data are for the United Kingdom, so we link them only through sector averages. The Eurostat indicator for generative visual AI is available for one year, so we cannot show its growth. The exposure measure is LLM-coded and has not been validated against human coders, although a rule-based score gives similar results. The mapping from O*NET to UK occupations goes through ISCO-08 and is approximate. The ONS series is experimental and has missing months that we interpolate. Adverts measure hiring intent, not employment, and substitution may occur through hours, outsourcing, or freelancing, which adverts cannot show. Model release dates are approximate. Finally, our model abstracts from changes in the quality and variety of assets and from price effects.'),
H1('8. Conclusion'),
P('Generative visual AI is being adopted, with about one in ten European firms using it in 2025 and about one in three in publishing, film, and broadcasting, and firms that have not adopted point to expertise and legal and privacy uncertainty as the main obstacles. In UK job adverts, occupations with more visual content creation show small declines after 2022 that are hard to separate from a COVID-era pattern, that are not concentrated in low-quality-requirement tasks, and that are too large in the most exposed occupations for current adoption to explain through substitution. The evidence fits an early-adoption phase in which displacement is not yet detectable, but it does not show that displacement will arrive. Testing the delayed-displacement view requires firm-level data that link adoption to hiring, a validated task measure, and several more years of data.'));

add(new Paragraph({children:[],pageBreakBefore:true}),H1('Appendix A. Rubrics Used for LLM Coding'),
P('*Visual content creation score (applied to all 18,796 O*NET task statements; model: Claude Sonnet 5.5 through the OpenRouter API; temperature 0; 20 tasks per request).* Score each task for how much it involves producing or editing visual content: creating, designing, drawing, illustrating, photographing, filming, animating, retouching, editing, laying out, or rendering images, graphics, video, or other visual media. 2 = producing or editing visual content is central. 1 = visual content is a partial or supporting product of the task. 0 = the task does not involve producing or editing visual content. Technical drawings and engineering blueprints count only when the task is about producing them as drawings or graphics. Reading, inspecting, or looking at things does not count. Writing and audio production do not count.'),
P('*Quality-requirement score (applied to the 859 tasks scoring 1 or 2).* Rate how demanding the acceptance standard is for the visual output of the task. 0 = low: generic, routine, draft, or internal-use visuals where good-enough output is acceptable and errors are cheap to fix. 1 = medium: visuals for external audiences or clients where polish matters but several acceptable solutions exist and review is routine. 2 = high: brand-defining, safety-critical, legally or regulatorily sensitive, technically exact, or signature or original artistic work where errors are costly or the particular creator’s judgment is central.'),
P('The prompts are in the repository as prompt_creation.txt and prompt_quality.txt. Data and code are in the accompanying repository (isr_paper).'));

add(new Paragraph({children:[],pageBreakBefore:true}),H1('References'),
REF('Acemoglu, D., Autor, D., Hazell, J., and Restrepo, P. 2022. Artificial intelligence and jobs: Evidence from online vacancies. *Journal of Labor Economics* 40(S1):S293–S340.†'),
REF('Agrawal, A., Gans, J., and Goldfarb, A. 2018. *Prediction Machines: The Simple Economics of Artificial Intelligence*. Boston: Harvard Business Review Press.†'),
REF('Bresnahan, T. F., and Trajtenberg, M. 1995. General purpose technologies: “Engines of growth”? *Journal of Econometrics* 65(1):83–108.†'),
REF('Brynjolfsson, E., Rock, D., and Syverson, C. 2021. The productivity J-curve: How intangibles complement general purpose technologies. *American Economic Journal: Macroeconomics* 13(1):333–372.†'),
REF('David, P. A. 1990. The dynamo and the computer: An historical perspective on the modern productivity paradox. *American Economic Review* 80(2):355–361.†'),
REF('Eloundou, T., Manning, S., Mishkin, P., and Rock, D. 2023. GPTs are GPTs: An early look at the labor market impact potential of large language models. arXiv:2303.10130.†'),
REF('Eurostat. ICT usage in enterprises: artificial intelligence by size class of enterprise (isoc_eb_ai) and by NACE Rev. 2 activity (isoc_eb_ain2); Labour Force Survey employed persons by occupation and economic activity (lfsa_eisn2) and by detailed economic activity (lfsa_egan22d). Accessed via the Eurostat dissemination API.'),
REF('Felten, E., Raj, M., and Seamans, R. 2021. Occupational, industry, and geographic exposure to artificial intelligence. *Strategic Management Journal* 42(12):2195–2217.†'),
REF('Fichman, R. G., and Kemerer, C. F. 1999. The illusory diffusion of innovation: An examination of assimilation gaps. *Information Systems Research* 10(3):255–275.†'),
REF('Indeed Hiring Lab. Job Postings Index, by sector, United States (data repository hiring-lab/job_postings_tracker). Creative Commons Attribution 4.0 International License.'),
REF('National Center for O*NET Development. O*NET Database, version 29.1 (Task Statements; Abilities) and crosswalk of ESCO occupations to O*NET-SOC. Creative Commons Attribution 4.0 International License.'),
REF('Office for National Statistics. Labour demand volumes by Standard Occupation Classification (SOC 2020), UK: January 2017 to August 2026 (experimental statistics based on Textkernel data); and SOC 2020 Volume 2: the coding index. Open Government Licence.'),
REF('Webb, M. 2020. The impact of artificial intelligence on the labor market. Working paper, Stanford University.†'),
new Paragraph({children:runs('† Details taken from memory or from the earlier research proposal without independent verification; to be checked before circulation.',{size:20}),spacing:{...SGL,before:200}}));

const doc=new Document({
 styles:{default:{document:{run:{font:F,size:24}}},paragraphStyles:[
  {id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:0}},
  {id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:1}},
  {id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,italics:true,font:F},paragraph:{outlineLevel:2}}]},
 sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,bottom:1440,left:1440,right:1440}}},
  footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],font:F,size:20})]})]})},
  children:body}]});
Packer.toBuffer(doc).then(b=>fs.writeFileSync('ISR_Paper_Early_Adoption_Delayed_Displacement.docx',b));
