const fs=require('fs');
const {Document,Packer,Paragraph,TextRun,ImageRun,Table,TableRow,TableCell,WidthType,ShadingType,AlignmentType,HeadingLevel,BorderStyle,Footer,PageNumber,LineRuleType}=require('docx');
const F='Times New Roman';
const DBL={line:480,lineRule:LineRuleType.AUTO};
const SGL={line:240,lineRule:LineRuleType.AUTO};
// inline markup: *italic*  **bold**
function runs(t,o={}){const out=[];const re=/(\*\*[^*]+\*\*|\*[^*]+\*)/g;let last=0,m;
 while((m=re.exec(t))){if(m.index>last)out.push(new TextRun({text:t.slice(last,m.index),font:F,size:o.size||24,...o}));
  const s=m[0];if(s.startsWith('**'))out.push(new TextRun({text:s.slice(2,-2),bold:true,font:F,size:o.size||24,...o}));
  else out.push(new TextRun({text:s.slice(1,-1),italics:true,font:F,size:o.size||24,...o}));last=m.index+s.length;}
 if(last<t.length)out.push(new TextRun({text:t.slice(last),font:F,size:o.size||24,...o}));return out;}
const P=(t)=>new Paragraph({children:runs(t),spacing:{...DBL,after:0},indent:{firstLine:720},alignment:AlignmentType.LEFT});
const H1=(t)=>new Paragraph({heading:HeadingLevel.HEADING_1,children:[new TextRun({text:t,bold:true,font:F,size:24,allCaps:true})],spacing:{before:360,after:120,...SGL},keepNext:true});
const H2=(t)=>new Paragraph({heading:HeadingLevel.HEADING_2,children:[new TextRun({text:t,bold:true,font:F,size:24})],spacing:{before:240,after:120,...SGL},keepNext:true});
const H3=(t)=>new Paragraph({heading:HeadingLevel.HEADING_3,children:[new TextRun({text:t,bold:true,italics:true,font:F,size:24})],spacing:{before:200,after:100,...SGL},keepNext:true});
const EQ=(t,n)=>new Paragraph({children:[new TextRun({text:t,italics:true,font:F,size:24}),new TextRun({text:'\t('+n+')',font:F,size:24})],tabStops:[{type:'right',position:9360}],spacing:{before:120,after:120,...SGL},alignment:AlignmentType.CENTER});
const CAP=(t)=>new Paragraph({children:runs(t,{size:22}),spacing:{before:240,after:80,...SGL},keepNext:true,alignment:AlignmentType.CENTER});
const NOTE=(t)=>new Paragraph({children:runs(t,{size:20}),spacing:{before:60,after:200,...SGL}});
const C=(t)=>new Paragraph({children:[new TextRun({text:'',font:F})],spacing:SGL});
const bd={style:BorderStyle.SINGLE,size:4,color:'000000'},nb={style:BorderStyle.NONE,size:0,color:'FFFFFF'};
function TBL(widths,rows,hdr=true){const tot=widths.reduce((a,b)=>a+b,0);
 return new Table({width:{size:tot,type:WidthType.DXA},columnWidths:widths,rows:rows.map((r,i)=>new TableRow({tableHeader:i===0&&hdr,cantSplit:true,children:r.map((c,j)=>new TableCell({width:{size:widths[j],type:WidthType.DXA},
  borders:{top:i===0?bd:nb,bottom:(i===0||i===rows.length-1)?bd:nb,left:nb,right:nb},margins:{top:50,bottom:50,left:90,right:90},
  shading:i===0?{fill:'EDEDED',type:ShadingType.CLEAR,color:'auto'}:undefined,
  children:[new Paragraph({children:runs(c,{size:20,bold:i===0}),spacing:SGL})]}))}))});}
const REF=(t)=>new Paragraph({children:runs(t),spacing:{...SGL,after:120},indent:{left:720,hanging:720}});
const TODO='[TO BE COMPLETED AFTER ESTIMATION]';

const IMG=(p,w,h)=>new Paragraph({children:[new ImageRun({type:'png',data:fs.readFileSync(p),transformation:{width:w,height:h}})],alignment:AlignmentType.CENTER,spacing:{before:120,after:60,...SGL},keepNext:true});
const body=[];
const add=(...x)=>body.push(...x);

add(new Paragraph({children:[new TextRun({text:'Early Adoption, Delayed Displacement? Generative Visual AI and Creative Work',bold:true,font:F,size:32})],alignment:AlignmentType.CENTER,spacing:{before:1200,after:240,...SGL}}),
 new Paragraph({children:[new TextRun({text:'[Author names and affiliations removed for double-blind review]',font:F,size:22})],alignment:AlignmentType.CENTER,spacing:{after:480,...SGL}}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(new Paragraph({children:[new TextRun({text:'Abstract',bold:true,font:F,size:24})],alignment:AlignmentType.CENTER,spacing:{after:120,...SGL}}),
 new Paragraph({children:runs('Does generative AI that creates images and video displace creative workers, or is its effect delayed? We model labor demand in visual-content occupations as the share of employers who have adopted times the net effect among adopters; adoption requires acceptable output quality at low review cost and is held back by expertise and legal frictions. Eurostat data show that 9.6% of European firms with ten or more employees use AI that generates pictures, video, or audio, and that firms cite expertise and legal and privacy uncertainty far more than lack of usefulness. In job-posting data for UK, European, and Canadian occupations, exposure to visual content creation predicts small, fragile declines after 2022 (about 1 to 3% per standard deviation), not concentrated in low-quality-requirement tasks. A conditional projection suggests that a 40% cut in demand among adopters would become detectable around 2029–2030.'),spacing:{...SGL,after:200},alignment:AlignmentType.JUSTIFIED}),
 new Paragraph({children:[new TextRun({text:'Keywords: ',bold:true,font:F,size:24}),new TextRun({text:'generative AI; technology adoption; delayed diffusion; assimilation gap; creative labor; image and video generation; online job adverts; complementary assets',font:F,size:24})],spacing:{...SGL,after:120}}),
 new Paragraph({children:[],pageBreakBefore:true}));

add(H1('1. Introduction'),
P('Generative AI that creates images from text prompts (available since 2022) and video (since 2024) makes a first draft of visual content almost free. The obvious expectation is that it will displace the people who produce such content. General-purpose technologies, however, have often taken a long time to reach the labor market: electric motors changed factory output decades after they appeared, and computers took years to show up in productivity statistics (David 1990; Brynjolfsson et al. 2021). Information systems research describes a related gap between a firm’s adoption of an innovation and its assimilation into everyday work (Fichman and Kemerer 1999). So is generative visual AI displacing creative work now, or are we still in an early phase of adoption? Studies of online freelance platforms already find lower demand for image creation (Demirci et al. 2025; Hui et al. 2024), but platforms are a setting where buyers can switch tools at little cost.'),
P('We address this question with open data and a model that separates adoption from displacement. In the model, the change in labor demand in an occupation is the product of two terms: the share of employers that have adopted the technology, and the net effect of adoption on hiring among those adopters, which combines substitution with a scale effect from cheaper content. A firm adopts a visual generator for a task only if its output meets the task’s quality requirement at a review cost below the cost of human production, and adoption is held back by frictions in expertise, legal clarity, and data protection. A small effect on labor demand can therefore mean low adoption, weak substitution among adopters, offsetting scale effects, or no effect at all. We use the data to narrow down which of these is more likely.'),
P('We combine three sources. The first is Eurostat’s enterprise survey on AI, which in 2025 asks whether firms use AI that generates pictures, video, or audio, and why firms that considered AI did not adopt it. The second is UK online job adverts by occupation from the Office for National Statistics (ONS), covering 413 four-digit occupations from 2017 to 2026. The third is an LLM-coded measure of occupational exposure to visual content creation, built from O*NET task statements and mapped to UK occupations through ISCO-08. For replication we use Eurostat’s experimental statistics on online job advertisements by three-digit ISCO occupation for 16 European countries from 2019 to 2024, and Statistics Canada’s Job Vacancy and Wage Survey for 2015 to 2026. US postings by sector and European employment by industry serve as supplementary evidence.'),
P('Adoption is already substantial. 9.6% of European firms with ten or more employees use AI that generates pictures, video, or audio; the share is 27.9% among firms with 250 or more employees and about 36% in publishing, film, and broadcasting. Among firms that considered AI but did not adopt it, 70% cite lack of expertise, 54% unclear legal consequences, and 53% data protection and privacy concerns, while 18% say AI is not useful. In UK adverts, occupations with higher exposure to visual content creation show small declines after 2022, about 2 to 3% per standard deviation of exposure by 2025 and 2026 (randomization p-values range from 0.03 to 0.47 across years and specifications). These declines resemble a reversal of a COVID-era pattern, are not concentrated in tasks with low quality requirements, vanish when one occupation is dropped, and, for the most exposed occupations, are far too large to be explained by observed adoption. The European replication has the same sign and similar size, with flat pre-period coefficients and only two post-2022 years (about −1.6% per standard deviation in 2023 and −1.2% in 2024 with the language control; −3.7% and −5.9% without). In Canada the coefficient is negative in the first post-2022 year (−2.2% per standard deviation, with occupation-group fixed effects) but not afterward. We also ask when displacement would become detectable. If demand among adopters fell by about 40% and adoption followed the recent path of text-generation AI, the effect would reach the detection threshold of our design around 2029 to 2030, and much later or never for smaller effects. Overall, the evidence fits early adoption with little detectable displacement so far; we do not claim that displacement is absent or that it will not come.'),
P('The paper makes four contributions to information systems research. First, it offers a model that splits the labor-demand effect into adoption and the net effect among adopters, and uses it to turn a null-like estimate into a bound: the observed decline in the most exposed occupations is too large for current adoption to explain through substitution among adopters, which points to other causes. Second, it brings direct survey evidence on the frictions that delay adoption (expertise and legal and privacy uncertainty) instead of assuming them. Third, it turns the model into a conditional projection of when displacement would become visible in data of this kind, with criteria that later data can falsify. Fourth, it documents an open, reproducible way to link task-level data on visual content creation to occupation-level hiring data across countries.'),
P('The remainder of the paper is organized as follows. Section 2 reviews related work. Section 3 presents the model and hypotheses. Section 4 describes the data and measures. Section 5 sets out the empirical strategy. Section 6 reports results. Section 7 discusses implications and limitations.'));

add(H1('2. Related Literature'),
H2('2.1 Delayed Adoption and Delayed Effects of General-Purpose Technologies'),
P('Research on general-purpose technologies argues that their effects arrive late because they depend on complementary investments in organization, skills, and processes (Bresnahan and Trajtenberg 1995; David 1990). Brynjolfsson et al. (2021) formalize this as a productivity J-curve: measured gains lag adoption because the intangible complements are built first. Information systems research has a parallel tradition on diffusion and assimilation. Fichman and Kemerer (1999) showed that organizations can acquire an innovation without deploying it, so diffusion statistics overstate use. Recent work in this journal calls for research on how generative AI reshapes work and organizations (Gopal et al. 2025). We carry these ideas over to labor demand: counts of adopting firms may overstate how far tasks have actually shifted, and effects on hiring may trail adoption by years.'),
H2('2.2 AI Exposure and Labor Demand'),
P('A large literature measures how closely AI capabilities map onto occupational tasks (Webb 2020; Felten et al. 2021; Eloundou et al. 2023). Acemoglu et al. (2022) use online vacancies to study how AI-exposed establishments change their hiring. Exposure measures show where AI could matter; they do not show whether or when firms act on it. We construct an exposure measure for one class of tasks, producing or editing visual content, and combine it with survey evidence on whether firms adopt and why they do not.'),
H2('2.3 Cheaper Prediction, Cheaper Content, and Complements'),
P('Agrawal et al. (2018) describe AI as a fall in the cost of prediction, which raises the value of complements such as judgment. Generative AI lowers the cost of producing a draft, so the standard implication is that cheaper content raises the quantity demanded, and with it the demand for direction, selection, and review.'),
P('A growing literature studies the effect of generative AI on labor demand on online platforms. Hui et al. (2024) find that freelancers in occupations exposed to ChatGPT, DALL·E 2, and Midjourney lost employment and earnings on a large platform. Demirci et al. (2025) find that, relative to manual-intensive jobs, job posts for writing and coding fell by about 21% after ChatGPT, and posts for image creation by about 17% after the release of image-generating tools. Evidence from creator platforms points the same way: Zhou and Lee (2024) report that artists who adopted text-to-image tools raised their output, and Kim et al. (2026) find that the arrival of generative AI affected illustrators and other creator types on a large Japanese platform differently. Field evidence inside firms shows large productivity gains from generative AI for individual workers (Brynjolfsson et al. 2025), which is the micro-level counterpart of the net effect among adopters in our model. These studies use platform or within-firm data, where tasks are bought project by project and switching to a new tool or provider is cheap. We study the standing occupations of employers in national job-advert and vacancy statistics, where adoption has to pass through organizational frictions, and we link the evidence to survey data on adoption and its obstacles. The comparison suggests a hypothesis consistent with our model: substitution appears first where buyers can change tools or providers cheaply, and later where it requires organizational change.'),
H2('3.1 Acceptance and Substitution at the Task Level'),
P('A firm needs visual assets such as images, layouts, or short videos. Producing an asset with human labor costs *θ*. Producing it with generative AI costs *c* for generation plus *r* for human review. With probability *a* the output is accepted. With probability 1 − *a* it fails the quality requirement and a human produces the asset at cost *θ*. The expected cost of the AI route is *c* + *r* + (1 − *a*)*θ*, so the firm substitutes AI when the acceptance rate exceeds a threshold:'),
EQ('a > a* = ( c + r ) / θ',1),
P('The acceptance rate *a* falls as the task’s quality requirement rises, so substitution is more likely for tasks with low quality requirements, such as routine graphics and internal-use visuals, than for brand-defining, technically exact, or legally sensitive work. The review cost *r* includes the cost of checking output for errors and for legal risks such as copyright and personal data, which depends on the clarity of the legal framework and on the firm’s expertise.'),
H2('3.2 From Task Substitution to Occupational Labor Demand'),
P('Let *A_ot* be the share of employers of occupation *o* that have adopted a visual generator for the occupation’s tasks by time *t*. If adopters change their demand for the occupation by a log amount *β_o* and non-adopters do not change, the aggregate log change in labor demand is approximately:'),
EQ('Δ ln N_ot ≈ A_ot · β_o',2),
P('The effect among adopters *β_o* combines a substitution effect, which is negative where *a* > *a**, with a scale effect, which is positive because cheaper assets raise the quantity demanded and create work in direction, selection, and review. Adoption *A_ot* follows a diffusion process. A firm adopts when the expected gain exceeds a fixed cost of adoption that covers expertise, workflow redesign, and legal and privacy compliance. These fixed costs differ across firms and fall over time, so *A_ot* rises gradually. Two implications follow. First, a small aggregate effect is expected when *A_ot* is small, even if *β_o* is large. Second, the effect on hiring should grow as adoption spreads.'),
P('Equation (2) also yields a bound. If we can estimate Δ ln N and have an estimate of the adoption share, then *β_o* ≈ Δ ln N / *A_ot*. If this ratio exceeds what substitution could plausibly deliver, the decline cannot be due to adoption alone, and other causes must be at work.'),
H2('3.3 Hypotheses'),
CAP('**Table 1.** Hypotheses and observable predictions'),
TBL([900,4000,4460],[
 ['','Hypothesis','Prediction in the data'],
 ['H1','Early adoption without detectable displacement: adoption of generative visual AI is substantial, while the aggregate labor-demand effect in exposed occupations is small relative to adoption.','Eurostat adoption is substantial and rising; the UK occupation-level effect of exposure is small and, scaled by adoption, bounded.'],
 ['H2','Quality threshold: declines concentrate in occupations whose visual tasks have low quality requirements.','Exposure to low-quality-requirement creation tasks predicts larger declines than exposure to high-requirement tasks.'],
 ['H3','Frictions: adoption is held back by expertise and legal and privacy uncertainty rather than perceived uselessness.','Firms that considered AI but did not adopt cite expertise and legal and privacy concerns more often than usefulness; countries with more such citations adopt less.'],
 ['H4','Delay: the effect of exposure on hiring grows over time as adoption spreads.','Coefficients on exposure become more negative in later years.']]),
C());

add(H1('4. Data and Measures'),
H2('4.1 Adoption and Barriers: Eurostat Enterprise Survey on AI'),
P('We use the Eurostat survey on ICT usage in enterprises, which covers firms with ten or more employees in EU member states and some other European countries. The 2025 wave includes an indicator for enterprises using AI technologies that generate pictures, videos, or sound and audio, which is the closest available measure of adoption of generative visual AI. The indicator is available only for 2025, so we use text generation (which was asked in 2021, 2023, 2024, and 2025) and image recognition and processing for time trends. The survey also asks enterprises that considered using AI but did not why they did not: lack of expertise, unclear legal consequences, data protection and privacy concerns, costs, data availability or quality, incompatibility with existing systems, ethical considerations, and the view that AI is not useful. We use results for the EU27 by size class and by NACE sector, and by country.'),
H2('4.2 Hiring: UK Online Job Adverts by Occupation, and European Replication Data'),
P('We use the ONS experimental series Labour Demand Volumes by Standard Occupational Classification (SOC 2020), which is based on Textkernel data. It gives the number of new online job adverts in the United Kingdom each month from January 2017 to August 2026 for 413 four-digit SOC unit groups. The ONS assigns each advert to an occupation by matching its job title to a taxonomy. Several months have suppressed or missing cells (all occupations for March 2026, and many for June and July 2025 and June 2026), which we fill by linear interpolation for up to two consecutive months. We sum adverts over twelve-month windows from July to June, which removes seasonality. The base year is July 2021 to June 2022, which precedes the public release of text-to-image systems between April and August 2022 (DALL·E 2, Midjourney, and Stable Diffusion) and of ChatGPT in November 2022. We keep occupations with at least 1,000 adverts in the base year, which leaves 403 occupations.'),
P('For replication we use Eurostat’s experimental statistics on online job advertisements (dataset jvs_a_isco3_r1), which are derived from the Web Intelligence Hub’s classified online job adverts. They give the annual number of online job advertisements by ISCO-08 three-digit occupation and country for 2019 to 2024. We use national-level counts for the countries with data (18), keep country-occupation cells with at least 1,000 adverts in 2022, and obtain 604 cells in 96 occupations in 16 countries. ISCO three-digit occupations are coarser than UK unit groups; for example, graphic designers fall within ISCO 216 (architects, planners, surveyors, and designers). We map the O*NET exposure measures to ISCO three-digit codes through the same crosswalk.'),
P('A third data set is Statistics Canada’s Job Vacancy and Wage Survey (table 14-10-0444), an employer survey that gives the number of job vacancies by NOC 2021 unit group (five-digit) for Canada each quarter from 2015 to 2026. The quarters 2020Q2 and 2020Q3 were not collected, so we cannot compute the twelve-month window ending in June 2021, and cells with small counts are suppressed. We keep the 308 unit groups with at least 1,000 vacancies in the base window (July 2021 to June 2022). Because there is no official concordance between the Canadian and US classifications, we score the 6,144 main-duty statements in the NOC 2021 with the same rubric used for O*NET tasks (3.4% score one or two); unit group exposure is the mean of the score divided by two. We cannot control for LLM exposure in Canada because the Eloundou et al. (2023) scores are mapped to US occupation codes only.'),
H2('4.3 Occupational Exposure to Visual Content Creation'),
P('We classify each of the 18,796 task statements in O*NET (version 29.1) with an LLM. The rubric scores a task 2 if producing or editing visual content (graphics, illustrations, photographs, video, animation, layouts) is central, 1 if visual content is a partial or supporting product, and 0 otherwise; it excludes looking at or inspecting things, writing, and audio production. The full rubric is in Appendix A. In total 859 tasks (4.6%) score 1 or 2, and 180 (1.0%) score 2. Occupation-level exposure is the mean over the occupation’s tasks of the score divided by two. We map O*NET occupations to UK SOC unit groups in two steps: O*NET to ISCO-08 using the crosswalk that O*NET publishes (ESCO occupations carry ISCO codes), and ISCO-08 to UK SOC 2020 using the ONS coding index, which records an ISCO-08 code for each indexed job title. A UK occupation’s exposure is the weighted mean over the ISCO codes attached to it. Exposure is highly skewed: its standard deviation across UK occupations is 0.037, the highest values are for graphic and multimedia designers (8.0 standard deviations above the mean), arts officers and producers, artists, web design professionals, and photographers. We control for occupational exposure to LLMs (Eloundou et al. 2023), mapped in the same way.'),
P('We validated the measures with two human coders, who independently scored the same stratified random sample of 199 task statements (199 of the 200 sampled tasks are used: coder A left one blank). The strata were defined by the LLM score and by a rule-based score: 45 tasks scored 2, 55 scored 1, 40 scored 0 but flagged by the rule-based score, and 60 random tasks scored 0 (sampling weights are used in all estimates). The coders saw only the occupation and the task and used the narrow rubric in Appendix A. Agreement between the coders is low: the design-weighted exact agreement is 0.57, weighted Cohen’s κ is 0.18, the κ for a score of one or more versus zero is 0.20, and the Spearman correlation is 0.22. The coders also differ in how broadly they read the construct: coder A scored 27.6% of all O*NET tasks one or more (3.5% two) and coder B 44.5% (15.3% two), against 4.6% (1.0%) for the narrow LLM score. Both coders counted as visual many tasks that the rubric excludes, such as reading blueprints, examining engravings for quality, and monitoring closed-circuit television.'),
P('By weighted κ, the narrow LLM score agrees with the coders less than the coders agree with each other (0.11 and 0.04, against 0.18), although its rank correlation with coder A (0.52) is higher than the correlation between the coders (0.22). Its weighted κ is 0.11 with coder A (95% bootstrap interval 0.06 to 0.20) and 0.04 with coder B; its binary κ is 0.15 and 0.04; its Spearman correlations are 0.52 and 0.25. Its positives are mostly accepted (coder A scored 80% of them one or more) but it misses most of what the coders counted as visual (sensitivity 0.12 relative to coder A and 0.07 relative to coder B; specificity 0.98 and 0.97). The narrow score is a conservative indicator of visual content production. Because the coders disagree with each other, we cannot treat either as a gold standard, and the reliability of task-level labels for this construct is low regardless of who or what produces them.'),
P('As a transparent benchmark we also score all tasks with a rule-based classifier built from the rubric text (keyword and pattern rules; the code is in the replication repository). Against the LLM score, its task-level F1 for a score of one or more is 0.58 in the first half and 0.46 in the second half of the task list, and its correlation with the LLM score across occupations is 0.88 and 0.78 (436 and 488 occupations). Its Spearman correlation with coder A is 0.36. UK estimates with the rule-based score are close to those with the narrow LLM score (−2.0% in 2025 and −3.4% in 2026 per standard deviation, with the language control).'),
P('We therefore built a second, broad measure that scores how much a task involves working with visual materials and visual or aesthetic output: producing, editing, reading, inspecting, or monitoring images, drawings, video, interfaces, and layouts (rubric in Appendix A). We wrote the rubric after seeing coder A’s pattern on the first half of the sample and evaluated it on the second half (99 tasks). Against coder A on that held-out half the weighted κ is 0.41 and the Spearman correlation 0.66. Coder B did not contribute to the rubric, so the comparison with coder B is an independent check: on all 199 tasks the weighted κ is 0.31 (0.25 on the second half), the binary κ is 0.29 (0.23), and the Spearman correlation is 0.46; against the rounded average of the two coders, the weighted κ is 0.28 and the binary κ 0.33. These values are modest in absolute terms. Relative to the benchmark of agreement between the coders (weighted κ 0.18, Spearman 0.22), the broad score agrees with each coder at least as well as the coders agree with each other, and its Spearman correlation with coder A (0.61) and coder B (0.46) is well above the correlation between them. We apply the broad measure to all 18,796 tasks, with the occupation title shown to the model as the coders saw it; 14.9% of tasks score one or more (2.5% score two). We report results for both measures. Low reliability of an exposure measure biases estimated coefficients toward zero, so some of the smallness of our estimates may reflect measurement error rather than absence of an effect.'),
H2('4.4 Supplementary Data'),
P('We also use the Indeed Hiring Lab job postings index by sector for the United States (47 sectors, daily, 2020–2026) and Eurostat Labour Force Survey employment by NACE two-digit industry for the EU27 (2015–2025). Their results are reported in Section 6.8.'));

add(H1('5. Empirical Strategy'),
H2('5.1 Adoption and Barriers'),
P('We report adoption of generative visual AI and of text generation by size class and sector, and the share of enterprises that considered AI but did not adopt it and cite each barrier. To check whether our exposure measure predicts adoption, we compute sector-level exposure as the employment-weighted mean over ISCO major groups (from the Eurostat Labour Force Survey structure in 2021) and relate adoption to it across sectors and across country-sector cells with country fixed effects, with permutation inference over sector labels. We relate countries’ adoption to the share of considerers who cite each barrier.'),
H2('5.2 Dose-Response Event Study in UK Adverts'),
P('For each occupation *i* and year *t* we compute *y_it* = ln(adverts in year *t*) − ln(adverts in the base year). For each year other than the base year we estimate'),
EQ('y_it = α_t + b_t · z(E_i) + c_t · z(L_i) + μ_g(i),t + ε_it',3),
P('where *E_i* is occupational exposure to visual content creation, *L_i* is occupational exposure to LLMs, both standardized, and *μ_g(i),t* are fixed effects for SOC sub-major groups (two-digit), so that the comparison is between occupations in the same broad group. Standard errors are clustered by SOC minor group (three-digit). We also report specifications with major-group fixed effects and without the language control. Because exposure is a continuous, pre-determined characteristic, *b_t* for years before the base year provides a check on pre-existing differences, although the pre-period contains the COVID shock and cannot be used to test parallel trends cleanly. As an alternative to conventional standard errors we compute randomization p-values by permuting exposure across occupations within sub-major groups (2,000 draws). For the European replication we estimate the same model on country-occupation cells with country-year fixed effects, so that the comparison is between occupations within the same country and year, and with standard errors clustered by ISCO three-digit occupation and, as a check, by two-digit group; randomization p-values permute exposure across occupations within ISCO two-digit groups (1,000 draws). For Canada we estimate the same model on unit groups with fixed effects for NOC major groups or two-digit groups, using the twelve-month windows from July to June, standard errors clustered by NOC three-digit group, and randomization p-values from permuting exposure within two-digit groups (1,000 draws). In Section 6.5 we also compare three occupation groups chosen from occupation labels before looking at outcomes: image and video production (graphic and multimedia designers, artists, photographers and audio-visual operators, web design professionals), creative direction and production, and text production (writers, journalists, editors).'),
H2('5.3 Quality-Requirement Heterogeneity'),
P('To test H2 we split exposure into components by the quality requirement of the creation tasks: *E_low* is the mean over an occupation’s tasks of the creation score divided by two, counting only tasks coded as low quality requirement, and *E_high* is the same for tasks coded high. We estimate equation (3) with both components and test whether the coefficient on *E_low* is more negative than that on *E_high*.'),
H2('5.4 Scaling by Adoption'),
P('To assess whether the observed declines are of a size that adoption could explain, we use equation (2). For selected occupations, we compute the predicted log change from the estimated coefficient and the occupation’s exposure, and divide it by assumed adoption shares of 10% (the EU27 average for firms using AI that generates pictures, video, or audio), 20% (professional, scientific and technical services), and 36% (publishing, film, and broadcasting). The calculation is a stylized plausibility check because adoption among employers of a specific occupation is not observed.'));

add(H2('5.5 Conditional Projection'),
P('The effect among adopters *β* in equation (2) is not identified by our data, so we do not forecast displacement. Instead we ask when a given *β* would become detectable with the design of Section 5.2. We model adoption as logistic: the log-odds of the adoption share rise linearly after 2025 at a scenario-specific rate. The rates are anchored on the Eurostat series: the log-odds of text-generation AI adoption rose by 0.98 between 2023 and 2024, by 0.52 between 2024 and 2025, and by 0.75 per year on average between 2023 and 2025, and those of any AI use by 0.52 per year. We use 0.75 (fast), 0.50 (medium), and 0.25 (slow) per year, starting from 9.6% (all European firms with ten or more employees) or 36.2% (publishing, film, and broadcasting). The predicted coefficient per standard deviation of exposure is *A_t* · *β* divided by the exposure of the most exposed occupation (8.0 standard deviations for graphic and multimedia designers). We call the effect detectable when the coefficient exceeds 1.96 times the standard error of the UK estimate for 2026 (0.017), that is 0.033 per standard deviation, which corresponds to an aggregate log change of 0.27 for that occupation. The calculation is a scenario analysis: it depends on a linear extrapolation of exposure, on an adoption path fitted to few data points, and on adoption among employers of the occupation being close to the sector figure.'),
H1('6. Results'),
H2('6.1 Adoption and Barriers (H1, H3)'),
P('Adoption of generative visual AI is already substantial in Europe. In 2025, 9.6% of EU27 enterprises with ten or more employees used AI that generates pictures, videos, or audio, close to the 8.8% that used text-generation AI. Adoption rises steeply with size and varies by sector (Table 2). Text-generation adoption, which is available for earlier years, rose from 1.3% in 2021 to 2.1% in 2023, 5.4% in 2024, and 8.8% in 2025, and use of at least one AI technology rose from 7.7% to 20.0%. Image recognition, in contrast, grew slowly, from 2.1% to 3.8%. Adoption is therefore early and accelerating, not absent.'),
CAP('**Table 2.** Adoption of AI by size class and sector, EU27, 2025 (percentage of enterprises with 10 or more employees)'),
TBL([3860,2750,2750],[
 ['Group','Picture, video, or audio generation','Text generation'],
 ['All enterprises (10+)','9.6','8.8'],
 ['10–49 employees','8.1','7.0'],
 ['50–249 employees','14.4','14.8'],
 ['250 or more employees','27.9','31.7'],
 ['Information and communication (J)','35.5','42.2'],
 ['Publishing, film, TV, music (J58–J60)','36.2','34.0'],
 ['Professional, scientific, technical (M)','18.7','17.7'],
 ['Construction (F)','4.5','3.2'],
 ['Transportation and storage (H)','4.0','3.9']]),
NOTE('*Note.* Eurostat, enterprise survey on ICT usage, indicators E_AI_TPVSG and E_AI_TNLG. The picture, video, or audio generation indicator is available only for 2025.'),
P('Table 3 reports why firms that considered AI did not adopt it. The most cited reasons are lack of expertise (70%), unclear legal consequences (54%), and data protection and privacy concerns (53%); costs are cited by 38% and the view that AI is not useful by 18%. The pattern is similar across size classes. Firms describe their obstacles as capability and legal or privacy uncertainty, not as lack of usefulness. Two caveats apply: the answers concern AI in general rather than visual generators, and they come only from firms that considered AI, so they do not describe all non-adopters.'),
CAP('**Table 3.** Reasons for not using AI among enterprises that considered it, EU27, 2025 (percentage of such enterprises)'),
TBL([5360,4000],[
 ['Reason','Share citing (%)'],
 ['Lack of relevant expertise','70.3'],
 ['Unclear legal consequences','53.6'],
 ['Data protection and privacy concerns','52.7'],
 ['Difficulties with availability or quality of data','43.5'],
 ['Incompatibility with existing equipment, software, or systems','41.6'],
 ['Costs seem too high','38.4'],
 ['Ethical considerations','24.6'],
 ['AI is not useful for the enterprise','17.8']]),
NOTE('*Note.* Eurostat, enterprise survey on ICT usage, 2025, enterprises with 10 or more employees. Multiple answers allowed.'),
P('Across 23 countries, adoption of picture, video, or audio generation is negatively correlated with the share of considerers citing costs (r = −0.76) and weakly with the share citing unclear legal consequences (r = −0.24) and data protection (r = −0.02), and positively with the share citing lack of expertise (r = 0.46). The last correlation is plausible because countries with more adopters also have more considerers who have run into the difficulty. With 23 countries, these correlations are descriptive only. They offer little support for the view that cross-country differences in legal concerns explain differences in adoption, although legal and privacy concerns are widespread. We therefore treat H3 as partly supported: firms report expertise and legal and privacy uncertainty as the main obstacles, but we cannot show that these obstacles explain who adopts.'),
P('Our exposure measure predicts adoption across sectors, but not specifically. Across the 11 sectors in the survey, sector-level exposure to visual content creation correlates with adoption of picture, video, or audio generation at 0.84, but also with adoption of text generation (0.83) and of image recognition (0.81). In country-sector cells with country fixed effects, a standard deviation of sector exposure is associated with 0.57 log points higher adoption of picture, video, or audio generation (permutation p = 0.006), 0.65 for text generation (p = 0.003), and 0.58 for image recognition (p = 0.005). Sectors with more creative and professional work are more digitally intensive and adopt every kind of AI more. The exposure measure therefore carries a general adoption propensity, which is why the labor-demand analysis controls for language exposure and compares occupations within groups.'),
H2('6.2 UK Adverts: Dose-Response (H1, H4)'),
P('Table 4 and Figure 1 report the coefficients on occupational exposure to visual content creation. With sub-major group fixed effects and the control for LLM exposure, a standard deviation of exposure is associated with 2.4% fewer adverts in the year ending June 2023 relative to the base year (standard error 1.2), 1.1% fewer in 2024 (1.9), 2.1% fewer in 2025 (1.6), and 3.3% fewer in 2026 (1.7). Randomization p-values are 0.47 for 2024, 0.16 for 2025, and 0.03 for 2026. Without the language control the coefficients are larger (−4.3% in 2025 and −5.2% in 2026, standard errors 1.6 and 1.8) because exposure to visual content creation and exposure to LLMs are positively correlated across occupations (0.25). With major-group fixed effects the estimates are between −2.3% and −3.1% in 2023–2026. Results are similar when exposure is the rule-based score (−2.0% in 2025, −3.4% in 2026, randomization p = 0.17 and 0.02).'),
CAP('**Table 4.** UK adverts: coefficient on occupational exposure to visual content creation (per standard deviation), change in log adverts relative to July 2021–June 2022'),
TBL([3160,1275,1275,1275,1275,1100],[
 ['Specification','2021','2023','2024','2025','2026'],
 ['Sub-major FE, LLM control','−0.030 (0.011)','−0.024 (0.012)','−0.011 (0.019)','−0.021 (0.016)','−0.033 (0.017)'],
 ['Sub-major FE, no LLM control','−0.033 (0.011)','−0.031 (0.012)','−0.024 (0.017)','−0.043 (0.016)','−0.052 (0.018)'],
 ['Major FE, LLM control','−0.027 (0.008)','−0.031 (0.010)','−0.023 (0.017)','−0.026 (0.016)','−0.026 (0.015)'],
 ['Randomization p (sub-major FE, LLM control)','','','0.467','0.157','0.029']]),
NOTE('*Note.* 403 UK occupations. Standard errors clustered by SOC minor group in parentheses. Columns are years ending in June; 2022 is the base. Pre-base coefficients for 2018, 2019, and 2020 (sub-major FE, LLM control) are +0.024 (0.014), +0.022 (0.014), and +0.005 (0.012).'),
IMG('data/ons/uk_dose_response_llm.png',576,312),
CAP('**Figure 1.** Coefficient on occupational exposure to visual content creation by year, with 95% confidence intervals (sub-major FE, LLM control)'),
P('Three features limit how far these estimates can be read. First, the coefficient for 2021 is also negative (−0.030, standard error 0.011), which means exposed occupations were lower in 2021 than in the 2022 base. Relative to 2019, exposed occupations lost about 5.2% per standard deviation by 2021, recovered to −2.2% in 2022, and then fell back to between −3.3% and −5.5% in 2023–2026. A substantial part of the post-2022 decline is therefore a reversal of the 2022 recovery from COVID, and the data cannot separate it from an effect of generative AI. Second, the result is fragile: with web design professionals dropped, the 2025 coefficient falls to −0.010 (0.013); with occupations weighted by base-year adverts it is −0.013 (0.016); with the share of tasks scoring one or more as exposure it is −0.017 (0.017). Third, the coefficients do not grow steadily: they are −0.024 in 2023, −0.011 in 2024, −0.021 in 2025, and −0.033 in 2026. A growing effect is what the delayed-adoption view predicts (H4), but the pattern is not monotone and the confidence intervals overlap. The evidence is consistent with a small, growing effect, but it cannot reject no effect.'),
H2('6.3 European Replication'),
P('Table 5 reports the replication in 16 European countries. With country-year fixed effects and the control for LLM exposure, a standard deviation of exposure is associated with 1.6% fewer online adverts in 2023 relative to 2022 (standard error 0.6, randomization p = 0.016) and 1.2% fewer in 2024 (standard error 1.7, p = 0.19). Without the language control the estimates are −3.7% in 2023 (standard error 0.9) and −5.9% in 2024 (standard error 2.1), because exposure to visual content creation and to LLMs are correlated across occupations (0.27). Weighting occupations by their 2022 adverts gives −2.5% for 2024 (standard error 2.2). The pre-2022 coefficients are positive or close to zero (+0.024, +0.008, and +0.011 for 2019, 2020, and 2021), which means that exposed occupations were already falling slightly relative to others before 2022; the pre-2022 trend in the exposure gradient is weak (−0.007 per year, standard error 0.005), and relative to its extrapolation the 2023 and 2024 coefficients are −0.009 (0.007) and +0.002 (0.023). In country-by-country regressions with at least 25 occupations, the slope is negative in 7 of 9 countries in 2023 (median −0.012) and in 8 of 9 in 2024 (median −0.035). Among creative occupations, adverts for architects, planners, surveyors, and designers (ISCO 216, which includes graphic designers) fell by 0.48 log points between 2022 and 2024 against an average of −0.19 across all occupations, while adverts for creative and performing artists (ISCO 265) rose by 0.35. These results point in the same direction as the UK results and are similar in size, but they cover only two post-2022 years, use coarser occupations, and give a precise estimate only for 2023.'),
CAP('**Table 5.** European replication: coefficient on occupational exposure to visual content creation (per standard deviation), change in log online adverts relative to 2022'),
TBL([3560,1160,1160,1160,1160,1160],[
 ['Specification','2019','2020','2021','2023','2024'],
 ['Country-year FE, LLM control','+0.024 (0.014)','+0.008 (0.013)','+0.011 (0.009)','−0.016 (0.006)','−0.012 (0.017)'],
 ['Country-year FE, no LLM control','+0.008 (0.013)','−0.002 (0.013)','+0.008 (0.008)','−0.037 (0.009)','−0.059 (0.021)'],
 ['Randomization p (LLM control)','','','','0.016','0.188']]),
NOTE('*Note.* Eurostat experimental statistics on online job advertisements by ISCO three-digit occupation; 604 country-occupation cells, 96 occupations, 16 countries in 2023. Standard errors clustered by ISCO three-digit occupation in parentheses; 2022 is the base year.'),
H2('6.4 Canadian Replication'),
P('Table 6 reports the estimates for Canada (308 unit groups). With fixed effects for NOC major groups, a standard deviation of exposure is associated with 2.9% fewer vacancies in the year ending June 2023 relative to the base year (standard error 0.7), 2.6% fewer in 2024 (2.2), 3.5% fewer in 2025 (2.4), and 3.4% fewer in 2026 (2.5). Without fixed effects the estimates are −3.7%, −3.4%, −5.2%, and −5.3% (standard errors 0.7, 2.5, 2.9, and 2.6). When the comparison is within NOC two-digit groups, the estimate is −2.2% in 2023 (standard error 0.9, randomization p = 0.10) and not different from zero afterwards (−0.9% in 2024, +1.6% in 2025, and +1.1% in 2026; p between 0.59 and 0.77). The pre-2022 coefficients are close to zero in all specifications (for the specification without fixed effects, −0.005, +0.001, and −0.009 for 2017, 2018, and 2019), but the data do not allow a comparison for 2020 and 2021 because of the missing quarters. Vacancies fell sharply across the Canadian economy: total vacancies in the twelve months ending June 2026 were 47% below those in the base year (a log change of −0.63). Vacancies for graphic designers and illustrators (NOC 52120), one of the most exposed unit groups, fell from 11,610 to 3,910 over the same period (−1.09 log points, a 66% fall), more than the market as a whole. The Canadian estimates therefore agree with the UK and European results on the sign in the first post-2022 year and show no clear pattern afterwards once occupations are compared within narrow groups.'),
CAP('**Table 6.** Canada: coefficient on occupational exposure to visual content creation (per standard deviation), change in log vacancies relative to July 2021–June 2022'),
TBL([2760,1075,1075,1075,1075,1300],[
 ['Specification','2017','2019','2023','2024','2025 / 2026'],
 ['No fixed effects','−0.005 (0.028)','−0.009 (0.017)','−0.037 (0.007)','−0.034 (0.025)','−0.052 (0.029) / −0.053 (0.026)'],
 ['NOC major-group FE','−0.003 (0.035)','−0.008 (0.022)','−0.029 (0.007)','−0.026 (0.022)','−0.035 (0.024) / −0.034 (0.025)'],
 ['NOC two-digit FE','+0.036 (0.038)','+0.007 (0.026)','−0.022 (0.009)','−0.009 (0.025)','+0.016 (0.027) / +0.011 (0.030)'],
 ['Randomization p (two-digit FE)','','','0.100','0.770','0.592 / 0.734']]),
NOTE('*Note.* Statistics Canada, Job Vacancy and Wage Survey, table 14-10-0444; 308 NOC 2021 unit groups. Windows are July to June; the windows ending in June 2020 and June 2021 are unavailable because 2020Q2 and 2020Q3 were not collected. Standard errors clustered by NOC three-digit group in parentheses. No control for LLM exposure.'),
H2('6.5 UK Adverts: Occupation Groups'),
P('The three groups chosen from occupation labels show a similar story with larger numbers (Table 7). Relative to other occupations, adverts for image and video production occupations fell by 0.20 log points in the first year after the base year (randomization p = 0.032) and by 0.38 in the third and fourth (p = 0.011). Creative direction occupations fell by less (−0.11 in the first year and −0.23 in the third; p between 0.15 and 0.27). Text production occupations did not differ from others in the first two years (−0.10 and +0.03) and fell later (−0.33 in the third year, p = 0.046; −0.47 in the fourth, p = 0.008), led by journalists and editors. The decline in image and video production is concentrated in web design professionals, who rank first or third among 405 occupations in the later years (log changes of −1.45 and −1.36 against a comparison median of −0.43 and −0.46); graphic and multimedia designers rank 32nd to 38th (−0.86 and −0.89), and artists and photographers are close to the median. Without web design professionals the third- and fourth-year differences fall to −0.16 and −0.21. Placebo design occupations that image generators do not target (interior designers, fashion and accessories designers, design occupations not elsewhere classified) also fell relative to others (−0.16, −0.20, and −0.06 in the first, third, and fourth years). Between June 2019 and June 2021 the image and video production group had already fallen by 0.32 log points relative to others, and the other two groups by 0.36 and 0.31.'),
CAP('**Table 7.** UK occupation groups: change in log adverts from July 2021–June 2022, group minus other occupations'),
TBL([2660,1675,1675,1675,1675],[
 ['Group (comparison pool)','Jul22–Jun23','Jul23–Jun24','Jul24–Jun25','Jul25–Jun26'],
 ['Image and video production (all)','−0.196 (0.032)','−0.262 (0.047)','−0.378 (0.011)','−0.384 (0.011)'],
 ['Image and video production (SOC 1–3)','−0.217 (0.016)','−0.294 (0.044)','−0.381 (0.008)','−0.389 (0.007)'],
 ['Creative direction (all)','−0.113 (0.225)','−0.159 (0.268)','−0.230 (0.168)','−0.210 (0.224)'],
 ['Creative direction (SOC 1–3)','−0.134 (0.149)','−0.191 (0.211)','−0.233 (0.159)','−0.216 (0.179)'],
 ['Text production (all)','−0.098 (0.279)','+0.029 (0.839)','−0.333 (0.046)','−0.473 (0.008)'],
 ['Text production (SOC 1–3)','−0.119 (0.201)','−0.003 (0.982)','−0.336 (0.049)','−0.478 (0.005)']]),
NOTE('*Note.* Entries are the mean log change of the group minus that of the comparison pool, with randomization p-values in parentheses. Comparison pools: all other occupations with at least 1,000 adverts in the base year (395), and the subset in SOC major groups 1 to 3 (249). Months with missing cells are interpolated. The last column includes the imputed month of March 2026.'),
H2('6.6 Quality-Requirement Heterogeneity (H2)'),
P('H2 is not supported. Exposure to low-quality-requirement creation tasks is associated with declines in 2023 and 2024 (−0.026 and −0.019, standard errors 0.016 and 0.023), but the coefficient is close to zero in 2025 (−0.005) and small in 2026 (−0.017). Exposure to high-requirement tasks has coefficients near zero throughout. The difference between the low and high coefficients is −0.029 (standard error 0.025) in 2023, −0.028 (0.036) in 2024, 0.000 (0.033) in 2025, and −0.014 (0.036) in 2026 (Table 8). The difference has the same sign in the pre-period (−0.046 in 2018 and −0.031 in 2019), and none of the differences is statistically distinguishable from zero. Low- and high-requirement exposure are correlated across occupations (0.48), which limits power. We cannot reject that quality requirements matter, but we find no support for it.'),
CAP('**Table 8.** UK adverts: coefficients on exposure to low- and high-quality-requirement creation tasks (per standard deviation)'),
TBL([1360,2000,2000,2000,2000],[
 ['Year','Low requirement','High requirement','Low minus high','Pre-period or post'],
 ['2018','−0.012 (0.017)','+0.034 (0.019)','−0.046 (0.032)','pre'],
 ['2019','−0.006 (0.017)','+0.026 (0.018)','−0.031 (0.030)','pre'],
 ['2023','−0.026 (0.016)','+0.003 (0.012)','−0.029 (0.025)','post'],
 ['2024','−0.019 (0.023)','+0.009 (0.017)','−0.028 (0.036)','post'],
 ['2025','−0.005 (0.021)','−0.005 (0.018)','0.000 (0.033)','post'],
 ['2026','−0.017 (0.021)','−0.003 (0.020)','−0.014 (0.036)','post']]),
NOTE('*Note.* Sub-major group fixed effects and LLM control; standard errors clustered by SOC minor group. Quality requirement of the 859 creation tasks was coded by an LLM (Appendix A).'),
H2('6.7 Scaling by Adoption'),
P('Table 9 applies equation (2). For graphic and multimedia designers, who have the highest exposure (8.0 standard deviations above the mean), the coefficients imply a predicted log change of −0.17 in 2025 and −0.26 in 2026 (specification with the language control). If 36% of employers of this occupation had adopted, which is the EU27 rate in publishing, film, and broadcasting, the implied effect among adopters would be −0.46 and −0.73 log points, a fall in adverts of 37% to 52% among adopters. At the EU27 average adoption rate of 10% the implied effect among adopters is −1.7 and −2.6 log points, which means 81% to 93% fewer adverts. The lower end of the 95% interval is larger still. Without the language control the implied numbers are about twice as large. These magnitudes are implausibly large for substitution among adopters, who would have to cut hiring for the occupation sharply and persistently within a few years of a technology’s release, while still adopting less than the average firm in the professions that employ designers. Either adoption among employers of these occupations is far higher than the sector averages in Table 2, or most of the observed decline is not due to adoption of generative visual AI. The first reading is possible because designers are concentrated in sectors with higher adoption and in small firms that buy tools off the shelf. The second reading is consistent with the COVID-era pattern in Section 6.2 and with the decline of design occupations that image generators do not target.'),
CAP('**Table 9.** Implied effect among adopters for graphic and multimedia designers (log points)'),
TBL([3160,1550,1550,1550,1550],[
 ['Quantity','Adoption 10%','Adoption 20%','Adoption 36%','Predicted aggregate'],
 ['2025, point estimate','−1.67','−0.84','−0.46','−0.17'],
 ['2025, lower end of 95% CI','−4.14','−2.07','−1.15','−0.41'],
 ['2026, point estimate','−2.62','−1.31','−0.73','−0.26'],
 ['2026, lower end of 95% CI','−5.25','−2.62','−1.46','−0.52']]),
NOTE('*Note.* Predicted aggregate log change = coefficient per standard deviation × 8.0 standard deviations (sub-major FE, LLM control). Implied effect among adopters = predicted aggregate divided by the adoption share. Stylized calculation; adoption among employers of the occupation is not observed.'),
H2('6.8 Supplementary Evidence: US Sectors and European Employment'),
P('US sector postings (Indeed) show a similar relative decline in the sectors Arts & Entertainment, Media & Communications, and Marketing, chosen before looking at outcomes. Relative to the other 44 sectors, the log change in postings from January–March 2022 to October 2022–March 2023 was −0.23 (randomization p = 0.018), and by October 2024–March 2025 it was −0.32 (p = 0.063). The same sectors had risen 0.11 more than others in the year before the base period (p = 0.25). They were not the largest decliners: between the base and October 2024–March 2025 Marketing ranked fifth, Media & Communications sixth, and Arts & Entertainment fifteenth of 47 by size of fall, while Software Development ranked first and Data & Analytics second. In European Labour Force Survey data, employment in video and film production (NACE J59), advertising (M73), and other professional, scientific and technical activities including design and photography (M74) rose between 2019–2021 and 2023–2025 by 0.13, 0.11, and 0.15 log points against a median of 0.04 across 88 industries. The creative industries gained 0.09 log points relative to all other industries (randomization p = 0.20) and 0.04 relative to knowledge-service industries (p = 0.52). Neither source separates visual generation from the technology slowdown, and employment and adverts measure different things.'),
H2('6.9 Broad Exposure Measure'),
P('Table 10 reports the dose-response estimates with the broad measure of exposure to visual materials. In the UK, with sub-major group fixed effects and the control for LLM exposure, a standard deviation of exposure is associated with 2.1% fewer adverts in the year ending June 2023 relative to the base year (standard error 1.5), 1.0% fewer in 2024 (2.2), 1.8% fewer in 2025 (2.0), and 2.7% fewer in 2026 (2.1); randomization p-values are 0.54, 0.25, and 0.09 for 2024, 2025, and 2026. With major-group fixed effects the estimates are −2.6% to −3.0% in 2023–2026 with standard errors of 1.1 to 1.8. The coefficients before the base year are positive and larger than for the narrow measure (+4.7% in 2018 and +4.2% in 2019, with standard errors of 1.7 and 1.5), which means that occupations with high exposure to visual materials were rising relative to others before 2022 and then lost that advantage. In the European data the broad measure gives −0.9% in 2023 (standard error 0.7, randomization p = 0.27) and −0.4% in 2024 (1.5, p = 0.77), against positive pre-2022 coefficients (+4.0% in 2019, +2.3% in 2020, +1.9% in 2021). The country-by-country slopes are negative in 5 of 9 countries in both years. With the broad measure the post-2022 estimates are therefore smaller and less precise than with the narrow measure, and the pre-2022 pattern of relative growth is stronger, so a larger part of the post-2022 pattern can be read as the reversal of an earlier trend.'),
CAP('**Table 10.** Broad exposure measure: coefficient on exposure to visual materials (per standard deviation), change in log adverts relative to the base year'),
TBL([2560,1100,1100,1100,1100,1100,1300],[
 ['Sample','2018/19','2020/21','2023','2024','2025','2026'],
 ['UK: sub-major FE, LLM control','+0.047 / +0.042','−0.018 (2021)','−0.021 (0.015)','−0.010 (0.022)','−0.018 (0.020)','−0.027 (0.021)'],
 ['UK: randomization p','','','','0.543','0.253','0.091'],
 ['Europe: country-year FE, LLM control','+0.040 (2019)','+0.023 / +0.019','−0.009 (0.007)','−0.004 (0.015)','',''],
 ['Europe: randomization p','','','0.272','0.774','','']]),
NOTE('*Note.* Broad measure of exposure to visual materials (Section 4.3). UK: 403 occupations; Europe: 604 country-occupation cells in 96 occupations and 16 countries. Standard errors in parentheses; for the pre-2022 columns they are 0.017 and 0.015 (UK, 2018 and 2019), 0.015 (UK, 2021), 0.017 (Europe, 2019), and 0.019 and 0.010 (Europe, 2020 and 2021). The UK base year is July 2021–June 2022 and the European base year is 2022.'),
H2('6.10 Summary of Evidence Against the Hypotheses'),
P('H1 is supported in a limited sense: adoption is substantial and rising, while estimated labor-demand effects are small, imprecise, and partly a reversal of earlier trends; the scaling exercise shows that the largest observed declines are too large for current adoption to explain through substitution. H2 is not supported. H3 is partly supported: firms cite expertise and legal and privacy uncertainty far more than usefulness, but cross-country variation in these concerns does not clearly explain adoption. H4 is weakly supported: in the UK the coefficients are most negative in 2026 and in Europe without the language control they grow from 2023 to 2024, but in both the pattern is not clearly monotone and in the UK the effect cannot be separated from the pre-existing pattern. The European replication confirms the sign of the result but not that it is new: the European gradient was already moving in the same direction before 2022, and the replication covers only two post-2022 years. In Canada the first post-2022 year agrees in sign, and later years show no clear pattern within narrow occupation groups. With the broad exposure measure the post-2022 estimates are smaller and less precise and the pre-2022 coefficients are positive and larger, so the evidence for displacement is weaker still.'));

add(H2('6.11 Projection: When Could Displacement Become Detectable?'),
P('Table 11 reports the share of employers that would have to adopt for the effect to reach the detection threshold, and the first year in which each adoption scenario gets there. The threshold requires adoption times *β* to reach −0.27. If demand among adopters falls by 39% (*β* = −0.5), adoption must reach 53%. Starting from the EU27 average of 9.6%, this happens in 2029 under fast diffusion, 2030 under medium diffusion, and 2035 under slow diffusion. Starting from the 36% adoption observed in publishing, film, and broadcasting, it happens in 2026, 2027, and 2028. If demand among adopters falls by 26% (*β* = −0.3), adoption must reach 89%, which occurs between 2031 and 2034 for the average firm under fast and medium diffusion and between 2029 and 2031 in media-related sectors, and not within the horizon under slow diffusion. If demand falls by 10% (*β* = −0.1), the threshold would require adoption above 100%: such an effect would not be detectable with this design at any adoption level. If demand among adopters fell by 55% (*β* = −0.8), detection would occur in 2028 to 2032 for the average firm and already in 2025 in media-related sectors. The present UK coefficient for 2026 (−0.033) is at the detection threshold, so it is consistent either with such a large effect among adopters in a high-adoption sector or with a decline that is not caused by adoption, as Section 6.7 suggests.'),
CAP('**Table 11.** Adoption needed for detectability and first year of detectability by scenario'),
TBL([2960,1600,1600,1600,1600],[
 ['Effect among adopters β (demand change)','Adoption needed','Fast diffusion (all firms / media)','Medium diffusion (all firms / media)','Slow diffusion (all firms / media)'],
 ['−0.1 (−10%)','above 100%','not detectable / not detectable','not detectable / not detectable','not detectable / not detectable'],
 ['−0.3 (−26%)','89%','2031 / 2029','2034 / 2031','after 2035 / after 2035'],
 ['−0.5 (−39%)','53%','2029 / 2026','2030 / 2027','2035 / 2028'],
 ['−0.8 (−55%)','33%','2028 / 2025','2029 / 2025','2032 / 2025']]),
NOTE('*Note.* Adoption starts from 9.6% (all firms with ten or more employees, EU27, 2025) or 36.2% (publishing, film, and broadcasting) and follows a logistic path with log-odds slopes of 0.75, 0.50, and 0.25 per year. Detection: predicted coefficient per standard deviation of exposure below −0.033 (1.96 times the UK standard error of 0.017) for an occupation with exposure 8.0 standard deviations above the mean. The medium-diffusion path for all firms reaches 56% adoption in 2030.'),
P('The projection yields criteria that later data can use to falsify it. Under medium diffusion from the average-firm baseline, adoption is 32% in 2028. A coefficient per standard deviation of exposure above −0.01 in 2028 in the UK and European data would then imply that *β* is above about −0.25 for typical adopters (a demand reduction below roughly 22%). A coefficient at or below −0.035 in 2030, when adoption is 56%, would be consistent with *β* of about −0.5 or less. These criteria are conditional on the adoption path; if adoption is slower, the same coefficients imply larger values of *β*.'),
H1('7. Discussion'),
H2('7.1 Contributions'),
P('The paper offers a model that splits the labor-demand effect of a technology into adoption and the net effect among adopters, and uses it to bound what adoption can explain. It provides direct survey evidence on obstacles to adoption (expertise and legal and privacy uncertainty) and shows that adoption of generative visual AI is already substantial. It links task-level data on visual content creation to occupation-level hiring data across countries in an open, reproducible pipeline, and shows that estimated effects are small, have the same sign in a European replication, and are sensitive to a few occupations in the UK. For research on delayed diffusion, the results show how adoption statistics and labor outcomes can diverge: adoption is high enough to signal an early phase, while labor outcomes have not yet moved in a way that can be attributed to the technology.'),
P('Our estimates for employers’ standing occupations are smaller than the declines of about 17% in image-creation job posts and about 21% in writing and coding posts reported for a freelance platform (Demirci et al. 2025). This fits the delayed-adoption view that substitution appears first in spot markets for outsourced tasks and later inside organizations. We have not tested that explanation, and the data sets differ in measure, occupations, and period.'),
H2('7.2 Implications'),
P('For managers, the evidence on barriers suggests that the binding constraints on adopting generative visual AI are organizational (expertise, review and legal compliance, and data protection) rather than the capability of the tools. Investing in review capacity and in clear policies on copyright and personal data may therefore matter more than waiting for better models. For policy makers, small effects on hiring so far do not show that they will stay small. If adoption keeps rising at the pace seen for text generation, effects on hiring could appear within a few years, and monitoring should use occupation-level data that distinguish production roles from direction roles. For information systems research, the paper points to the assimilation gap as a way to read generative AI: counting adopters is not the same as measuring how far tasks have shifted.'),
H2('7.3 Limitations'),
P('The identification is weak. Exposure is a continuous measure, but the pre-period contains the COVID shock and the post-2022 pattern resembles a reversal of the 2022 recovery; the coefficients are small and rely on a few occupations. We do not observe adoption among the employers of each occupation, so the scaling exercise is a stylized check. The barriers come from a European survey about AI in general, whereas the hiring data are for the United Kingdom, so we link them only through sector averages, and the Eurostat indicator for generative visual AI exists for one year, so we cannot show its growth. The European replication uses experimental statistics for 16 countries and ISCO three-digit occupations, has only two post-2022 years, and ends in 2024. The Canadian data are an employer survey of vacancies rather than job adverts, lack two quarters in 2020, use exposure scored from NOC duty statements without a control for LLM exposure, and give imprecise estimates after 2023.'),
P('The exposure measures are LLM-coded. The narrow measure agrees poorly with two human coders (weighted κ 0.11 and 0.04), and the coders agree poorly with each other (0.18), so the reliability of the construct at task level is low. The broad measure agrees moderately (0.31 to 0.41), at least as well as the coders agree with each other, but its rubric was shaped by one coder. Low reliability attenuates estimated effects. A rule-based score gives results similar to the narrow measure. The mapping from O*NET to UK occupations goes through ISCO-08 and is approximate.'),
P('The ONS series is experimental and has missing months that we interpolate. Adverts measure hiring intent, not employment, and substitution may occur through hours, outsourcing, or freelancing, which adverts cannot show. Release dates refer to public availability and are approximate. The projection depends on assumptions about the adoption path, the linearity of exposure, and adoption among employers of each occupation, and it does not identify the effect among adopters. Finally, the model abstracts from changes in the quality and variety of assets and from price effects.'),
H1('8. Conclusion'),
P('Generative visual AI is being adopted, with about one in ten European firms using it in 2025 and about one in three in publishing, film, and broadcasting, and firms that have not adopted point to expertise and legal and privacy uncertainty as the main obstacles. In UK job adverts, occupations with more visual content creation show small declines after 2022 that are hard to separate from a COVID-era pattern, that are not concentrated in low-quality-requirement tasks, and that are too large in the most exposed occupations for current adoption to explain through substitution. The evidence fits an early-adoption phase in which displacement is not yet detectable, but it does not show that displacement will arrive. Under the model, a demand reduction of about 40% among adopters would become detectable in data of this kind around 2029 to 2030 if adoption follows its recent path, and a reduction of 10% would not become detectable at any adoption level. Testing the delayed-displacement view requires firm-level data that link adoption to hiring, a validated task measure, and several more years of data.'));

add(H1('Data, Code, and Generative AI Statements'),
P('*Data and code availability.* All data come from public sources (Eurostat, ONS, Statistics Canada, O*NET, Indeed Hiring Lab). The code, prompts, LLM-coded task scores, and human coding files needed to reproduce every table and figure are available in an anonymized replication repository [anonymized link to be provided at submission].'),
P('*Use of generative AI.* Large language models were used as measurement instruments to code O*NET and NOC task statements, as described in Section 4.3 and Appendix A. A generative AI assistant was also used to help write analysis code and to draft and edit the manuscript text. [The authors reviewed all results, text, and code and take responsibility for the content; authors to confirm this statement before submission.]'),
new Paragraph({children:[],pageBreakBefore:true}),H1('Appendix A. Rubrics Used for LLM Coding'),
P('*Visual content creation score (applied to all 18,796 O*NET task statements; model: [MODEL NAME AND VERSION], accessed through the OpenRouter API; temperature 0; 20 tasks per request).* Score each task for how much it involves producing or editing visual content: creating, designing, drawing, illustrating, photographing, filming, animating, retouching, editing, laying out, or rendering images, graphics, video, or other visual media. 2 = producing or editing visual content is central. 1 = visual content is a partial or supporting product of the task. 0 = the task does not involve producing or editing visual content. Technical drawings and engineering blueprints count only when the task is about producing them as drawings or graphics. Reading, inspecting, or looking at things does not count. Writing and audio production do not count.'),
P('*Broad visual-materials score (applied to all 18,796 tasks, with the occupation title shown).* Score how much the task involves visual materials and visual or aesthetic output. 2 = producing, designing, or editing visual or aesthetic output is the core of the task (graphics, illustration, photography, video, animation, web or interface design and development, layouts and patterns, set, costume, hair or make-up appearance, performing for camera or stage). 1 = the task works with visual materials without producing visual or aesthetic output as its core: reading, studying, or interpreting blueprints, drawings, maps, or images; producing engineering or technical drawings and documentation; visually inspecting or monitoring; preparing charts, slides, or visual aids as part of a broader duty. 0 = the task does not involve visual materials or visual output. Tasks are not scored merely because the worker must see to do them.'),
P('*Quality-requirement score (applied to the 859 tasks scoring 1 or 2).* Rate how demanding the acceptance standard is for the visual output of the task. 0 = low: generic, routine, draft, or internal-use visuals where good-enough output is acceptable and errors are cheap to fix. 1 = medium: visuals for external audiences or clients where polish matters but several acceptable solutions exist and review is routine. 2 = high: brand-defining, safety-critical, legally or regulatorily sensitive, technically exact, or signature or original artistic work where errors are costly or the particular creator’s judgment is central.'),
P('The prompts and all code are in the anonymized replication repository.'));

add(new Paragraph({children:[],pageBreakBefore:true}),H1('References'),
REF('Acemoglu, D., Autor, D., Hazell, J., and Restrepo, P. 2022. Artificial intelligence and jobs: Evidence from online vacancies. *Journal of Labor Economics* 40(S1):S293–S340.'),
REF('Agrawal, A., Gans, J., and Goldfarb, A. 2018. *Prediction Machines: The Simple Economics of Artificial Intelligence*. Boston: Harvard Business Review Press.'),
REF('Bresnahan, T. F., and Trajtenberg, M. 1995. General purpose technologies: “Engines of growth”? *Journal of Econometrics* 65(1):83–108.'),
REF('Brynjolfsson, E., Li, D., and Raymond, L. 2025. Generative AI at work. *The Quarterly Journal of Economics*.'),
REF('Brynjolfsson, E., Rock, D., and Syverson, C. 2021. The productivity J-curve: How intangibles complement general purpose technologies. *American Economic Journal: Macroeconomics* 13(1):333–372.'),
REF('David, P. A. 1990. The dynamo and the computer: An historical perspective on the modern productivity paradox. *American Economic Review* 80(2):355–361.'),
REF('Demirci, O., Hannane, J., and Zhu, X. 2025. Who is AI replacing? The impact of generative AI on online freelancing platforms. *Management Science* 71(10):8097–8108.'),
REF('Eloundou, T., Manning, S., Mishkin, P., and Rock, D. 2023. GPTs are GPTs: An early look at the labor market impact potential of large language models. arXiv:2303.10130.'),
REF('Eurostat. ICT usage in enterprises: artificial intelligence by size class of enterprise (isoc_eb_ai) and by NACE Rev. 2 activity (isoc_eb_ain2); online job advertisements by occupation (jvs_a_isco3_r1, experimental statistics based on the Web Intelligence Hub); Labour Force Survey employed persons by occupation and economic activity (lfsa_eisn2) and by detailed economic activity (lfsa_egan22d). Accessed via the Eurostat dissemination API.'),
REF('Felten, E., Raj, M., and Seamans, R. 2021. Occupational, industry, and geographic exposure to artificial intelligence. *Strategic Management Journal* 42(12):2195–2217.'),
REF('Fichman, R. G., and Kemerer, C. F. 1999. The illusory diffusion of innovation: An examination of assimilation gaps. *Information Systems Research* 10(3):255–275.'),
REF('Gopal, A., Li, J., Riemer, K., Sarker, S., Singh, P. V., Susarla, A., Bichler, M., and Thatcher, J. B. 2025. Inventing with machines: Generative AI and the evolving landscape of IS research. *Information Systems Research* 36(4):1949–1967.'),
REF('Hui, X., Reshef, O., and Zhou, L. 2024. The short-term effects of generative artificial intelligence on employment: Evidence from an online labor market. *Organization Science* 35(6):1977–1989.'),
REF('Indeed Hiring Lab. Job Postings Index, by sector, United States (data repository hiring-lab/job_postings_tracker). Creative Commons Attribution 4.0 International License.'),
REF('Kim, S., Jin, G. Z., and Lee, E. 2026. Does generative AI crowd out human creators? Evidence from Pixiv. NBER Working Paper 34733.'),
REF('National Center for O*NET Development. O*NET Database, version 29.1 (Task Statements; Abilities) and crosswalk of ESCO occupations to O*NET-SOC. Creative Commons Attribution 4.0 International License.'),
REF('Office for National Statistics. Labour demand volumes by Standard Occupation Classification (SOC 2020), UK: January 2017 to August 2026 (experimental statistics based on Textkernel data); and SOC 2020 Volume 2: the coding index. Open Government Licence.'),
REF('Statistics Canada. Job vacancies and average offered hourly wage by occupation (unit group), quarterly, unadjusted for seasonality, table 14-10-0444; and National Occupational Classification (NOC) 2021 Version 1.0, elements file. Statistics Canada Open Licence.'),
REF('Webb, M. 2020. The impact of artificial intelligence on the labor market. SSRN working paper 3482150 (revised January 2020).'),
REF('Zhou, E., and Lee, D. 2024. Generative artificial intelligence, human creativity, and art. *PNAS Nexus* 3(3):pgae052.'));

const doc=new Document({
 styles:{default:{document:{run:{font:F,size:24}}},paragraphStyles:[
  {id:'Heading1',name:'Heading 1',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:0}},
  {id:'Heading2',name:'Heading 2',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,font:F},paragraph:{outlineLevel:1}},
  {id:'Heading3',name:'Heading 3',basedOn:'Normal',next:'Normal',quickFormat:true,run:{size:24,bold:true,italics:true,font:F},paragraph:{outlineLevel:2}}]},
 sections:[{properties:{page:{size:{width:12240,height:15840},margin:{top:1440,bottom:1440,left:1440,right:1440}}},
  footers:{default:new Footer({children:[new Paragraph({alignment:AlignmentType.CENTER,children:[new TextRun({children:[PageNumber.CURRENT],font:F,size:20})]})]})},
  children:body}]});
Packer.toBuffer(doc).then(b=>fs.writeFileSync('ISR_Submission_Early_Adoption_Delayed_Displacement.docx',b));
