const { P, PN, H1, H2, H3, EQ, BOX, table } = require('./lib');
const S = require('../../runs/summary.json');
const T = require('../../runs/paper_tables.json');
const R = ['qwen05', 'smol360', 'qwen15'];
const f2 = x => x.toFixed(2), usd = x => '$' + Math.round(x).toLocaleString('en-US');
const rg = (a, d = 0) => { const lo = Math.min(...a).toFixed(d), hi = Math.max(...a).toFixed(d); return lo === hi ? lo : `${lo} to ${hi}`; };
const cfgk = (r, c) => S[r].sla500.configs.find(x => x.config === c);
const red = R.map(r => 100 * (1 - cfgk(r, 'L2').k_star / cfgk(r, 'none').k_star));
const fb = R.map(r => 100 * S[r].false_block_share_of_good.L2);
const dsr = R.map(r => S[r].dependence_stats.ratio_no_routing.point), dsrr = R.map(r => S[r].dependence_stats.ratio_with_routing.point);
const none3 = R.map(r => 100 * S[r].burst.poisson_checks.none.p_exceed_k_star_observed), none44 = R.map(r => 100 * S[r].burst044.poisson_checks.none.p_exceed_k_star_observed);
const best = R.flatMap(r => [100 * S[r].burst.poisson_checks['L1+L2'].p_exceed_k_star_observed, 100 * S[r].burst044.poisson_checks['L1+L2'].p_exceed_k_star_observed]);
const meanPlan = R.flatMap(r => [...Object.values(S[r].sla500.poisson_checks), ...Object.values(S[r].burst.poisson_checks)].map(v => 100 * v.p_exceed_mean_capacity_observed));
const tcr = S.failure.typed_capacity.scenarios.map(x => 100 * (x.all_classes.k_typed / x.all_classes.k_naive_poisson - 1));

const intro = [
  H1('1. Introduction'),
  P(`Large language models (LLMs) now sit inside customer-facing and decision-support information systems, where an ungrounded answer is better understood as a service incident than as a lapse in output quality. A support assistant that invents a refund policy, or a drafting tool that cites a court decision that does not exist, creates work for someone: the answer has to be found, corrected, and sometimes explained to a customer or a regulator. Research on managing AI in organisations has so far concentrated on adoption, governance, and the division of tasks between people and machines (Berente et al. 2021; Raisch and Krakowski 2021). The operational question that follows deployment has received much less formal attention. If hallucinations arrive at random, how much human triage and verification capacity should an organisation keep in reserve, and how many automated guardrail layers should it place in front of the model?`),
  P(`Practitioners tend to answer with two heuristics. The first provisions triage capacity at the mean incident load. The second credits every additional guardrail layer with its stand-alone effectiveness, as if layers failed independently, so that three layers that each catch 63% of hallucinations are assumed to leave about 5%. Both are easy to apply and both fail in predictable ways. Provisioning at the mean leaves even a perfectly Poisson workload short on between a quarter and a half of days once the rate reaches one event per day (Section 3.1), and in our replays it was exceeded on ${rg(meanPlan)}% of days. The independence product, as we show, is an optimistic bound whenever layers tend to fail on the same inputs.`),
  P(`We ask three questions. First, how should standby capacity for human-handled hallucinations be set, and how does the requirement change when daily demand is more variable than a Poisson process allows? Second, how do guardrail layers change the requirement once their dependence and their costs in latency, false blocks and failures are taken into account, and how many layers are worth having? Third, do the counting-process assumptions behind the answers hold up on public data from comparable real streams?`),
  P(`We address these questions in the design-science tradition (Hevner et al. 2004; Gregor and Hevner 2013). The artifact is a capacity-planning method. It sets standby capacity at a quantile of the daily count of human-handled incidents, corrects that quantile for over-dispersion, bounds the residual rate of a guardrail cascade without assuming independence, and describes the several kinds of failure that an LLM service produces with different counting processes. We ground the method in a formal model (Section 3) and evaluate it (Sections 4 and 5) on the measured outputs of three small open models that answered the same 300 SQuAD 2.0 questions through three executed guardrail layers. Arrival times are simulated, with day-to-day variability informed by public traces of an LLM service, of LLM providers' incidents, of company ticket systems and of court decisions involving fabricated citations. None of these traces, with the partial exception of the court-case database, records hallucinations, and we know of no public operator log that does.`),
  P(`Three findings stand out. One task-specific verifier delivered most of the benefit of the cascade: it reduced required capacity by ${rg(red)}%, but it also blocked ${rg(fb)}% of correct answers, and a routed LLM judge did not demonstrably pay for itself under a two-second fail-open timeout. The share of hallucinations that passed two layers was ${rg(dsr, 1)} times the independence prediction when both layers saw every answer and ${rg(dsrr, 1)} times when routing hid some answers from the second layer, although the intervals are wide and, for two of the three generators, include one in the first case. And mild day-to-day variation in demand (a coefficient of variation between 0.3 and 0.44) was enough for a Poisson-sized plan to be exceeded on ${rg([...none3, ...none44])}% of days without guardrails and on ${rg(best)}% of days with the best cascade, against a target of 5%.`),
  P(`The paper makes four contributions, and we try to be clear about which parts apply known results. The quantile rule for staffing and the negative-binomial correction for over-dispersion are classical (Whitt 2007; Cameron and Trivedi 1998). Our contribution there is to apply them to the arrival stream of human-handled LLM incidents, to show how over-dispersion and thinning by guardrails enter the requirement (Propositions 2 and 3), and to test the counting-process assumptions on public streams. Second, we restate the multiplicative guardrail formula as the independence special case of Fréchet-type bounds on a cascade of arrival rates (Proposition 4). Dependence between defence layers has been measured on real stacks (Alotaibi et al. 2026) and the independence product is known to over-credit redundancy (Bhardwaj et al. 2026); we add a measurement for hallucination-grounding layers with uncertainty intervals and carry the correction through to the capacity decision. We also show that, once capacity is integer-valued, cost is generally not unimodal in the number of layers, with comparative statics in the ratio of labour to compute cost (Proposition 5). Third, we replace the single-Poisson description of "all failures" with a typed model in which hallucinations, provider incidents, serving failures and human service each follow the process that fits their mechanism (Proposition 6). Fourth, we report measured guardrail performance, layer dependence and latency together with fits of the typed model to public traces.`),
  P(`In the terms of Gregor and Hevner (2013), the contribution is closest to an exaptation: known solutions are carried into a new problem domain, and a few new results (Propositions 3, 5 and 6) follow from the structure of that domain. To our knowledge, earlier work has not combined measured guardrail performance, an incident-count model with dispersion and clustering, and a quantile-based capacity decision in one evaluated framework, although each ingredient has precedents (Section 2). The evaluation has clear limits, which we set out in Section 6.3: arrivals are simulated, the models are small, and the task is extractive question answering. The numbers should therefore be read as an illustration of the method, and the method, together with its diagnostics, is what we expect to transfer.`),
  P(`The remainder of the paper is organised as follows. Section 2 reviews related work. Section 3 develops the model. Section 4 describes the empirical design and Section 5 reports the findings. Section 6 discusses contributions, implications and limitations, and Section 7 concludes. Proofs, data details and supplementary tables are in the appendices.`),
];

const related = [
  H1('2. Background and Related Work'),
  H2('2.1 Managing AI and human oversight'),
  P(`Berente et al. (2021) argue that AI creates managerial problems that earlier information technologies did not, because of its autonomy, its capacity to learn and its inscrutability. A related stream examines how organisations divide work between people and AI systems, and describes a tension between automating tasks and augmenting human judgement (Raisch and Krakowski 2021). Human review of AI output sits at the centre of both. Yet this work says little about how large the human reserve needs to be, which is a question of quantities (headcount, response time, risk of overload) that depend on how failures arrive.`),
  H2('2.2 Hallucination and its mitigation'),
  P(`Hallucination, the generation of content that is wrong or not supported by the source, is documented as a pervasive property of neural text generation (Ji et al. 2023). Mitigation work includes retrieval grounding (Lewis et al. 2020), consistency checks based on repeated sampling (Manakul et al. 2023), safeguard classifiers (Inan et al. 2023) and verification by an LLM acting as judge (Zheng et al. 2023). This literature evaluates detectors by accuracy. It does not ask how a detector's accuracy translates into the human capacity an organisation must hold, which is the translation we attempt.`),
  H2('2.3 Capacity under random demand'),
  P(`Sizing service capacity from the quantile of a Poisson count is standard practice in service operations (Whitt 2007), and time-varying demand is handled by piecewise-stationary staffing (Green et al. 2007). Empirical work on call centres finds that arrivals are Poisson only conditional on a random, day-specific rate, so that daily counts are over-dispersed (Brown et al. 2005), and count-data econometrics supplies the negative-binomial remedy (Cameron and Trivedi 1998). We import these tools into a new arrival stream and test whether the same caveats apply.`),
  H2('2.4 Queueing and counting-process models of AI work'),
  P(`Several recent papers model human review of AI output. They include a Poisson escalation model with Erlang-C staffing for agent escalations (Besanson 2026), an M/G/1 model of reviewing AI drafts (Bartolucci and Vivo 2026) and a fluid-limit analysis of routing between an LLM judge and human review (Lin and Zhang 2026). These papers use mean-based stability or waiting-time criteria and assume, rather than test, Poisson arrivals. We size capacity at a quantile of the count distribution and test the arrival assumptions. On the failure side, a public-health-style analysis of AI incident databases finds strong over-dispersion relative to Poisson in counts of vehicle and deepfake incidents (Abraham et al. 2026), and a Markov reliability model of LLM agents reduces to the Goel-Okumoto software-reliability model when failures are rare (Tran-Truong and Le 2026). Neither concerns hallucinations or guardrail bypass, and neither applies time-rescaling tests or capacity sizing.`),
  H2('2.5 Layered defences'),
  P(`The multiplicative formula for the residual rate of independent safeguards is standard in reliability engineering, and it over-credits redundancy when failures are positively associated (Esary et al. 1967). For LLM defence stacks, Alotaibi et al. (2026) measure positive failure correlation between seven defence layers (φ between 0.30 and 0.75 on JailbreakBench) and call the product a lower bound that no real stack attains. Bhardwaj et al. (2026) give a Fréchet-Hoeffding sandwich and find high co-failure among same-model components. Our dependence results are additional evidence in a different setting, hallucination-grounding layers, and not a first demonstration.`),
  H2('2.6 Gap'),
  P(`Prior work therefore treats the pieces separately: arrival models for AI incidents, queueing for human review, measured layer dependence, and the cost and latency of guardrails. We combine them for LLM hallucination operations and evaluate the combination on measured outputs and public traces. The literature on LLM guardrails moved quickly during 2026, our search was not exhaustive, and similar work may exist.`),
];

const model = [
  H1('3. Model'),
  H2('3.1 Arrivals of critical hallucinations'),
  P(`Consider a service that receives queries at a time-varying rate Λ(t) with a daily cycle. Each query independently yields a hallucination, meaning an answer that is wrong or unsupported, with probability p₀, and a guardrail cascade may block some of these. We make three assumptions that are strong and that we revisit in Section 6.3. First, queries are independent given the arrival intensity. Second, every hallucination that passes the whole cascade is detected and becomes exactly one human-handled event that uses one unit of triage capacity. We call such an event a *critical hallucination* and write q ≤ p₀ for the probability that a query produces one. Third, a unit of capacity clears one critical event per day.`),
  P(`Under these assumptions the thinning theorem (Kingman 1993) implies that critical hallucinations form a non-homogeneous Poisson process (NHPP) with intensity qΛ(t). Let X_d be the number of events on day d, with mean λ = q∫Λ(t)dt taken over the day. Then X_d follows a Poisson(λ) distribution whatever the within-day shape of Λ; that shape matters only for hourly staffing, where the requirement for hour h is the quantile of Poisson(λ_h). The detection assumption deserves emphasis. If only a fraction δ of the hallucinations that survive is ever noticed and triaged, the event rate is δλ and, by Proposition 3, the dispersion index becomes 1 + δλc². The capacities we report are therefore upper bounds that hold for δ = 1, and detection is itself a point of failure that the model does not cover.`),
  P(`Inter-arrival times are exponential only if the rate is constant. Under the NHPP, the time-rescaled gaps Λ̂(t_i) − Λ̂(t_{i−1}) are independent Exp(1) variables (the time-rescaling theorem; Ogata 1988; Daley and Vere-Jones 2003), which gives a goodness-of-fit test that we use in Section 5. If the daily rate is itself random, Λ_d = λM with E[M] = 1 and Var(M) = c², the daily count is a mixed Poisson variable with Var(X_d) = λ + λ²c² = λφ, where φ = 1 + λc² is the dispersion index. This is the Cox, or doubly stochastic, alternative to the pure Poisson null (Cox 1955; Cox and Isham 1980).`),
  P(`For a reliability target α, the capacity requirement is the generalised inverse of the daily-count distribution:`),
  EQ('k*(α, λ) = min { k ∈ ℕ₀ : P(X_d ≤ k) ≥ α }', '1'),
  BOX('Proposition 1 (Poisson capacity).', `Let X ~ Poisson(λ). (a) k*(α, λ) is non-decreasing in λ. (b) k*(α, λ) = 0 if and only if λ ≤ −ln α; for α = 0.95 this threshold is ${T.k_zero_threshold.toFixed(4)} events per day. (c) Provisioning at the mean, k = ⌊λ⌋, leaves the system under-provisioned with probability P(X > ⌊λ⌋), which is at least 0.26 for every λ ≥ 1, about 0.35 at λ = 3, and tends to 0.5 as λ grows. (d) k*(α, λ) = λ + z_α√λ + O(1) as λ → ∞.`),
  P(`Part (c) is the formal version of the first heuristic discussed in the Introduction. A system sized at the mean load is short on between a quarter and a half of days even when the Poisson assumption holds exactly. The proofs of all propositions are in Appendix A.`),
  H2('3.2 Over-dispersion'),
  BOX('Proposition 2 (over-dispersion inflates capacity).', `Let X_d | M ~ Poisson(λM) with E[M] = 1 and Var(M) = c² > 0. Then (a) Var(X_d) = λφ with φ = 1 + λc². (b) X_d dominates Poisson(λ) in the convex order, so E[(X_d − k)⁺] ≥ E[(Y − k)⁺] for every k, where Y ~ Poisson(λ). (c) If φ stays bounded as λ grows, k*_mixed(α) = λ + z_α√(λφ) + O(1). If instead the multiplier has a fixed coefficient of variation c, then φ grows with λ and k*_mixed(α) = λ·F_M⁻¹(α) + O(√λ), where F_M is the distribution of M. In that regime the normal approximation λ + z_α√(λφ) understates the exact quantile by an amount that grows linearly in λ, and √φ is a lower guide for the inflation of the safety stock k* − λ, not an exact factor.`),
  P(`For a Gamma-distributed multiplier at λ = 120.7 and c = 0.3, for example, the exact ratio of the safety stock to its Poisson value is 3.7, against √φ = 3.4; at c = 0.44 it is 5.5 against 4.9. Planning should therefore use the exact negative-binomial quantile, which Table 1 reports. At λ = 10 events per day and c = 0.3, the Poisson plan k* = 15 is exceeded on 11.0% of days instead of 4.9%, and the correct requirement is 18. At λ = 25 and c = 0.3, the Poisson plan of 33 is exceeded on 16.7% of days and 41 is required.`),
  ...table('Table 1. Capacity under over-dispersed arrivals (Gamma-mixed Poisson, α = 0.95)',
    ['λ (events/day)', 'c (CV of daily rate)', 'φ', 'k* Poisson', 'k* mixed', 'P(exceed) Poisson plan'],
    T.overdispersion.filter(r => r.lambda >= 10).map(r => [r.lambda, r.cv, f2(r.phi), r.k_poisson, r.k_negbin, (100 * r.exceedance_prob_poisson_plan || 100 * r.exceed_prob_poisson_plan).toFixed(1) + '%']),
    [1500, 1800, 1100, 1500, 1500, 1960], 'Exact negative-binomial quantiles, computed by paper_tables.py.'),
  H2('3.3 Thinning'),
  P(`Requests may arrive in clusters even when incidents are rare. Because critical hallucinations are an independent thinning of requests, the dispersion of the incident stream follows from that of the request stream.`),
  BOX('Proposition 3 (thinning reduces dispersion).', `Let N be the request count in a window with mean μ and Fano factor F = Var(N)/μ, and let each request independently become a critical event with a constant probability p that does not depend on the request stream. Then the event count N_p has mean pμ and Fano factor 1 + p(F − 1). Equivalently, for a mixed-Poisson day with a rate multiplier of coefficient of variation c, φ = 1 + λc² with λ = pμ, and independent thinning with constant p leaves M, and hence c, unchanged.`),
  P(`A guardrail cascade that lowers the residual probability p therefore pulls the incident stream towards Poisson (Fano factor 1), whereas an unprotected stream, with p large, keeps most of the burstiness of the request stream. Since c is invariant to thinning while φ is not, c is the quantity that can be carried over between streams with different event rates. That transfer requires p to be constant and independent of M, which we assume for hallucinations but do not test. A practical reading is that over-dispersion matters most where capacity is largest, that is, with weak guardrails, and matters less after strong filtering.`),
  H2('3.4 Guardrail cascades and dependence'),
  P(`A cascade of N layers with stand-alone clearance rates c_i (the share of critical hallucinations that layer i blocks) is usually assumed to give a residual rate λ_N = λ₀Π(1 − c_i). That formula presumes independent layer decisions, whereas in practice the same ambiguous or adversarial outputs tend to fool all the layers.`),
  BOX('Proposition 4 (dependence bounds).', `For any joint behaviour of the layers, λ₀(1 − Σc_i)⁺ ≤ λ_N ≤ λ₀(1 − max_i c_i). If the layers' catch indicators, conditional on a hallucination, are positively associated (Esary et al. 1967), then additionally λ_N ≥ λ₀Π(1 − c_i). Consequently the multiplicative formula understates residual risk and, through Proposition 1(a), understates required capacity.`),
  P(`Table 2 shows how wide the identification problem is. With c_i = 0.63 and λ₀ = 10, three layers could imply anything from 0 to 7 units of capacity, depending on the unknown dependence. This is why the dependence has to be measured (Section 5.2) and not assumed.`),
  ...table('Table 2. Residual rate and capacity bounds (λ₀ = 10, c_i = 0.63, α = 0.95)',
    ['N', 'λ_N lower', 'λ_N independent', 'λ_N upper', 'k* lower', 'k* indep.', 'k* upper'],
    T.dependence_bounds.map(r => [r.N, f2(r.lambda_lower), f2(r.lambda_indep), f2(r.lambda_upper), r.k_lower, r.k_indep, r.k_upper]),
    [700, 1500, 1700, 1500, 1200, 1300, 1460]),
  H2('3.5 Cost-minimising guardrail depth'),
  P(`Let C_h be the daily cost of one unit of triage capacity, g_i the daily compute cost of layer i, and k_min ≥ 0 a minimum standing capacity, since an on-call engineer is not dismissed because incidents are rare. Consider the cost`),
  EQ('f(N) = C_h · max{ k_min, k*(α, λ_N) } + Σ_{i ≤ N} g_i', '2'),
  P(`subject to a latency constraint Σ_{i ≤ N} L_i ≤ SLA, where L_i is the added latency of layer i.`),
  BOX('Proposition 5 (optimal depth).', `(a) In general f is not unimodal in N: because k* is integer-valued with plateaus, f can rise and then fall again. (b) With k_min ≥ 1, let N₀ be the first N with k*(α, λ_N) ≤ k_min; every N > N₀ is strictly dominated, so N* ≤ N₀. (c) Let θ = C_h/g with equal per-layer compute cost g. The minimiser N*(θ) is non-decreasing in θ: when human triage is relatively expensive, deeper cascades are optimal. (d) The latency constraint restricts N to a feasible prefix of the cascade.`),
  P(`Table 3 gives an illustrative parameter set (λ₀ = 10 events per day, a clearance of 0.63 per layer under independence, $150 per capacity unit, $25 per layer). With k_min = 0 the cost falls from N = 3 to N = 4, rises at N = 5 and falls again at N = 6, where k* reaches zero (λ₆ = 0.026 < −ln 0.95), so the minimum is at N = 6. With a realistic floor of one on-call engineer (k_min = 1) the minimum is at N = 4. The number of layers is thus an outcome of the model and not a constant: it depends on the cost ratio, the clearance rates, the dependence between layers and the latency constraint, and a fixed prescription such as "three layers" does not follow from the cost model. Part (a) is a property of the model structure and not an empirical finding.`),
  ...table('Table 3. Daily cost by guardrail depth (λ₀ = 10, c = 0.63 independent, C_h = $150/unit, g = $25/layer)',
    ['N', 'λ_N', 'k*', 'Labour', 'Compute', 'Total (k_min = 0)', 'Total (k_min = 1)'],
    T.table1.map(r => [r.N, r.lambda.toFixed(3), r.k_star, usd(r.labour), usd(r.compute), usd(r.total), usd(150 * Math.max(1, r.k_star) + r.compute)]),
    [700, 1200, 800, 1400, 1400, 1930, 1930],
    'Minimum: N = 6 under k_min = 0; N = 4 under k_min = 1. The cost parameters are illustrative assumptions.'),
  H2('3.6 Beyond a single Poisson: typed failure classes'),
  P(`An LLM service produces several kinds of failure, and they violate the Poisson assumptions in different ways. Treating "all failures" as one Poisson stream is therefore a modelling error and not a harmless simplification. We model each class with the process that matches its mechanism and combine the classes only at the level of the human-handled event, an incident or a ticket. Table 4 summarises the mapping, the assumption that fails and where the evidence appears.`),
  ...table('Table 4. Failure classes, mechanisms and models',
    ['Class', 'Mechanism', 'Poisson assumption violated', 'Model used', 'Evidence'],
    [['Hallucination (per answered query)', 'Independent errors of the model given the query, on a clustered, daily-varying request stream', 'Constant rate; independence of requests', 'Cox / negative-binomial thinning of the request stream (Props. 2, 3)', 'Sections 5.3, 5.5'],
     ['Provider-declared incidents', 'Outages, possibly followed by further incidents within hours; weekday and hour seasonality and a drifting level', 'Orderliness and independence (self-excitation)', 'Seasonal, level-adjusted Hawkes process with exponential kernel; NHPP as null', 'Section 5.7, App. C'],
     ['Serving errors and timeouts', 'Common-cause episodes (outages, rate limiting) with heavy-tailed size', 'Orderliness (batch arrivals), independence', 'Episode process (Hawkes) with heavy-tailed marks; compound Poisson for failed-request counts', 'Section 5.7, App. C'],
     ['Human triage service', 'Mixture of quick and very long tickets', 'Exponential service', 'Heavy-tailed (Weibull, lognormal) service; workload headroom', 'Section 5.6']],
    [1500, 2200, 1700, 2300, 1660]),
  BOX('Proposition 6 (superposition and clustering).', `(a) If the daily counts of independent failure classes j have means λ_j and dispersion indices φ_j, the total daily count has mean Σλ_j and variance Σλ_jφ_j, so the 95% capacity is approximately Σλ_j + z·√(Σλ_jφ_j). A single Poisson on the total uses φ = 1 and understates the safety stock by the factor √φ_eff, where φ_eff = Σλ_jφ_j / Σλ_j. The superposition of independent classes is Poisson only if every class is Poisson. (b) For a stationary Hawkes process (Hawkes 1971) with branching ratio α < 1, the cluster started by a background event has a Borel size distribution with mean 1/(1 − α), and the long-window Fano factor of counts is 1/(1 − α)². (c) For a compound Poisson count N = Σ_{i ≤ M} X_i with M ~ Poisson(ν), the Fano factor is E[X²]/E[X], which is unbounded when the mark distribution has an infinite second moment (for instance a Pareto tail index below 2). The variance of the daily count, and with it the error of a Poisson plan, is then dominated by the largest episodes.`),
];
module.exports = { intro, related, model };
