const { P, PN, H1, H2, H3, BUL, table, IMG } = require('./lib');
const S = require('../../runs/summary.json');
const N = { qwen05: 'Qwen2.5-0.5B', smol360: 'SmolLM2-360M', qwen15: 'Qwen2.5-1.5B' };
const R = Object.keys(N);
const f0 = x => Math.round(x), f1 = x => x.toFixed(1), f2 = x => x.toFixed(2), f3 = x => x.toFixed(3);
const pct = x => (100 * x).toFixed(1) + '%';
const usd2 = x => { const v = Math.round(x); return (v < 0 ? '-$' : '$') + Math.abs(v).toLocaleString('en-US'); };
const cfg = (r, c) => S[r].sla500.configs.find(x => x.config === c);
const ci = (r, c, k) => S[r].sla500.bootstrap_ci[c][k];
const rng = (lo, hi, d = 0) => `[${lo.toFixed(d)}, ${hi.toFixed(d)}]`;
const rngs = (a, d = 2) => { const l = Math.min(...a), h = Math.max(...a); return `${l.toFixed(d)} to ${h.toFixed(d)}`; };
const sci = x => x < 1e-3 ? x.toExponential(0).replace('e-', '×10⁻').replace('+', '') : x.toFixed(3);
const T3 = S.triage;
const T3x = [{ cv: T3.software_company.arrivals_excl_low_days.detrended.implied_daily_rate_cv, cv_all: T3.software_company.arrivals.detrended.implied_daily_rate_cv }, { cv: T3.italian_helpdesk.arrivals_excl_holidays.detrended.implied_daily_rate_cv, cv_all: T3.italian_helpdesk.arrivals.detrended.implied_daily_rate_cv }, { cv: T3.servicenow.arrivals_excl_low_days.detrended.implied_daily_rate_cv, cv_all: T3.servicenow.arrivals.detrended.implied_daily_rate_cv }];
const burstNone = r => S[r].burst.poisson_checks.none;
const meanPlanAll = R.flatMap(r => [...Object.values(S[r].sla500.poisson_checks), ...Object.values(S[r].burst.poisson_checks)].map(v => 100 * v.p_exceed_mean_capacity_observed));
const baseNone = r => S[r].sla500.poisson_checks.none;

// ---------------------------------------------------------------- Section 4
const method = [
  H1('4. Empirical Evaluation: Design'),
  H2('4.1 Data, generators and ground truth'),
  P(`We use the validation set of SQuAD 2.0 (Rajpurkar et al. 2018), which mixes answerable questions with questions that the supplied passage cannot answer. One random sample of 300 questions (seed 0; 148 unanswerable) was drawn once and given to all three generators, so the three runs are paired on the same questions and are not independent samples. Each model receives the passage and the question and must reply with a short answer or the token UNANSWERABLE. A response is labelled a hallucination if it is not an abstention and either the question is answerable and the answer matches no gold answer (normalised containment, or token-F1 of at least 0.6), or the question is unanswerable. Abstentions are never counted as hallucinations and bypass the guardrails. The generators are Qwen2.5-0.5B-Instruct, SmolLM2-360M-Instruct and Qwen2.5-1.5B-Instruct (Qwen Team 2024; Allal et al. 2025), run greedily on a CPU. We chose small open models because they can be run end to end with full control over latency measurement. Their hallucination rates are higher than those of frontier models, so absolute rates should not be transferred (Section 6.3).`),
  H2('4.2 Guardrail layers'),
  P(`The three layers follow the usual progression from deterministic rules, through a trained classifier, to a semantic judge, and each one is implemented and executed on every answer. Layer L1 applies regular expressions for e-mail addresses, national identifiers, card and phone numbers, checks for template-token leakage and degenerate repetition, and blocks any answer containing a number that is absent from the evidence passage. Layer L2 is an extractive question-answering verifier: a SQuAD 2.0-trained model (deepset/roberta-base-squad2) answers the question from the passage, the score is the token-F1 between its span and the generator's answer (zero if it predicts no answer), and the output is blocked when the score is below 0.5, a threshold we did not tune. Layer L3 is an LLM judge (Qwen2.5-1.5B-Instruct in every run) that sees the passage, the question and the answer and replies SUPPORTED or UNSUPPORTED (Zheng et al. 2023); it is invoked only when routed, which with L2 present means only if the L2 score is below 0.9.`),
  P(`The first implementation of L2 was an NLI cross-encoder (DeBERTa-v3-small; He et al. 2021) that scored whether the passage entails "the answer to Q is A". It proved uninformative, and we replaced it with the extractive verifier after seeing the results (Section 5.1). We did not use safeguard classifiers of the Llama Guard type because they target policy violations and not factual grounding. All layers use the same evidence passage, as in retrieval-grounded verification. Because every layer is run on every example, any subset or cascade can be evaluated offline from the observed flags, without an independence assumption. For each call we record the flag, the score, the wall-clock latency and any exception.`),
  P(`Layers fail open. A call that raises an exception or takes longer than 2 s is counted as a system failure, from which we estimate a failure rate and not assume one; its verdict is discarded, so the answer passes that layer, and the added latency is capped at 2 s. No call raised an exception, so all system failures are judge calls slower than 2 s, which were ${rngs(R.map(r => 100 * S[r].layer_timeouts_share.L3), 0)}% of judge calls on our CPU set-up. Section 5.4 reports a sensitivity analysis in which slow verdicts are awaited and credited.`),
  H2('4.3 Traffic replay and estimators'),
  P(`Production logs of hallucinations are unavailable, so arrivals are simulated while outcomes are measured. Queries arrive according to an NHPP with a 24-slot hour-of-day intensity and a mean of 200 queries per day over 90 days. The default profile follows business hours; a second profile is the hour-of-day profile measured in the BurstGPT production trace (Section 4.5). A Cox variant multiplies each day's intensity by a Gamma factor with mean 1 and coefficient of variation c, to represent bursty demand. We use c = 0.3 and c = 0.44 as scenario values. Net of trend, and after excluding holiday and low-volume days, public ticket streams give daily-rate coefficients of variation of 0.10 to 0.38 (0.25 to 0.41 with all days; Section 5.6), so c = 0.3 lies within that range and c = 0.44 above it. The value 0.44 is the smallest coefficient of variation of any 14-day window of BurstGPT (Section 5.5), whose variability over the whole trace is much larger, so it is a floor for that trace and not a net-of-trend estimate comparable to the ticket values.`),
  P(`Each arriving query replays a uniformly drawn example from the measured pool, and it becomes a critical event if it is a hallucination that survives the cascade (the detection assumption of Section 3.1). For each event stream we estimate λ̂ as events per day and apply four tests: an index-of-dispersion test on daily counts, a chi-square test of constant hourly intensity, a Kolmogorov-Smirnov test of raw inter-arrival times against an exponential and of time-rescaled gaps under the fitted hourly intensity (the Lilliefors-type p-value is optimistic), and a negative-binomial fit of daily counts. Uncertainty from the finite evaluation pool is quantified with a 300-draw bootstrap over examples, reported as 95% percentile intervals. Because the same pool generates all arrivals, the replay tests whether the counting process has the claimed structure given measured per-query outcomes. It does not test whether real users' queries are independent, which is the main limit on external validity.`),
  H2('4.4 Cascade selection and cost model'),
  P(`We evaluate the cascades L1, L2 and L3 and all their combinations, always in the order L1, L2, L3, including the case of no guardrail. The *best cascade* is the one that minimises k* + 0.02 × (mean added latency in ms) + (system failures per day) among cascades whose mean added latency is within the stated budget (100 ms, or 500 ms where indicated). The weights are arbitrary and were not tuned; they serve only to produce one ranking for Sections 5.3 and 5.7, where L1+L2 under the 500 ms budget is selected for all three generators.`),
  P(`Daily cost is C_h·max(k_min, k*) plus compute, false-block and residual-harm costs. We set C_h to $150 per capacity unit, compute to $0.0001 per classifier call and $0.002 per judge call, the false-block cost to $1 per wrongly blocked answer and the residual-harm cost to $100 per hallucination that reaches a user. These are scenario values, not estimates. The *minimum-dollar cascade* of Section 5.4 minimises this cost and can differ from the best cascade because it ignores latency and system failures. A sensitivity grid varies daily traffic (50, 200 and 800 queries), the false-block cost ($0, $1, $10) and the residual-harm cost ($0, $100, $1,000), giving 27 scenarios per generator. Sampling uncertainty is quantified by pool bootstrap, including paired intervals for cost differences between cascades.`),
  H2('4.5 Public production data'),
  P(`Six public sources test the counting-process assumptions on real systems. BurstGPT (Wang et al. 2025) records 10.6 million requests to regional Azure OpenAI services over 231 days. A dataset of LLM service outages and incident reports (Chu et al. 2025) provides 457 incidents declared by three providers from March 2023. Three company ticket logs describe human triage: customer tickets of an international software company (Abdellatif 2026), the incident log of a ServiceNow instance (Amaral et al. 2018) and the help-desk log of an Italian software company (Verenich 2016). Finally, a curated database of court decisions involving fabricated content (Charlotin 2026) is the only dated log of hallucination incidents we found, although it is confined to the legal domain and is subject to strong detection and reporting bias. Appendix B gives the filters, the work-week and holiday rules, and the estimators. Two features of the design are worth stating here. Each ticket analysis is reported twice, once for all work days and once with holidays and low-volume days excluded, because isolated dips inflate dispersion that a local mean cannot absorb. And each Poisson plan is evaluated both against a two-sided local mean, which is not a feasible forecast, and causally, with a trailing mean and a coefficient of variation estimated on earlier days only.`),
  P(`For typed failure models we fit a seasonal Hawkes process with exponential kernel to provider incidents, λ(t) = μ₀s(t) + Σαβe^{−β(t − t_i)}, where s(t) is a weekday-by-hour profile estimated from the data and held fixed, and compare it with a seasonal NHPP by AIC, by a parametric-bootstrap likelihood-ratio test and by the time-rescaling test. For BurstGPT failures we detect outage-like episodes, characterise their size and arrival process, and test four alternative episode definitions. Finally, we combine class-specific negative-binomial daily counts by Monte Carlo to compare the 95% capacity of a typed superposition with that of a single Poisson on the total (Section 5.7). All simulations and bootstrap draws are seeded and can be reproduced with the scripts that accompany the paper (Appendix D).`),
];

// ---------------------------------------------------------------- Section 5
const results = [
  H1('5. Findings'),
  H2('5.1 Hallucination rates and guardrail layer performance'),
  P(`On the same 300 questions the hallucination rate is ${pct(S.qwen05.p_halluc)} for Qwen2.5-0.5B, ${pct(S.smol360.p_halluc)} for SmolLM2-360M and ${pct(S.qwen15.p_halluc)} for Qwen2.5-1.5B, and 75 to 90% of the hallucinations are answers to unanswerable questions. Table 5 reports the layers. The deterministic layer L1 catches only ${rngs(R.map(r => 100 * S[r].marginal_clearance.L1), 1)}% of hallucinations: the task contains no personal data or template leaks and few fabricated numbers, so L1 is nearly inert, though also nearly free of latency and false blocks. The judge L3 blocks ${rngs(R.map(r => 100 * S[r].marginal_clearance.L3), 0)}% of hallucinations and ${rngs(R.map(r => 100 * S[r].false_block_share_of_good.L3), 0)}% of correct answers, and each call takes about 1.8 to 1.9 s on our CPU. Because ${rngs(R.map(r => 100 * S[r].layer_timeouts_share.L3), 0)}% of judge calls exceed the 2 s timeout and their verdicts are discarded, these clearances are lower than they would be if slow verdicts were credited (Section 5.4). The judge is Qwen2.5-1.5B-Instruct throughout, so one arm is judged by its own generator; we did not test for a self-judging effect.`),
  P(`The NLI classifier we tried first gave a negative result. Its entailment score separated correct from hallucinated answers with an AUC of ${rngs(R.map(r => S[r].auc_nli_negative_result), 2)}, where 0.5 is chance, and at the default threshold it blocked ${rngs(R.map(r => 100 * S[r]['nli_catch_and_falseblock_at_0.5'][0]), 0)}% of hallucinations and ${rngs(R.map(r => 100 * S[r]['nli_catch_and_falseblock_at_0.5'][1]), 0)}% of correct answers. Its apparent capacity savings were an artefact of blocking almost everything, which is why we report false-block rates next to every capacity figure: a capacity reduction alone cannot distinguish a useful layer from one that blocks indiscriminately. We replaced it with the extractive verifier (AUC ${rngs(R.map(r => S[r].auc_l2), 2)}) and re-ran all layers on the stored answers. The replacement was made after seeing the results, the verifier is evaluated on the same 300 questions, and it is in effect a second solver of the task it verifies, trained on SQuAD, which flatters it relative to a generic classifier. All numbers below use it.`),
  ...table('Table 5. Guardrail layers on the same 300 SQuAD 2.0 questions for each generator (CPU inference; latency re-measured without concurrent jobs)',
    ['Generator', 'p₀ (hallucination rate)', 'c₁ (L1)', 'c₂ (L2 QA)', 'c₃ (L3 judge)', 'L2 false-block (good answers)', 'L3 false-block', 'L2 mean ms', 'L3 mean ms (capped at 2 s)'],
    R.map(r => [N[r], pct(S[r].p_halluc), pct(S[r].marginal_clearance.L1), pct(S[r].marginal_clearance.L2), pct(S[r].marginal_clearance.L3), pct(S[r].false_block_share_of_good.L2), pct(S[r].false_block_share_of_good.L3), f0(S[r].layer_latency_ms.L2.mean), f0(S[r].layer_latency_ms.L3.mean)]),
    [1300, 1100, 800, 900, 900, 1250, 1000, 900, 950],
    'c_i is the stand-alone share of hallucinated answers the layer blocks. False-block is the share of correct, non-abstained answers blocked (denominators 119, 103 and 136). The L2 threshold (F1 < 0.5) was not tuned; SmolLM2 gives longer answers, which lowers its token-F1 agreement and inflates its L2 false-block rate.'),

  H2('5.2 Dependence between layers and the cost of routing'),
  P(`Among hallucinated answers, the catch decisions of L2 and L3 are weakly and positively associated (φ = ${R.map(r => f2(S[r].dependence_stats.phi)).join(', ')} for the three generators; 95% bootstrap intervals ${R.map(r => '[' + S[r].dependence_stats.phi_ci.map(f2).join(', ') + ']').join(', ')}; Fisher exact p = ${R.map(r => f3(S[r].dependence_stats.fisher_exact_p)).join(', ')}), which is the direction Proposition 4 predicts. The intervals include zero for two of the three generators and the runs share their questions, so the evidence is suggestive and not conclusive. L1 catches only 1 to 10 hallucinations per generator, so its pairwise statistics (φ ≤ 0.09) say nothing useful.`),
  P(`The excess of the residual share over the independence formula is correspondingly modest (Figure 1, left). For the L2+L3 cascade, the share of hallucinations that pass both layers is ${rngs(R.map(r => 100 * S[r].residual_share['L2+L3'].independent), 1)}% under the independence formula, computed from the same sample's marginals, and ${rngs(R.map(r => 100 * S[r].residual_share['L2+L3'].observed_no_routing), 1)}% when both layers see every answer. That is ${R.map(r => f1(S[r].dependence_stats.ratio_no_routing.point)).join(', ')} times higher (${R.map(r => S[r].dependence_stats.n_pass_no_routing).join(', ')} hallucinations pass; pool-bootstrap intervals ${R.map(r => '[' + S[r].dependence_stats.ratio_no_routing.ci.map(f1).join(', ') + ']').join(', ')}), and the interval includes 1 for ${R.filter(r => S[r].dependence_stats.ratio_no_routing.ci[0] <= 1.0).length} of the three generators. The cost of dynamic routing, in which only low-agreement answers go to the judge, is clearer. The ratios rise to ${R.map(r => f1(S[r].dependence_stats.ratio_with_routing.point)).join(', ')} (${R.map(r => '[' + S[r].dependence_stats.ratio_with_routing.ci.map(f1).join(', ') + ']').join(', ')}), and the number of passing answers rises to ${R.map(r => S[r].dependence_stats.n_pass_with_routing).join(', ')}. Routing cuts judge calls by ${rngs(R.map(r => 100 * (1 - S[r].sla500.configs.find(x => x.config === 'L2+L3').judge_route_rate)), 0)}%, but the judge no longer sees the answers the verifier considers consistent, and those contain a substantial share of the hallucinations the judge would have caught. The absolute numbers of passing answers are small, so all of these estimates are imprecise.`),
  ...IMG('../../runs/fig_cascade.png', 600, 227, 'Figure 1. Left: share of hallucinations passing the L2+L3 cascade under independence, observed without routing, and observed with routing. Right: capacity k* by cascade (95% bootstrap CI over the evaluated pool), log scale.'),

  H2('5.3 Burstiness: Poisson-sized plans under Cox traffic'),
  P(`With non-homogeneous Poisson arrivals and no burstiness the replay reproduces the Poisson structure, as it must by construction. For the unprotected stream the daily-count dispersion test does not reject (p = ${rngs(R.map(r => baseNone(r).dispersion_p), 2)}), raw inter-arrival times are strongly non-exponential because the intensity varies by the hour, and the time-rescaled gaps are consistent with Exp(1) (p = ${rngs(R.map(r => baseNone(r).ks_rescaled_p), 2)}). This checks the replay and the estimators and shows that the rescaling machinery behaves as theory predicts. It is not evidence that real traffic is Poisson, because the arrivals are simulated.`),
  P(`When the daily intensity is multiplied by a Gamma factor with a coefficient of variation of only 0.3, the dispersion test rejects overwhelmingly (p < 10⁻⁹⁰ for the unprotected stream) and the negative-binomial shape parameter r lies between ${f1(Math.min(...R.map(r => burstNone(r).nb_r)))} and ${f1(Math.max(...R.map(r => burstNone(r).nb_r)))}. The Poisson capacity k* = ${R.map(r => burstNone(r).k_star_poisson).join(', ')} for the three generators without guardrails is then exceeded on ${rngs(R.map(r => 100 * burstNone(r).p_exceed_k_star_observed), 0)}% of days instead of the targeted 5%. The correct negative-binomial requirement is ${R.map(r => burstNone(r).k_star_negbin).join(', ')}, that is, ${rngs(R.map(r => 100 * (burstNone(r).k_star_negbin / burstNone(r).k_star_poisson - 1)), 0)}% more (Figure 2). Under the best cascade (L1+L2, λ of about 4 to 17 per day) the effect is smaller in absolute capacity, but the Poisson plan is still exceeded on ${rngs(R.map(r => 100 * S[r].burst.poisson_checks['L1+L2'].p_exceed_k_star_observed), 0)}% of days (Table 6). Because the burstiness is injected, this replay confirms Proposition 2 and Table 1 on measured outcomes and is not an independent empirical finding. Provisioning at the mean was exceeded on ${rngs(meanPlanAll, 0)}% of days across all configurations we replayed, against the 5% target of the quantile plan.`),
  ...IMG('../../runs/fig_burst.png', 600, 220, 'Figure 2. Daily critical hallucinations without guardrails (Qwen2.5-0.5B, 90 days, 200 queries/day). Left: steady NHPP traffic. Right: bursty traffic. Dotted line: Poisson k* (α = 0.95).'),
  P(`To place the scenario values in context, the smallest coefficient of variation of any 14-day window of BurstGPT is ${f2(S.real_data.burstgpt.calmest_14day_window.cv)}, a floor for a trace whose median window has ${f2(S.real_data.burstgpt.calmest_14day_window.median_window_cv)} (Section 5.5), while the daily-rate coefficient of variation net of trend in public ticket streams is ${f2(Math.min(...T3x.map(x => x.cv)))} to ${f2(Math.max(...T3x.map(x => x.cv)))} (Section 5.6; ${f2(Math.min(...T3x.map(x => x.cv_all)))} to ${f2(Math.max(...T3x.map(x => x.cv_all)))} before exclusions). Table 6 gives the exceedance rates under the two scenario values, the second combined with the BurstGPT hour-of-day profile. The gap shrinks with guardrails but does not vanish: for the best cascade the Poisson plan is exceeded on ${rngs(R.map(r => 100 * S[r].burst044.poisson_checks['L1+L2'].p_exceed_k_star_observed), 0)}% of days at c = 0.44, against ${rngs(R.map(r => 100 * S[r].burst044.poisson_checks.none.p_exceed_k_star_observed), 0)}% without guardrails. This is what Propositions 2 and 3 lead one to expect. For a given c, φ = 1 + λc² is smaller when the event rate is smaller, so over-dispersion inflates the safety stock by fewer units (about ${R.map(r => S[r].burst044.poisson_checks['L1+L2'].k_star_negbin - S[r].burst044.poisson_checks['L1+L2'].k_star_poisson).join(', ')} extra), although the exceedance probability remains between 1.3 and 3 times the target.`),
  ...table('Table 6. Share of days on which the Poisson-sized capacity k* is exceeded (target 5%; 90 simulated days)',
    ['Generator', 'Cascade', 'Steady NHPP (c = 0)', 'c = 0.3', 'c = 0.44 + BurstGPT profile', 'k* Poisson → k* negative-binomial (c = 0.44)'],
    R.flatMap(r => ['none', 'L1+L2'].map(c => [N[r], c,
      pct(S[r].sla500.poisson_checks[c].p_exceed_k_star_observed), pct(S[r].burst.poisson_checks[c].p_exceed_k_star_observed), pct(S[r].burst044.poisson_checks[c].p_exceed_k_star_observed),
      `${S[r].burst044.poisson_checks[c].k_star_poisson} → ${S[r].burst044.poisson_checks[c].k_star_negbin}`])),
    [1500, 1000, 1500, 1100, 2000, 2260],
    'Observed over 90 simulated days, so each share has a standard error of about 2 to 5 percentage points. L1+L2 is the best cascade by the objective of Section 4.4 within the 500 ms budget; it is not the minimum-dollar cascade of Section 5.4.'),

  H2('5.4 Capacity, latency and cost by cascade'),
  P(`Table 7 gives, for each generator, the residual rate, the capacity, the added latency and the volume of false blocks for the main cascades at 200 queries per day, with bootstrap intervals over the evaluated pool. At a pool of 300 questions the intervals are wide, so differences of a few units of k* between cascades are not significant; the large differences are.`),
  ...table('Table 7. Cascade performance at 200 queries/day, α = 0.95, SLA 500 ms mean added latency (95% bootstrap CI in brackets)',
    ['Generator', 'Cascade', 'λ per day', 'k*', 'Mean added latency (ms)', 'False blocks / day', 'System failures / day'],
    R.flatMap(r => ['none', 'L1+L2', 'L2', 'L3', 'L2+L3'].map(c => [N[r], c, `${f1(cfg(r, c).lambda_per_day)} ${rng(...ci(r, c, 'lam'), 0)}`, `${cfg(r, c).k_star} ${rng(...ci(r, c, 'k'), 0)}`, f0(cfg(r, c).mean_latency_ms) + (cfg(r, c).feasible ? '' : ' ✗'), f1(cfg(r, c).lambda_false_block), f1(cfg(r, c).lambda_sys_fail)])),
    [1400, 900, 1700, 1300, 1500, 1300, 1260],
    'L2+L3 is the routed cascade (the judge is called only if the L2 score is below 0.9); L3 alone runs the judge on every answer. ✗ marks a violation of the 500 ms budget. Mean added latency is per query, including abstentions, which bypass the guardrails, so it differs from the per-layer means of Table 5; each judge call is capped at the 2 s timeout, after which its verdict is discarded and it counts as a system failure. L1+L2 and L1+L2+L3 equal L2 and L2+L3 up to small differences because L1 is nearly inert on this task.'),
  P(`A single task-specific verifier (L2) reduces required capacity from ${R.map(r => cfg(r, 'none').k_star).join(', ')} to ${R.map(r => cfg(r, 'L2').k_star).join(', ')} units per day, a reduction of ${rngs(R.map(r => 100 * (1 - cfg(r, 'L2').k_star / cfg(r, 'none').k_star)), 0)}%. Adding the routed judge changes it to ${R.map(r => cfg(r, 'L2+L3').k_star).join(', ')}, a difference of ${R.map(r => cfg(r, 'L2').k_star - cfg(r, 'L2+L3').k_star).join(', ')} units, while it roughly triples added latency and adds about six system failures per day through timeouts. Running the judge on every answer is infeasible under any latency budget we consider (about 1.6 to 1.8 s per query) and produces 50 to 60 system failures per day. Under a 100 ms budget only L1 and L2 are feasible (L2 takes 90 to 100 ms here); under 500 ms the routed judge fits on average but not at the 95th percentile (${rngs(R.map(r => cfg(r, 'L2+L3').p95_latency_ms / 1000), 1)} s). Latencies would be much lower on GPUs or hosted inference.`),
  P(`The best cascade by the objective of Section 4.4 is ${R.map(r => S[r].sla500.best).filter((v, i, a) => a.indexOf(v) === i).join(', ')} for all three generators. At the scenario costs the minimum-dollar cascade is ${R.map(r => `${S[r].sla500.cheapest_config} for ${N[r]}`).join(', ')}, and the daily cost falls from $${R.map(r => Math.round(cfg(r, 'none').cost.total).toLocaleString('en-US')).join(', $')} without guardrails to $${R.map(r => Math.round(S[r].sla500.configs.find(x => x.config === S[r].sla500.cheapest_config).cost.total).toLocaleString('en-US')).join(', $')} at the minimum. The paired bootstrap interval of the daily saving from adding the routed judge to L1+L2 is ${R.map(r => `${usd2(S[r].cost_saving_ci['L1+L2+L3 vs L1+L2'].saving_point)} [${S[r].cost_saving_ci['L1+L2+L3 vs L1+L2'].ci.map(usd2).join(', ')}]`).join('; ')} for the three generators. It is positive but not distinguishable from zero for the two Qwen generators and slightly negative for SmolLM2-360M, whose classifier leaves only ${f0(cfg('smol360', 'L2').lambda_per_day / 200 * 300)} of its ${S.smol360.n_hallucinated} hallucinations for the judge to catch, and the judge caught none. Under the fail-open policy, then, the judge does not demonstrably pay for itself for any generator.`),
  P(`The result depends on the timeout policy. If slow judge verdicts were awaited and credited, the stand-alone clearance of L3 would be ${rngs(R.map(r => 100 * S[r].late_credit_sensitivity.c3), 0)}% instead of ${rngs(R.map(r => 100 * S[r].marginal_clearance.L3), 0)}%, the routed cascade would need k* = ${R.map(r => S[r].late_credit_sensitivity.k_star_L2_L3).join(', ')}, and the saving from adding the judge would be ${R.map(r => `${usd2(S[r].late_credit_sensitivity.saving_L1L2L3_vs_L1L2.saving_point)} [${S[r].late_credit_sensitivity.saving_L1L2L3_vs_L1L2.ci.map(usd2).join(', ')}]`).join('; ')}. The judge's apparent value therefore depends on accepting latencies above 2 s. Residual hallucinations after L2 are few (${R.map(r => f0(cfg(r, 'L2').lambda_per_day / 200 * 300)).join(', ')} of 300 questions), the 27-scenario grid varies cost parameters without reflecting sampling error, and the runs share their questions, so none of the differences between generators is a general finding. What the data do support is that the classifier is the dominant layer, the deterministic layer is nearly free but also nearly useless on this task, and the judge's marginal value is small and uncertain.`),
];
module.exports = { method, results };
