const { P, PN, H1, H2, H3, BUL, table, IMG } = require('./lib');
const S = require('../../runs/summary.json');
const f0 = x => Math.round(x), f1 = x => x.toFixed(1), f2 = x => x.toFixed(2), f3 = x => x.toFixed(3);
const pct = x => (100 * x).toFixed(1) + '%';
const rngs = (a, d = 2) => { const l = Math.min(...a), h = Math.max(...a); return `${l.toFixed(d)} to ${h.toFixed(d)}`; };
const sci = x => x < 1e-3 ? x.toExponential(0).replace('e-', '×10⁻').replace('+', '') : x.toFixed(3);
const comma = x => Math.round(x).toString().replace(/\B(?=(\d{3})+(?!\d))/g, ',');
const T3 = S.triage;
const T3x = [{ cv: T3.software_company.arrivals_excl_low_days.detrended.implied_daily_rate_cv, cv_all: T3.software_company.arrivals.detrended.implied_daily_rate_cv }, { cv: T3.italian_helpdesk.arrivals_excl_holidays.detrended.implied_daily_rate_cv, cv_all: T3.italian_helpdesk.arrivals.detrended.implied_daily_rate_cv }, { cv: T3.servicenow.arrivals_excl_low_days.detrended.implied_daily_rate_cv, cv_all: T3.servicenow.arrivals.detrended.implied_daily_rate_cv }];
const RD = S.real_data, B = RD.burstgpt, I = RD.incidents;
const IC = g => I.counts[g];

const sec55 = [
  H2('5.5 Evidence from public production traces'),
  H3('Request arrivals (BurstGPT).'),
  P(`The Azure OpenAI trace has ${(B.rows / 1e6).toFixed(1)} million requests over ${B.days_covered} recorded days, and ${pct(B.failed_share)} of requests failed (zero response tokens). The hour-of-day profile has a peak-to-trough ratio of ${f1(B.peak_to_trough)}, so the arrival process is clearly non-homogeneous, as the NHPP formulation assumes. Within an hour, counts are more variable than Poisson. The median variance-to-mean ratio of counts per bin (Poisson = 1) is ${f1(B.fano['1'].median_var_over_mean)} at 1 s, ${f1(B.fano['10'].median_var_over_mean)} at 10 s, ${f1(B.fano['60'].median_var_over_mean)} at 1 min and ${f1(B.fano['600'].median_var_over_mean)} at 10 min, so requests are clustered at every scale from 1 s upward, mildly at 1 s and strongly from 10 s. By Proposition 3, an unprotected hallucination stream with p = 0.6 would inherit about ${f1(1 + 0.6 * (B.fano['600'].median_var_over_mean - 1))} of that dispersion at the 10-minute scale, whereas a cascade with a residual probability of 0.05 would retain about ${f1(1 + 0.05 * (B.fano['600'].median_var_over_mean - 1))}.`),
  P(`Day-to-day volume is extremely variable: the median day has ${comma(B.daily_requests.median)} requests, with a range from ${B.daily_requests.min} to ${comma(B.daily_requests.max)}. The median absolute day-to-day log change is ${f2(B.robust_daily_variability['median_abs_day_to_day_log_change'])}, a factor of ${f1(Math.exp(B.robust_daily_variability['median_abs_day_to_day_log_change']))}, and ${f0(100 * B.robust_daily_variability.share_of_days_changing_by_over_30pct)}% of days differ from the previous day by more than 30%. Net of the local level (the day count over the mean of the 14 neighbouring days), the coefficient of variation is ${f2(B.daily_cv['days 0-120 (files 1-2)'].window14)} in days 0 to 120 and ${f2(B.daily_cv['days 225-334 (file 3)'].window14)} in days 225 to 334. The smallest coefficient of variation of any of the ${B.calmest_14day_window.n_windows} 14-day windows with all days above 1,000 requests is ${f2(B.calmest_14day_window.cv)}, against a median window value of ${f2(B.calmest_14day_window.median_window_cv)}. We therefore treat 0.44 as a floor for the variability of this trace, not an estimate comparable to the net-of-trend values of Section 5.6. The variability reflects traffic growth, campaigns, regime shifts and probably logging gaps as well as random fluctuation (the series also contains ${B.near_duplicate_days_6_apart} near-duplicate day pairs, which we treat as a data artefact), so we use it as a stress test and not as an estimate of the dispersion of hallucination counts. In that stress test we replay the measured multipliers, rescaled to mean 1, on event streams with means of 10 and 120 per day. The Poisson plan is exceeded on ${f0(100 * B.capacity_replay['files 1-2, lambda=10'].poisson_plan_exceeded_share)}% and ${f0(100 * B.capacity_replay['files 1-2, lambda=120'].poisson_plan_exceeded_share)}% of days with the multipliers of days 0 to 120, and on ${f0(100 * B.capacity_replay['file 3, lambda=10'].poisson_plan_exceeded_share)}% and ${f0(100 * B.capacity_replay['file 3, lambda=120'].poisson_plan_exceeded_share)}% with those of days 225 to 334, which are inflated by regime shifts.`),
  H3('Service incidents (LLM providers).'),
  P(`Between March 2023 and August 2024 the three providers declared ${I.n} incidents, or ${f2(IC('all providers').lambda_per_day)} per day. Incident starts are strongly non-homogeneous: the mean weekday count is ${f1((IC('all providers').dow_counts.slice(0, 5).reduce((a, b) => a + b, 0) / 5) / (IC('all providers').dow_counts.slice(5).reduce((a, b) => a + b, 0) / 2))} times the mean weekend count, and hour-of-day homogeneity is rejected for every provider and subset. A homogeneous Poisson model is rejected on every inter-arrival and dispersion test. Allowing for weekly and daily seasonality removes part of the lack of fit but not all of it. The daily index of dispersion is ${f2(IC('all providers').daily_dispersion_index)} and still ${f2(IC('all providers').stratified_dispersion_index)} after stratifying by day of week (p = ${sci(IC('all providers').dispersion_p_stratified_by_dow)}), and a negative-binomial fit to daily counts gives r ≈ ${f1(IC('all providers').nb_r_daily)}. Part of this over-dispersion probably reflects a changing incident rate over the 18 months, which a weekday-stratified test does not remove (Section 5.7 adjusts the baseline for it). The practical consequence at this low rate is small: the Poisson and negative-binomial 95% capacities coincide (${IC('all providers').k_star_poisson_daily} incident per day), and the Poisson capacity is exceeded on ${pct(IC('all providers').observed_days_over_poisson_k)} of days, below the 5% target. This agrees with Proposition 2, since φ = 1 + λc² remains modest, about 1.2 to 1.5 here, when λ is below one per day.`),
  P(`Incident duration, measured from declared start to resolution, serves as a proxy for human response time. It has a median of ${f1(I.duration_hours.median)} h, a 90th percentile of ${f1(I.duration_hours.p90)} h and a 99th percentile of ${f0(I.duration_hours.p99)} h; the mean is ${f1(I.duration_hours.mean)} h and the coefficient of variation ${f1(I.duration_hours.cv)}, so response times are heavy-tailed and far from exponential. The 95th percentile of the number of concurrently open incidents is ${I.concurrent_open.q95_observed}, the same as for a Poisson occupancy with that mean (${I.concurrent_open.q95_mginf_poisson}), and two or more incidents are open at once ${pct(1 - I.concurrent_open.pmf['0'] - I.concurrent_open.pmf['1'])} of the time. A single standing responder therefore covers 95% of the time at provider level, and the heavy tail of durations accounts for the rare long overruns. These are provider-declared outages and degradations, not hallucinations, so they inform the arrival and service-time structure of an LLM incident stream but not its rate.`),
  H3('Dated hallucination cases (court decisions).'),
  P(`The only public, dated log of hallucination incidents we found is a curated database of court decisions in which a party relied on fabricated AI content (Charlotin 2026; ${S.cases.n_cases_with_date.toLocaleString('en-US')} dated cases, ${S.cases.span[0]} to ${S.cases.span[1]}). It is confined to the legal domain, the date is the decision date at day resolution, and detection and reporting bias is strong. Counts grew from a handful per month to over a hundred in 2025, so we analyse only the flatter period from October 2025 to August 2026 (${S.cases.segment.n.toLocaleString('en-US')} cases, ${f1(S.cases.segment.mean_weekday_tickets)} per weekday), and exclude September and October 2026 because recent months are incomplete. In that period weekday counts are over-dispersed relative to Poisson (day-of-week-stratified index ${f2(S.cases.segment.weekday_dispersion_index_stratified)}, p = ${sci(S.cases.segment.weekday_dispersion_p)}; daily-rate coefficient of variation net of trend ${f2(S.cases.segment.detrended.implied_daily_rate_cv)}). Part of this comes from the ${S.cases.segment_excl_holidays.excluded_work_days} US federal-holiday weekdays; without them the index is ${f2(S.cases.segment_excl_holidays.weekday_dispersion_index_stratified)} and the coefficient of variation ${f2(S.cases.segment_excl_holidays.detrended.implied_daily_rate_cv)}, a weak over-dispersion. At about six cases per weekday the effect on capacity is small: the 95% capacity is ${S.cases.segment.k95_poisson} under Poisson and ${S.cases.segment.k95_negbin_stratified_index} under a negative binomial with the stratified index, and a Poisson plan against the local mean is exceeded on ${pct(S.cases.segment.detrended.poisson_local_plan_exceeded)} of weekdays (${pct(S.cases.segment.causal.poisson_plan_exceeded)} with a causal plan). This is consistent with Proposition 2 and with the other low-rate streams. It is, to our knowledge, the only dispersion estimate for dated hallucination incidents that public data allow, subject to the caveats above.`),
];

const TS = { software_company: 'Software company (customer tickets 2017-23)', servicenow: 'ServiceNow incidents (12-week segment, 2016)', italian_helpdesk: 'Italian software help desk (2010-12)' };
const TK = Object.keys(TS);
const ARX = { software_company: 'arrivals_excl_low_days', servicenow: 'arrivals_excl_low_days', italian_helpdesk: 'arrivals_excl_holidays' };
const A = k => T3[k].arrivals, AX = k => T3[k][ARX[k]];
const both = (f, p) => k => `${p(f(A(k)))} → ${p(f(AX(k)))}`;
const sec56 = [
  H2('5.6 Human triage workloads in public ticket data'),
  P(`The fourth family of public data concerns what happens after an incident has been detected: how tickets arrive at, and are worked by, human teams in real organisations. The streams are customer-support and IT-incident tickets and not LLM incidents, but they are the best public evidence we know of on the arrival variability and the service-time distribution of human triage. Each stream is analysed for all work days and with holiday and low-volume days excluded by the rules of Appendix B; in Table 8 each cell reads "all days → excluded".`),
  ...table('Table 8. Arrival structure of human-handled ticket streams (work days only; Poisson plan = 95% quantile of Poisson with the local mean)',
    ['Stream', 'Tickets (per work day)', 'Work-day-stratified dispersion index (includes slow trends)', 'Daily rate CV net of trend and weekday', 'Poisson plan exceeded: in-sample local mean', 'NB plan exceeded: in-sample', 'Poisson plan exceeded: causal', 'NB plan exceeded: causal'],
    TK.map(k => [TS[k], `${A(k).n.toLocaleString('en-US')} (${f1(A(k).mean_weekday_tickets)})`, both(a => a.weekday_dispersion_index_stratified, f1)(k), both(a => a.detrended.implied_daily_rate_cv, f2)(k), both(a => a.detrended.poisson_local_plan_exceeded, pct)(k), both(a => a.detrended.negbin_local_plan_exceeded, pct)(k), `${both(a => a.causal.poisson_plan_exceeded, pct)(k)}${k === 'servicenow' ? ' (20 → 15 days)' : ''}`, both(a => a.causal.negbin_plan_exceeded, pct)(k)]),
    [1500, 1000, 1150, 1100, 1250, 1050, 1050, 900],
    'Each cell: all work days → low-volume or holiday days excluded (software company and ServiceNow: days below 35% of the rolling median, 62 and 5 days; Italian help desk: national holidays, 26 days). Target exceedance is 5%. The dispersion index includes slow trends, whereas the CV is net of a local level, so the two are not directly comparable. In-sample: the local mean is a two-sided leave-one-out mean over about 40 surrounding work days after removing the weekday effect, and c is estimated from the same days that are scored, so neither is a feasible forecast. Causal: trailing 20-work-day mean, c estimated on earlier days only, rolling origin (the weekday effects are estimated on the full sample). The software company works Sunday to Thursday; the other work weeks are Monday to Friday.'),
  P(`All streams are strongly non-homogeneous over the week and the day (weekend ticket rates are ${f2(A('software_company').weekend_to_weekday_daily_ratio)}, ${f2(A('servicenow').weekend_to_weekday_daily_ratio)} and ${f2(A('italian_helpdesk').weekend_to_weekday_daily_ratio)} of work-day rates), and arrivals remain far from Poisson even after time-rescaling, because daily volumes vary beyond the weekly cycle. Net of slow trends and the weekday effect, the coefficient of variation of the daily rate is ${f2(A('software_company').detrended.implied_daily_rate_cv)} → ${f2(AX('software_company').detrended.implied_daily_rate_cv)} for the software company, ${f2(A('italian_helpdesk').detrended.implied_daily_rate_cv)} → ${f2(AX('italian_helpdesk').detrended.implied_daily_rate_cv)} for the Italian help desk and ${f2(A('servicenow').detrended.implied_daily_rate_cv)} → ${f2(AX('servicenow').detrended.implied_daily_rate_cv)} for the ServiceNow segment, where holidays and bridge days account for most of the value. The dated hallucination cases of Section 5.5 give ${f2(S.cases.segment.detrended.implied_daily_rate_cv)} → ${f2(S.cases.segment_excl_holidays.detrended.implied_daily_rate_cv)}. These values are of the same order as our scenario values (c = 0.3 lies within the range after exclusions and c = 0.44 above it), though all of them come from non-LLM or legal-domain streams and we do not claim a universal value.`),
  P(`Because φ = 1 + λc², the effect on capacity depends on the rate. Against the in-sample local mean, a Poisson-sized plan is exceeded on ${pct(AX('software_company').detrended.poisson_local_plan_exceeded)}, ${pct(AX('italian_helpdesk').detrended.poisson_local_plan_exceeded)} and ${pct(AX('servicenow').detrended.poisson_local_plan_exceeded)} of work days (about ${f0(AX('software_company').mean_weekday_tickets)}, ${f0(AX('italian_helpdesk').mean_weekday_tickets)} and ${f0(AX('servicenow').mean_weekday_tickets)} tickets per day) instead of 5%, and on ${pct(A('software_company').detrended.poisson_local_plan_exceeded)}, ${pct(A('italian_helpdesk').detrended.poisson_local_plan_exceeded)} and ${pct(A('servicenow').detrended.poisson_local_plan_exceeded)} with all days. A causal plan, which is what an operator could actually use, is exceeded on ${pct(AX('software_company').causal.poisson_plan_exceeded)} and ${pct(AX('italian_helpdesk').causal.poisson_plan_exceeded)} of days for the two long streams with the Poisson quantile, and on ${pct(AX('software_company').causal.negbin_plan_exceeded)} and ${pct(AX('italian_helpdesk').causal.negbin_plan_exceeded)} with a negative-binomial quantile. The negative-binomial plan is thus somewhat conservative, for reasons we cannot identify from these data. The in-sample negative-binomial columns are a calibration check of Proposition 2 and not an out-of-sample test, since c is estimated on the days that are scored, and the causal evaluation of the 12-week ServiceNow segment covers only ${AX('servicenow').causal.n_eval_days} days and is uninformative.`),
  P(`Service times are heavy-tailed (Appendix C, Table C1). Resolution time has a median of ${f0(T3.software_company.resolution_calendar_hours.median)} h against a mean of ${f0(T3.software_company.resolution_calendar_hours.mean)} h for the software company, ${f0(T3.servicenow.resolution_calendar_hours.median)} h against ${f0(T3.servicenow.resolution_calendar_hours.mean)} h for ServiceNow, and ${f0(T3.italian_helpdesk.resolution_calendar_hours.median)} h against ${f0(T3.italian_helpdesk.resolution_calendar_hours.mean)} h for the Italian help desk. The coefficients of variation are ${f1(T3.software_company.resolution_calendar_hours.cv)}, ${f1(T3.servicenow.resolution_calendar_hours.cv)} and ${f1(T3.italian_helpdesk.resolution_calendar_hours.cv)}, where an exponential distribution has 1, and the Weibull shapes of ${rngs(TK.map(k => T3[k].resolution_calendar_hours.weibull_shape), 2)} indicate a decreasing hazard: a ticket that has stayed open for a long time is likely to stay open much longer. Two consequences follow for capacity planning. Models that assume exponential service are not supported, which is one more reason to size capacity from the quantile of the arrival count and to treat the service-time tail explicitly and not through a mean-based utilisation. And in the one stream with handling-time data (the software company, where workload is the in-progress hours of the tickets created that day, attributed to the creation day) the 95th percentile of the daily workload is ${f1(T3.software_company.workload.workload_q95_over_mean)} times its mean, against ${f1(T3.software_company.workload.count_q95_over_mean)} for the daily ticket count. Capacity measured in handling hours thus needs a larger multiple of the mean than capacity measured in arrivals, and the unit of triage capacity of Section 3.1 should be defined for a typical ticket with the workload tail added separately. In-progress time is calendar time in a workflow state and not effort, and the comparison is not detrended, so the ratio is indicative only.`),
  P(`For the software company and the Italian help desk, the time-average number of open tickets is ${f0(T3.software_company.concurrency.time_avg_open)} and ${f0(T3.italian_helpdesk.concurrency.time_avg_open)}, and the observed 95th percentile of open tickets is ${f0(100 * (T3.software_company.concurrency.q95_observed / T3.software_company.concurrency.q95_poisson_same_mean - 1))}% and ${f0(100 * (T3.italian_helpdesk.concurrency.q95_observed / T3.italian_helpdesk.concurrency.q95_poisson_same_mean - 1))}% higher than that of a Poisson occupancy with the same mean. This describes a static backlog plan sized with the long-run mean and is not a test of Poisson arrivals, because both logs change in volume over their span and a slowly varying volume alone produces such an excess.`),
];

const FM = S.failure;
const FI0 = FM.incidents, FB = FM.burstgpt, TC = FM.typed_capacity, MC = FI0.monthly_counts_all;
const FI = Object.fromEntries(Object.entries(FI0).filter(([k]) => !k.endsWith('__level_adjusted') && k !== 'monthly_counts_all'));
const FL = Object.fromEntries(Object.entries(FI).map(([k]) => [k, FI0[k + '__level_adjusted']]));
const aicgain = d => d.aic.nhpp - d.aic.hawkes;
const CM = TC.scenarios[3].c_H;
const scn = (c, d) => TC.scenarios.find(x => Math.abs(x.c_H - c) < 1e-6 && x.S_definition === d);
const DF = 'fine (10-min merge)', DC = 'coarse (60-min merge)', DV = 'coarse (60-min merge), volume-conditional dispersion';
const sec57 = [
  H2('5.7 Typed failure models on public production data'),
  P(`We now fit the process classes of Section 3.6 to the two public failure datasets (the numbers are produced by run_failure_models.py).`),
  H3('Provider incidents: weekly seasonality, a drifting level and mild self-excitation.'),
  P(`The incident rate was not constant over the 18 months: monthly counts were ${Math.min(...MC.counts.slice(0, 12))} to ${Math.max(...MC.counts.slice(0, 12))} in the first twelve months and ${Math.min(...MC.counts.slice(12))} to ${Math.max(...MC.counts.slice(12))} afterwards (homogeneity across months rejected, χ² = ${f0(MC.homogeneity_chi2)} on ${MC.df} df). With a fixed seasonal profile and a constant level, a self-exciting term improves the fit for every stream (Table C2; AIC gains of ${f0(Math.min(...Object.values(FI).map(aicgain)))} to ${f0(Math.max(...Object.values(FI).map(aicgain)))}, branching ratio ${f2(Math.min(...Object.values(FI).map(d => d.hawkes.alpha)))} to ${f2(Math.max(...Object.values(FI).map(d => d.hawkes.alpha)))}), but part of this is the slowly changing level, which the self-excitation term can mimic. Once the baseline is multiplied by a monthly level, the estimated branching ratio falls to ${f2(Math.min(...Object.values(FL).map(d => d.hawkes.alpha)))} to ${f2(Math.max(...Object.values(FL).map(d => d.hawkes.alpha)))} (mean cluster size ${f2(Math.min(...Object.values(FL).map(d => d.mean_cluster_size)))} to ${f2(Math.max(...Object.values(FL).map(d => d.mean_cluster_size)))} incidents, half-life ${f1(Math.min(...Object.values(FL).map(d => d.excitation_halflife_hours)))} to ${f1(Math.max(...Object.values(FL).map(d => d.excitation_halflife_hours)))} h), the AIC gains shrink to ${f0(Math.min(...Object.values(FL).map(aicgain)))} to ${f0(Math.max(...Object.values(FL).map(aicgain)))}, and the optimistic time-rescaling test no longer rejects the NHPP for the combined stream (p = ${f2(FL['all providers'].ks_rescaled_p_nhpp)}), for OpenAI, or for the major and critical subset. A weekday-and-hour profile with a drifting level therefore describes most of the data. A weak residual self-excitation remains, roughly one incident in 11 to 18 being followed by a clustered successor, with borderline evidence, and Anthropic's rescaling test still rejects the NHPP (p = ${f3(FL['Anthropic'].ks_rescaled_p_nhpp)}). The implied long-window Fano factor of ${f2(1 / (1 - FL['all providers'].hawkes.alpha) ** 2)} (Proposition 6b) is below the stratified dispersion index of ${f2(S.real_data.incidents.counts['all providers'].stratified_dispersion_index)} reported in Section 5.5, so part of the measured over-dispersion is the drifting level. The conclusion for planning is modest: provider incidents need a seasonal, level-adjusted baseline, and whether they also cluster is weakly supported and, at this rate, of small consequence.`),
  H3('Serving failures: heavy-tailed episodes.'),
  P(`In the BurstGPT trace, failed requests are concentrated. Outage-like episodes, defined as minutes with more than 20% failed requests and at least five failures, merged when ten minutes apart, cover ${pct(FB.share_of_minutes_in_episodes)} of active minutes and contain ${pct(FB.share_of_failures_in_episodes)} of all ${FB.failed_requests.toLocaleString('en-US')} failures (${f0(100 * Math.min(...FB.sensitivity.map(x => x.share_of_failures)))} to ${f0(100 * Math.max(...FB.sensitivity.map(x => x.share_of_failures)))}% across five definitions; Table C3). The ${FB.n_episodes} episodes have a median duration of ${f0(FB.episode_duration_minutes.median)} minutes (90th percentile ${f0(FB.episode_duration_minutes.p90)}, maximum ${f0(FB.episode_duration_minutes.max)}) and heavy-tailed sizes: median ${f0(FB.episode_size.median)} failed requests, mean ${f0(FB.episode_size.mean)}, 99th percentile ${comma(FB.episode_size.p99)}, maximum ${comma(FB.episode_size.max)}. A lognormal fit has σ = ${f2(FB.episode_size_lognormal.sigma)}. The Hill estimator on the upper 20% gives a tail index of about ${f1(FB.episode_size.hill_tail_index)}, which at this sample size cannot distinguish a Pareto tail with infinite variance from a lognormal, so we do not read it as evidence of infinite variance. What matters for Proposition 6c is the second-moment ratio E[X²]/E[X] of episode sizes, which is ${comma(FB.episode_size_second_moment_ratio.empirical_EX2_over_EX)} empirically and ${comma(FB.episode_size_second_moment_ratio.lognormal_implied)} under the lognormal fit. The Fano factor of failed-request counts that arrive in such episodes is thus in the thousands. Conditioning on daily request volume, which itself ranges from ${S.real_data.burstgpt.daily_requests.min} to ${S.real_data.burstgpt.daily_requests.max.toLocaleString('en-US')} requests, the Pearson dispersion of daily failed-request counts is ${comma(FB.failed_requests_conditional_on_volume.pearson_dispersion_daily)}, far from the value of about 1 for a Poisson-thinned stream. A Poisson description of failed requests is wrong by several orders of magnitude, even after allowing for traffic.`),
  P(`The episodes themselves are not Poisson either. They average ${f1(FB.episodes_per_day.mean)} per day, with a daily dispersion index of ${f1(FB.episodes_per_day.dispersion_index)} unconditionally and ${f1(FB.episodes_conditional_on_volume.pearson_dispersion_daily)} given daily volume, and their inter-arrival times have a coefficient of variation of ${f1(FB.episode_interarrival_hours.cv)}. A Hawkes process fits much better than an NHPP when the baseline is the hour-of-day profile (AIC ${f0(FB.hawkes_episodes.aic.nhpp)} → ${f0(FB.hawkes_episodes.aic.hawkes)}; branching ratio ${f2(FB.hawkes_episodes.hawkes.alpha)}, half-life ${f1(FB.hawkes_episodes.excitation_halflife_hours)} h), and also when the baseline is proportional to the hourly request volume (AIC ${f0(FB.hawkes_episodes_exposure_adjusted.aic.nhpp)} → ${f0(FB.hawkes_episodes_exposure_adjusted.aic.hawkes)}; branching ratio ${f2(FB.hawkes_episodes_exposure_adjusted.hawkes.alpha)}), although the rescaled-gap test still rejects the Hawkes fit. The branching ratio depends on how episodes are delimited (Table C3): it stays between ${f2(Math.min(...FB.sensitivity.map(x => x.hawkes_alpha)))} and ${f2(Math.max(...FB.sensitivity.map(x => x.hawkes_alpha)))} across five definitions and the heavy tail of sizes persists, but the unconditional daily dispersion index of episode counts ranges from ${f1(Math.min(...FB.sensitivity.map(x => x.dispersion_index_daily)))} to ${f1(Math.max(...FB.sensitivity.map(x => x.dispersion_index_daily)))}, and a long outage may be split into several fragments. Only the direction, clustering and heavy tails, is robust.`),
  H3('Capacity under the typed model.'),
  P(`To see what the typed description changes for a human-triage plan, we combine three human-handled classes for an illustrative organisation, using parameters from our estimates and treating the classes as independent. The first is hallucinations after the classifier-only cascade L1+L2 (λ_H = ${f1(TC.lambda_H)} per day, from the Qwen2.5-0.5B run). Its daily-rate coefficient of variation c_H is assumed to lie between 0.3 and 0.45, close to the ${f2(T3x[0].cv)} and ${f2(T3x[1].cv)} estimated net of trend for the two long ticket streams (${f2(T3x[0].cv_all)} and ${f2(T3x[1].cv_all)} with all days), so φ_H = 1 + λ_Hc_H² is ${f2(scn(0.3, DF).phi_H)} to ${f2(scn(0.45, DF).phi_H)} by Proposition 2. The second is provider incidents affecting the organisation (λ_P = ${f2(TC.P.lambda)}, φ_P = ${f2(TC.P.phi)} from the stratified index). The third is own serving-failure episodes (λ_S from the episode counts over the ${TC.days_recorded} recorded days), with φ_S = ${f1(scn(CM, DC).S_phi)} for the coarse definition, ${f1(scn(CM, DF).S_phi)} for the fine one and ${f1(scn(CM, DV).S_phi)} for the coarse definition conditioned on request volume.`),
  P(`Treating the total as one Poisson stream gives a 95% capacity of ${scn(CM, DF).all_classes.k_naive_poisson} units per day with the fine definition and ${scn(CM, DC).all_classes.k_naive_poisson} with the coarse one, at c_H = ${f2(CM)}. The typed superposition requires ${scn(CM, DF).all_classes.k_typed} and ${scn(CM, DC).all_classes.k_typed}, and the single-Poisson plan is exceeded on ${pct(scn(CM, DF).all_classes.naive_plan_exceeded_share)} and ${pct(scn(CM, DC).all_classes.naive_plan_exceeded_share)} of days instead of 5% (Monte Carlo of ${TC.mc_days.toLocaleString('en-US')} days; effective dispersion φ_eff = ${f1(scn(CM, DC).all_classes.effective_dispersion)} to ${f1(scn(CM, DF).all_classes.effective_dispersion)}, Proposition 6a). Across the nine scenarios (three values of c_H and three treatments of the serving class), required capacity is ${Math.min(...TC.scenarios.map(x => x.all_classes.k_typed))} to ${Math.max(...TC.scenarios.map(x => x.all_classes.k_typed))} units against a single-Poisson plan of ${Math.min(...TC.scenarios.map(x => x.all_classes.k_naive_poisson))} to ${Math.max(...TC.scenarios.map(x => x.all_classes.k_naive_poisson))}, which is ${f0(100 * Math.min(...TC.scenarios.map(x => x.all_classes.k_typed / x.all_classes.k_naive_poisson - 1)))} to ${f0(100 * Math.max(...TC.scenarios.map(x => x.all_classes.k_typed / x.all_classes.k_naive_poisson - 1)))}% more, and the single-Poisson plan is exceeded on ${pct(Math.min(...TC.scenarios.map(x => x.all_classes.naive_plan_exceeded_share)))} to ${pct(Math.max(...TC.scenarios.map(x => x.all_classes.naive_plan_exceeded_share)))} of days. The hallucination class alone, whose dispersion is assumed, accounts for a gap of ${f0(100 * (scn(CM, DF).H_only.k_typed / scn(CM, DF).H_only.k_naive_poisson - 1))}% (${scn(CM, DF).H_only.k_typed} rather than ${scn(CM, DF).H_only.k_naive_poisson} units). The provider class adds little, and the serving class widens the gap substantially only when it is treated as strongly over-dispersed (the fine episode definition, φ_S = ${f1(scn(CM, DF).S_phi)}).`),
  P(`This scenario illustrates the size of the single-Poisson error under stated assumptions. It is not evidence for the typed model. The class means are not those of any real organisation, the comparator is a single Poisson (a negative-binomial plan on the total would close part of the gap), and a serving outage would plausibly raise hallucination and ticket volumes at the same time, which would widen it.`),
];
const findings2 = [...sec55, ...sec56, ...sec57];

// supplementary tables for the appendix
const FIk = Object.keys(FI);
const sup = {
  C1: table('Table C1. Resolution and handling times of tickets (hours)',
    ['Stream / measure', 'n', 'Median', 'Mean', '90th pct', '99th pct', 'CV', 'Best fit (AIC) / Weibull shape'],
    [['Software company: creation to resolution', T3.software_company.resolution_calendar_hours], ['Software company: time in "in progress"', T3.software_company.in_progress_hours], ['ServiceNow: opened to resolved', T3.servicenow.resolution_calendar_hours], ['ServiceNow: Critical/High only', T3.servicenow.high_priority.resolution_calendar_hours], ['Italian help desk: first to last event', T3.italian_helpdesk.resolution_calendar_hours]]
      .map(([n, x]) => [n, x.n.toLocaleString('en-US'), f1(x.median), f1(x.mean), f0(x.p90), f0(x.p99), f1(x.cv), `${x.best_fit} / ${f2(x.weibull_shape)}`]),
    [3000, 700, 800, 800, 900, 900, 600, 1660],
    'Calendar hours including waiting states (customer, vendor, queue); the in-progress measure counts only time in that workflow state. Exponential fits are rejected in every case (KS p < 10⁻³⁰).'),
  C2: table('Table C2. Seasonal NHPP versus seasonal Hawkes process for provider-declared incidents (March 2023 to August 2024)',
    ['Stream', 'Incidents', 'Baseline', 'Branching ratio α', 'Mean cluster size 1/(1−α)', 'Excitation half-life (h)', 'AIC gain over NHPP', 'LR test vs NHPP (bootstrap p)', 'Rescaled-gap KS p: NHPP → Hawkes'],
    FIk.flatMap(k => [[k === 'impact>=2' ? 'major/critical (impact ≥ 2)' : k, FI[k].n, 'profile, constant level', f2(FI[k].hawkes.alpha), f2(FI[k].mean_cluster_size), f1(FI[k].excitation_halflife_hours), f1(aicgain(FI[k])), `${f1(FI[k].lr)} (${FI[k].bootstrap_p <= 0.0051 ? '≤0.005' : f3(FI[k].bootstrap_p)})`, `${sci(FI[k].ks_rescaled_p_nhpp)} → ${f2(FI[k].ks_rescaled_p_hawkes)}`],
      ['', '', 'profile × monthly level', f2(FL[k].hawkes.alpha), f2(FL[k].mean_cluster_size), f1(FL[k].excitation_halflife_hours), f1(aicgain(FL[k])), `${f1(FL[k].lr)} (${f3(FL[k].bootstrap_p)})`, `${sci(FL[k].ks_rescaled_p_nhpp)} → ${f2(FL[k].ks_rescaled_p_hawkes)}`]]),
    [1300, 700, 1350, 850, 950, 850, 800, 1250, 1310],
    'Baseline: weekday/weekend × hour-of-day profile estimated from the incident data and held fixed; the second row of each stream additionally multiplies it by a monthly level estimated from monthly counts. Exponential excitation kernel; bootstrap p from 200 parametric simulations under the corresponding NHPP (smallest possible value 0.005). KS: Kolmogorov-Smirnov test of time-rescaled gaps against Exp(1) with the fitted compensator; the p-values are optimistic because the profile (48 slots), the monthly levels and the Hawkes parameters are all fitted on the same events.'),
  C3: table('Table C3. Sensitivity of the BurstGPT failure-episode model to the episode definition',
    ['Failure-share threshold', 'Min. failures per minute', 'Merge gap (min)', 'Episodes', 'Share of failures', 'Daily dispersion index', 'Hawkes α', 'Median / 99th pct size'],
    FB.sensitivity.map(x => [pct(x.rate_thr), x.min_fail, x.merge_gap_min, x.n_episodes, pct(x.share_of_failures), f1(x.dispersion_index_daily), f2(x.hawkes_alpha), `${f0(x.median_size)} / ${f0(x.p99_size)}`]),
    [1300, 1100, 1000, 900, 1100, 1200, 900, 1860], 'The first row (20%, 5, 10) is the definition used in the text. Hawkes fits use 30 bootstrap replications and hour-of-day baselines.'),
};
module.exports = { findings2, sup };
