const { P, PN, H1, H2, H3, BUL, table, run, d, fix } = require('./lib');
const S = require('../../runs/summary.json');
const R = ['qwen05', 'smol360', 'qwen15'];
const f0 = x => Math.round(x), f1 = x => x.toFixed(1), f2 = x => x.toFixed(2);
const pct = x => (100 * x).toFixed(1) + '%';
const rg = (a, d = 0) => { const lo = Math.min(...a).toFixed(d), hi = Math.max(...a).toFixed(d); return lo === hi ? lo : `${lo} to ${hi}`; };
const usd2 = x => { const v = Math.round(x); return (v < 0 ? '-$' : '$') + Math.abs(v).toLocaleString('en-US'); };
const cfgk = (r, c) => S[r].sla500.configs.find(x => x.config === c);
const T3 = S.triage, FM = S.failure, TC = FM.typed_capacity;
const meanPlan = R.flatMap(r => [...Object.values(S[r].sla500.poisson_checks), ...Object.values(S[r].burst.poisson_checks)].map(v => 100 * v.p_exceed_mean_capacity_observed));
const none3 = R.map(r => 100 * S[r].burst.poisson_checks.none.p_exceed_k_star_observed), none44 = R.map(r => 100 * S[r].burst044.poisson_checks.none.p_exceed_k_star_observed);
const best3 = R.map(r => 100 * S[r].burst.poisson_checks['L1+L2'].p_exceed_k_star_observed), best44 = R.map(r => 100 * S[r].burst044.poisson_checks['L1+L2'].p_exceed_k_star_observed);
const red = R.map(r => 100 * (1 - cfgk(r, 'L2').k_star / cfgk(r, 'none').k_star));
const fb = R.map(r => 100 * S[r].false_block_share_of_good.L2);
const tcr = TC.scenarios.map(x => 100 * (x.all_classes.k_typed / x.all_classes.k_naive_poisson - 1));
const dsr = R.map(r => S[r].dependence_stats.ratio_no_routing.point), dsrr = R.map(r => S[r].dependence_stats.ratio_with_routing.point);
const SXA = [T3.software_company.arrivals_excl_low_days, T3.italian_helpdesk.arrivals_excl_holidays, T3.servicenow.arrivals_excl_low_days];
const SA = [T3.software_company.arrivals, T3.italian_helpdesk.arrivals, T3.servicenow.arrivals];
const ccvx = SXA.map(a => a.detrended.implied_daily_rate_cv), ccva = SA.map(a => a.detrended.implied_daily_rate_cv);
const causx = [SXA[0].causal.poisson_plan_exceeded, SXA[1].causal.poisson_plan_exceeded].map(x => 100 * x);
const sav = R.map(r => S[r].cost_saving_ci['L1+L2+L3 vs L1+L2']);

const discussion = [
  H1('6. Discussion'),
  H2('6.1 Contributions to research'),
  P(`The paper offers an operations view of generative AI that complements the governance and adoption perspectives common in IS research (Berente et al. 2021; Raisch and Krakowski 2021). If a human reserve backs every guardrailed LLM service, the quantity that links a detector's accuracy to an organisation's cost is the quantile of a daily incident count. Expressing both in one unit, capacity or dollars per day, lets detectors, service levels and standing on-call arrangements be compared on a common scale, and it makes the human side of human-AI collaboration something that can be dimensioned and not only described.`),
  P(`Three modelling results travel beyond our data. Over-dispersion inflates required capacity in a way that a normal approximation with the dispersion index understates when the day-to-day variation has a fixed coefficient of variation (Proposition 2), and the inflation is largest precisely where capacity is largest, because independent thinning by guardrails leaves the coefficient of variation unchanged and shrinks the dispersion index (Proposition 3). The multiplicative guardrail formula is the independence special case of dependence bounds and, under positive association, a lower bound on residual risk (Proposition 4), so that the dependence between layers has to be measured before a stack is credited with its nominal effectiveness. And because capacity is integer-valued and standing staff has a floor, cost is not unimodal in the number of layers, so no fixed depth follows from the cost model (Proposition 5). The typed treatment of failure classes (Proposition 6) adds a modelling discipline: hallucinations, provider incidents, serving failures and human service each violate the Poisson assumptions in a different way, and combining them as one Poisson stream misdescribes all of them.`),
  P(`As design science, the study evaluates an artifact against measured behaviour and not only against a stylised model, and it reports where the artifact does not deliver. The two negative results are informative in this respect. An NLI classifier that looked effective at reducing capacity was in fact blocking nearly everything, and a routed LLM judge whose benefit seemed clear when slow verdicts were credited lost it under a realistic fail-open timeout. Both illustrate why capacity savings should always be reported together with false-block rates and latency.`),
  H2('6.2 Implications for practice'),
  P(`Operators should size standby capacity from a quantile of the daily count and should fit the dispersion first. Provisioning at the mean load was exceeded on ${rg(meanPlan)}% of days across the configurations we replayed. The Poisson quantile fixes this when counts are Poisson, but a modest day-to-day variation in demand (a coefficient of variation of 0.3 to 0.44) raised the exceedance rate of a Poisson-sized plan from 5% to ${rg(none3)}% and ${rg(none44)}% without guardrails, which follows from the injected multiplier and confirms the proposition on measured outcomes. Real LLM request streams vary far more than that, as the BurstGPT stress test shows. Over-dispersion matters most for large incident streams and least for small ones: provider outages at about 0.8 per day and dated hallucination cases at about six per weekday were statistically over-dispersed yet changed the 95% capacity by at most one unit, whereas the ServiceNow segment (about 350 tickets per work day, with the Poisson plan exceeded on ${f0(100 * SXA[2].detrended.poisson_local_plan_exceeded)}% of work days even after excluding holidays and bridge days) and an unprotected hallucination stream of more than 100 events per day were affected strongly.`),
  P(`The value of a guardrail is an empirical, per-deployment quantity. In our data one task-specific verifier delivered most of the benefit, with a ${rg(red)}% reduction in required capacity at the price of ${rg(fb)}% of correct answers blocked. The deterministic layer was nearly inert, and the routed judge's gain was small (k* reduced by ${R.map(r => cfgk(r, 'L2').k_star - cfgk(r, 'L2+L3').k_star).join(', ')} units) and indistinguishable from zero in cost terms (paired intervals for the daily saving ${R.map((r, i) => `${usd2(sav[i].saving_point)} [${sav[i].ci.map(usd2).join(', ')}]`).join('; ')}), at about three times the latency. A fixed "three layers" prescription is not supported; the method selects the stack from measurements. Routing is a first-order design choice in its own right. Sending only low-agreement answers to the expensive judge cuts judge calls by roughly an order of magnitude, but the share of hallucinations passing the L2+L3 cascade was ${rg(dsrr, 1)} times the independence prediction with routing against ${rg(dsr, 1)} times without it.`),
  P(`Failure classes should be modelled separately and combined at the ticket level. In our illustrative organisation a typed superposition required ${rg(tcr)}% more daily capacity than a single Poisson on the total across nine scenarios. The size of the gap is driven by the assumed over-dispersion of the hallucination class and by how strongly over-dispersed the serving class is taken to be, so the example shows how large the single-Poisson error can be under stated assumptions and is not a validated gain. Finally, human triage is bursty and heavy-tailed in real organisations. In public ticket streams the day-to-day coefficient of variation of the arrival rate was ${rg(ccvx, 2)} net of trend after excluding holiday and low-volume days (${rg(ccva, 2)} with all days), and resolution times had coefficients of variation of ${rg([T3.software_company.resolution_calendar_hours.cv, T3.servicenow.resolution_calendar_hours.cv, T3.italian_helpdesk.resolution_calendar_hours.cv], 1)} with decreasing hazards. In the one stream with handling-time data the 95th percentile of the daily workload was ${f1(T3.software_company.workload.workload_q95_over_mean)} times its mean, against ${f1(T3.software_company.workload.count_q95_over_mean)} for the arrival count. Capacity in arrivals is therefore not capacity in hours, and the service-time tail needs its own headroom.`),
  H2('6.3 Limitations and future research'),
  P(`The most important limitation is that arrivals are simulated and that no operator log of hallucinations is public. Outcomes are measured on real model outputs, but arrival times are generated and each arrival replays a bootstrapped example, so the Poisson and time-rescaling checks of Section 5.3 verify the machinery and are partly true by construction. The public traces we use are real production data, but they record requests, service incidents and human tickets, not hallucinations. The one dated hallucination log we found, a database of court decisions, is domain-specific, has day resolution and carries strong detection and reporting bias. The burstiness of the replay is therefore a scenario informed by real streams and not estimated from them. Validation on proprietary incident logs, even a few months of daily counts of hallucination-related tickets, is the most valuable follow-up. A closely related assumption is that every hallucination passing the guardrails is detected and becomes one human-handled event. In practice only a fraction is noticed or reported, so the capacities we report are upper bounds that hold under full detection (Section 3.1), and the detection process deserves a model of its own.`),
  P(`The evaluation is small and partly post hoc. The three generators answered the same 300 questions, so their results are paired and not independent replications, and each layer estimate rests on 141 to 195 hallucinations and on a few to a few dozen residual ones. The extractive verifier was introduced after the NLI classifier proved uninformative, so the choice of L2 was made after seeing results on the same data. It is trained on SQuAD, which flatters it, and its threshold was not tuned. The judge is the same 1.5B model in every run, so one arm is self-judged. The analyses should be repeated on a held-out sample with a pre-registered layer configuration. The dependence estimates are imprecise: the association between L2 and L3 and the excess over the independence formula are weak, their bootstrap intervals include zero or one for two of the three generators, and the independence prediction is computed from the same sample's marginals. The judge results also assume that verdicts of calls slower than 2 s are discarded (Section 5.4), and the evaluation uses small open models, 0.4 to 1.5 billion parameters, on one extractive task with CPU latencies. Absolute hallucination rates are far higher than for frontier models, and latencies on GPUs or hosted inference differ. The method transfers; the numbers do not. Ground truth rests on string and token-F1 matching against SQuAD gold answers, which can mark valid paraphrases as hallucinations and inflates the base rate, and the cost parameters and selection weights are assumptions, so only the labour-to-compute ratio and the sensitivity grid are informative.`),
  P(`The typed models and the public data carry their own caveats. The Hawkes and episode fits use a single kernel family, a fixed seasonal profile estimated from the same data and, for BurstGPT, an episode definition that matters quantitatively and may split a long outage into fragments; bootstrap p-values are bounded below by 1/(B + 1) and the time-rescaling p-values are optimistic. The capacity comparison of Section 5.7 combines classes from different organisations and datasets under independence, with an assumed hallucination dispersion and a single Poisson as comparator, and common-cause dependence between classes would widen the gap. The ticket streams are customer-support and IT incidents and not LLM incidents. Whether hallucination tickets share their arrival variability and service times is an assumption that is plausible for the coefficient of variation of the daily rate, which is invariant to independent thinning with constant p, and less so for service times, which depend on the verification task. Resolution times are calendar times that include waiting for customers or vendors and are not triage effort. Ticket volumes in two of the logs change over their span, the ServiceNow log supports only a 12-week segment, and the arrival-variability estimates rest on three streams. Isolated low-count days such as holidays and bridge days inflate dispersion that a local mean cannot absorb; we report results with and without them, using a volume rule for two streams and holiday calendars for two others, and the outcome-based volume rule is not applied to low-rate streams. The conservatism of the causal negative-binomial plan, which we cannot explain, shows that our variability estimates are not fully understood. BurstGPT has no calendar dates, a 104-day gap, near-duplicate day pairs and order-of-magnitude regime changes in daily volume, so its day-level variability reflects growth and logging as well as chance, and we use it only as a stress test.`),
  P(`Future work could proceed along three lines. The first is validation on production incident logs from operators, which would allow the counting-process assumptions to be tested directly and the dispersion of hallucination counts to be estimated and not assumed. The second is to model detection and triage explicitly, including the delay between an incident and its handling, so that capacity can be expressed as a function of response-time targets and not only of daily counts. The third is to study how guardrail dependence changes with the generator, the domain and adversarial pressure, since the evidence here concerns one task and three small models.`),
];
const conclusion = [
  H1('7. Conclusion'),
  P(`Treating human-handled LLM incidents as a counting process turns guardrail performance into a staffing and cost decision. Under the assumptions stated, capacity should be sized from an over-dispersion-aware quantile of the daily count. The multiplicative guardrail formula is an optimistic bound whose gap has to be measured. A single Poisson on all failures misdescribes every class, because hallucinations are over-dispersed through demand variability, provider incidents are seasonal with a drifting level and weak clustering, and serving failures arrive in heavy-tailed episodes. The cost-minimising number of layers depends on integer capacity effects, the floor on standing staff, latency, the labour-to-compute ratio and the measured clearance, and it is not fixed at three.`),
  P(`On the measured outputs of three small open models, a single task-specific verifier reduced required capacity by ${rg(red)}% relative to no guardrails while blocking ${rg(fb)}% of correct answers, and a routed judge did not demonstrably pay for itself under a 2 s fail-open timeout. Mild burstiness raised the exceedance rate of a Poisson-sized plan from 5% to roughly ${f0(Math.min(...none3))} to ${f0(Math.max(...none44))}% without guardrails and ${f0(Math.min(...best3, ...best44))} to ${f0(Math.max(...best3, ...best44))}% with the best cascade. Public production data corroborate the structure of the arrival processes: an LLM request trace shows clustered arrivals from the 10-second scale upward, provider incident streams are strongly seasonal with a drifting level, and company ticket streams show a net-of-trend daily-rate coefficient of variation of ${rg(ccvx, 2)} and heavy-tailed resolution times. Hallucination arrivals themselves are simulated, however, and no operator log is public. Testing the counting-process assumptions on production incident logs is the necessary next step.`),
];

// ------------------------------------------------------------------ appendices
const H1a = t => H1(t);
const appendix = [
  H1('Appendix A. Proofs'),
  PN(`**Proof of Proposition 1.** (a) The Poisson(λ) distribution is stochastically increasing in λ, so P(X ≤ k) is non-increasing in λ and the smallest k that reaches α cannot fall as λ rises. (b) k* = 0 exactly when P(X = 0) = e^{−λ} ≥ α, that is, when λ ≤ −ln α. (c) For λ in [n, n + 1) with n ≥ 1, P(X > n) increases in λ, so its minimum on that interval is P(Poisson(n) > n). The sequence P(Poisson(n) > n) increases in n towards 1/2, and its first term is P(Poisson(1) > 1) = 1 − 2e⁻¹ = 0.264. At λ = 3 it equals 1 − P(X ≤ 3) = 0.353. (d) is the Cornish-Fisher expansion of the Poisson quantile. ∎`),
  PN(`**Proof of Proposition 2.** (a) is the law of total variance: Var(X_d) = E[λM] + Var(λM) = λ + λ²c². (b) For Poisson Y_λ, ∂E[(Y_λ − k)⁺]/∂λ = P(Y_λ ≥ k), which is non-decreasing in λ, so λ ↦ E[(Y_λ − k)⁺] is convex. Jensen's inequality applied to the mixing variable gives E[(X_d − k)⁺] = E[g(λM)] ≥ g(λ), where g(λ) = E[(Y_λ − k)⁺]. (c) If φ is bounded, the count is asymptotically normal with variance λφ. For fixed c, X_d/λ converges in distribution to M as λ grows, so the α-quantile of X_d is asymptotically λF_M⁻¹(α), and the normal approximation fails by an amount linear in λ. ∎`),
  PN(`**Proof of Proposition 3.** Under binomial thinning with constant probability p, Var(N_p) = p²Var(N) + p(1 − p)μ by the law of total variance. Dividing by E[N_p] = pμ gives pF + (1 − p) = 1 + p(F − 1). The statement about c follows because thinning multiplies the intensity of each day by p and leaves the multiplier M unchanged. We also verified the identity by simulation (checks/check_thinning.py). ∎`),
  PN(`**Proof of Proposition 4.** The bounds are the Fréchet-Bonferroni bounds for the probability that no layer fires: 1 − Σc_i ≤ P(no layer fires) ≤ 1 − max_i c_i, with the lower bound truncated at zero. If the indicators of catching are positively associated, P(∩{I_i = 0}) ≥ ΠP(I_i = 0) (Esary et al. 1967). Multiplying by λ₀ gives the stated bounds on λ_N, and Proposition 1(a) transfers them to k*. ∎`),
  PN(`**Proof of Proposition 5.** (a) Table 3 is a counterexample to unimodality. (b) For N > N₀ the labour cost is constant at C_hk_min while compute cost increases in N, so such N are dominated by N₀. (c) Write f(N) = g[N + θK(N)] with K(N) = max{k_min, k*(α, λ_N)} non-increasing in N. The difference f(N + 1) − f(N) = g[1 + θ(K(N + 1) − K(N))] is non-increasing in θ, so f has decreasing differences in (N, θ) and the largest minimiser is non-decreasing in θ by Topkis' (1978) monotone comparative statics. (d) is immediate. ∎`),
  PN(`**Proof of Proposition 6.** (a) Variances of independent counts add, and the normal approximation of the quantile uses the total variance; the factor √φ_eff is the ratio of the resulting safety stock to that of a Poisson with the same mean. (b) The cluster generated by a background event is a Galton-Watson tree with Poisson(α) offspring. Its total progeny is Borel(α) with mean 1/(1 − α) and second moment 1/(1 − α)³, so E[X²]/E[X] = 1/(1 − α)², and the stationary variance-to-mean ratio of the count of a Hawkes process equals this value in the long-window limit. (c) is Wald's identity for the compound Poisson variance, Var(N) = νE[X²]. ∎`),

  H1('Appendix B. Public Data: Sources, Filters and Estimators'),
  PN(`**BurstGPT.** The trace (Wang et al. 2025; CC BY 4.0) holds 10.6 million request records of regional Azure OpenAI ChatGPT and GPT-4 services at one-second resolution over 231 days, in two contiguous segments of 121 and 110 days separated by an unrecorded gap of 104 days. Timestamps are seconds from an undisclosed day 0, so weekday labels are unknown. Failed requests are rows with zero response tokens. We estimate the hour-of-day profile, the day-to-day variability of request volume (robustly, because volume grows by two orders of magnitude and contains regime shifts) and the within-hour Fano factor of counts at 1 s, 10 s, 1 min and 10 min. The stress test replays the measured daily multipliers, rescaled to mean 1, on event streams with a given mean.`),
  PN(`**Provider incidents.** The dataset of LLM service outages and incident reports (Chu et al. 2025; CC BY 4.0) contains provider-declared incidents scraped from the status pages of OpenAI, Anthropic and Character.AI. We use the 457 incidents starting in March 2023, when all three pages are populated. We test Poisson counts per day and week (index of dispersion, also stratified by day of week), day-of-week and hour-of-day homogeneity, exponential inter-arrival times after time-rescaling with a fitted hour-of-week intensity, the distribution of incident durations as a proxy for human response time, and the number of concurrently open incidents against the M/G/∞ prediction.`),
  PN(`**Ticket logs.** The software-company data (Abdellatif 2026) contain 66,691 rows; we keep tickets of type "Ticket" created in 2017 or later and resolved as "Done", which leaves 22,016 tickets with creation, resolution and in-progress times. The work week is detected from the data as the five busiest days (Sunday to Thursday for this company, Monday to Friday for the others). The ServiceNow log (Amaral et al. 2018; 24,918 incidents in 2016 to 2017) has 98.9% of its incidents opened between 29 February and 1 June 2016, so its arrival analysis uses only the middle weeks (7 March to 27 May 2016) and its concurrency is not analysed. The Italian help-desk log (Verenich 2016) contains 3,804 cases from 2010 to 2012. A High/Highest/Blocker subset of the software company is not analysed because its rate rises from about zero to eleven tickets per work day over 2017 to 2023, which reflects a change in the priority field.`),
  PN(`**Holiday and low-volume exclusions.** Holidays and bridge days produce isolated low-count days that a local mean cannot absorb, so every arrival analysis is reported twice. For the software company and ServiceNow we exclude work days with fewer than 35% of the centred 41-work-day rolling median (62 and 5 days), a rule that is reliable only for high-rate streams. For the Italian help desk we exclude Italian national holidays and Easter Monday (26 days), and for the court cases US federal holidays (10 days).`),
  PN(`**Estimators.** For each stream we estimate weekday-stratified over-dispersion, the daily-rate coefficient of variation net of slow trends (the Pearson dispersion of weekday counts against a leave-one-out local mean over about eight weeks, after removing the weekday effect), the exceedance rate of Poisson-sized capacity plans, the distribution of resolution and in-progress times (exponential, lognormal and Weibull fits compared by AIC), the daily workload safety factor (95th percentile over mean of handling hours, against arrivals) and the number of concurrently open tickets against the M/G/∞ prediction. The Poisson plan is evaluated twice: against a two-sided local mean over about 40 surrounding work days (in-sample, not a feasible forecast) and causally, with the trailing 20-work-day mean and a coefficient of variation estimated on earlier days only (rolling origin). Weekday effects and the work-week definition are estimated on the full sample, so only the level and the coefficient of variation are strictly causal.`),
  PN(`**Court cases.** The Charlotin database (Charlotin 2026; CC BY 4.0, accessed 6 October 2026) lists court decisions with AI-fabricated content. We use the decision date at day resolution for October 2025 to August 2026 and analyse weekday counts with the same stratified and local-mean estimators as for tickets. September 2026 (95 cases) and one case in October 2026 are excluded because of reporting lag.`),
  PN(`**Typed failure models.** The Hawkes estimator was checked by simulation (recovery of μ₀, α and β from synthetic seasonal Hawkes data, and no false excitation when α = 0; checks/check_hawkes_recovery.py). The parametric-bootstrap likelihood-ratio test uses 200 simulations under the NHPP, because the boundary α = 0 invalidates the usual chi-square reference. For BurstGPT failures, outage-like episodes are minutes with more than 20% failed requests and at least five failures, merged when at most ten minutes apart. The Monte Carlo of Section 5.7 simulates 400,000 days (seed 0); the hallucination class uses the measured L1+L2 rate for Qwen2.5-0.5B and an assumed daily-rate coefficient of variation of 0.3 to 0.45, the provider class uses the rate and stratified dispersion index of Section 5.5, and the serving class uses the episode rate over the 231 recorded days with the dispersion index under three treatments.`),

  H1('Appendix C. Supplementary Tables'),
];

const refs = [
  'Abdellatif, M. 2026. "Help Desk Tickets (Version 3)," Mendeley Data (https://doi.org/10.17632/btm76zndnt.3).',
  'Abraham, S., Chen, T., Chhun, C., Jaramillo-Gutierrez, G., Mylius, S., Raaj, S., Slattery, P., and McGregor, S. 2026. "AI Incident Monitoring Through a Public Health Lens," arXiv:2604.19914.',
  'Allal, L. B., Lozhkov, A., Bakouch, E., Blázquez, G. M., Penedo, G., Tunstall, L., Marafioti, A., Kydlíček, H., Piqueres Lajarín, A., Srivastav, V., Lochner, J., Fahlgren, C., Nguyen, X.-S., Fourrier, C., Burtenshaw, B., Larcher, H., Zhao, H., Zakka, C., Morlon, M., Raffel, C., von Werra, L., and Wolf, T. 2025. "SmolLM2: When Smol Goes Big—Data-Centric Training of a Small Language Model," arXiv:2502.02737.',
  'Alotaibi, A., Jabbar, M. S., Al-Azani, S., and Ahmed, M. 2026. "Layered LLM Defenses as an Ensemble: Access Tiers, Inference Cost, and the Measured Failure Correlation Between Defense Layers," arXiv:2608.28327.',
  'Amaral, C. A. L., Fantinato, M., and Peres, S. M. 2018. "Incident Management Process Enriched Event Log," UCI Machine Learning Repository (dataset 498).',
  'Bartolucci, S., and Vivo, P. 2026. "Queue & AI: When Faster Tasks Slow Down the Workflow," arXiv:2605.27202.',
  'Berente, N., Gu, B., Recker, J., and Santhanam, R. 2021. "Managing Artificial Intelligence," MIS Quarterly (45:3), pp. 1433-1450.',
  'Besanson, G. 2026. "SARC: A Governance-by-Architecture Framework for Agentic AI Systems," arXiv:2605.07728.',
  'Bhardwaj, V. P., Singh, G., and Bhardwaj, A. P. 2026. "Agent Behavioral Contracts II: Certifying Compositional Reliability Without Assuming Independence," arXiv:2608.12895.',
  'Brown, L., Gans, N., Mandelbaum, A., Sakov, A., Shen, H., Zeltyn, S., and Zhao, L. 2005. "Statistical Analysis of a Telephone Call Center: A Queueing-Science Perspective," Journal of the American Statistical Association (100:469), pp. 36-50.',
  'Cameron, A. C., and Trivedi, P. K. 1998. Regression Analysis of Count Data. Cambridge, UK: Cambridge University Press.',
  'Charlotin, D. 2026. "AI Hallucination Cases Database" (https://www.damiencharlotin.com/hallucinations/; CC BY 4.0; accessed October 6, 2026).',
  'Chu, X., Talluri, S., Lu, Q., and Iosup, A. 2025. "An Empirical Characterization of Outages and Incidents in Public Services for Large Language Models," in Proceedings of ICPE 2025 (arXiv:2501.12469).',
  'Cox, D. R. 1955. "Some Statistical Methods Connected with Series of Events," Journal of the Royal Statistical Society, Series B (17:2), pp. 129-164.',
  'Cox, D. R., and Isham, V. 1980. Point Processes. London: Chapman & Hall.',
  'Daley, D. J., and Vere-Jones, D. 2003. An Introduction to the Theory of Point Processes, Volume I (2nd ed.). New York: Springer.',
  'Esary, J. D., Proschan, F., and Walkup, D. W. 1967. "Association of Random Variables, with Applications," Annals of Mathematical Statistics (38:5), pp. 1466-1474.',
  'Green, L. V., Kolesar, P. J., and Whitt, W. 2007. "Coping with Time-Varying Demand When Setting Staffing Requirements for a Service System," Production and Operations Management (16:1), pp. 13-39.',
  'Gregor, S., and Hevner, A. R. 2013. "Positioning and Presenting Design Science Research for Maximum Impact," MIS Quarterly (37:2), pp. 337-355.',
  'Hawkes, A. G. 1971. "Spectra of Some Self-Exciting and Mutually Exciting Point Processes," Biometrika (58:1), pp. 83-90.',
  'He, P., Gao, J., and Chen, W. 2021. "DeBERTaV3: Improving DeBERTa Using ELECTRA-Style Pre-Training with Gradient-Disentangled Embedding Sharing," arXiv:2111.09543.',
  'Hevner, A. R., March, S. T., Park, J., and Ram, S. 2004. "Design Science in Information Systems Research," MIS Quarterly (28:1), pp. 75-105.',
  'Inan, H., Upasani, K., Chi, J., Rungta, R., Iyer, K., Mao, Y., Tontchev, M., Hu, Q., Fuller, B., Testuggine, D., and Khabsa, M. 2023. "Llama Guard: LLM-Based Input-Output Safeguard for Human-AI Conversations," arXiv:2312.06674.',
  'Ji, Z., Lee, N., Frieske, R., Yu, T., Su, D., Xu, Y., Ishii, E., Bang, Y. J., Chen, D., Dai, W., Chan, H. S., Madotto, A., and Fung, P. 2023. "Survey of Hallucination in Natural Language Generation," ACM Computing Surveys (55:12), Article 248.',
  'Kingman, J. F. C. 1993. Poisson Processes. Oxford, UK: Oxford University Press.',
  'Lewis, P., Perez, E., Piktus, A., Petroni, F., Karpukhin, V., Goyal, N., Küttler, H., Lewis, M., Yih, W.-t., Rocktäschel, T., Riedel, S., and Kiela, D. 2020. "Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks," Advances in Neural Information Processing Systems (33).',
  'Lin, R., and Zhang, J. 2026. "When to Screen, When to Bypass: LLM-Judges in Resource-Scarce AI-Human Workflow," arXiv:2603.13870.',
  'Manakul, P., Liusie, A., and Gales, M. J. F. 2023. "SelfCheckGPT: Zero-Resource Black-Box Hallucination Detection for Generative Large Language Models," in Proceedings of EMNLP 2023.',
  'Ogata, Y. 1988. "Statistical Models for Earthquake Occurrences and Residual Analysis for Point Processes," Journal of the American Statistical Association (83:401), pp. 9-27.',
  'Qwen Team. 2024. "Qwen2.5 Technical Report," arXiv:2412.15115.',
  'Raisch, S., and Krakowski, S. 2021. "Artificial Intelligence and Management: The Automation-Augmentation Paradox," Academy of Management Review (46:1), pp. 192-210.',
  'Rajpurkar, P., Jia, R., and Liang, P. 2018. "Know What You Don\'t Know: Unanswerable Questions for SQuAD," in Proceedings of ACL 2018, pp. 784-789.',
  'Topkis, D. M. 1978. "Minimizing a Submodular Function on a Lattice," Operations Research (26:2), pp. 305-321.',
  'Tran-Truong, P. T., and Le, X.-B. 2026. "Measuring the Unmeasurable: Markov Chain Reliability for LLM Agents," arXiv:2604.24579.',
  'Verenich, I. 2016. "Helpdesk" (help desk log of an Italian software company), Mendeley Data, V1 (https://doi.org/10.17632/39bp3vv62t.1).',
  'Wang, Y., Chen, Y., Li, Z., Kang, X., Fang, Y., Zhou, Y., Zheng, Y., Tang, Z., He, X., Guo, R., Wang, X., Wang, Q., Zhou, A. C., and Chu, X. 2025. "BurstGPT: A Real-World Workload Dataset to Optimize LLM Serving Systems," in Proceedings of KDD 2025 (arXiv:2401.17644).',
  'Whitt, W. 2007. "What You Should Know About Queueing Models to Set Staffing Requirements in Service Systems," Naval Research Logistics (54:5), pp. 476-484.',
  'Zheng, L., Chiang, W.-L., Sheng, Y., Zhuang, S., Wu, Z., Zhuang, Y., Lin, Z., Li, Z., Li, D., Xing, E. P., Zhang, H., Gonzalez, J. E., and Stoica, I. 2023. "Judging LLM-as-a-Judge with MT-Bench and Chatbot Arena," Advances in Neural Information Processing Systems (36).',
];
const REFS = [H1('References'), ...refs.sort((x, y) => x.localeCompare(y)).map(r => new d.Paragraph({ children: [run(fix(r), { size: 22 })], spacing: { after: 100, line: 276 }, indent: { left: 720, hanging: 720 } }))];

const appendixEnd = [
  H1('Appendix D. Reproducibility and Data Availability'),
  P(`All code, per-query model outputs, guardrail decisions and analysis scripts are provided in an anonymised repository, the link to which is supplied to the editors with the submission. The experiments run in the order collect (run_experiment.py collect), re-time with the extractive verifier (retime), analyse (run_experiment.py analyze, run_all_analyses.sh), summarise (summarize.py) and build the figures, tables and manuscript (make_figures.py, paper_tables.py, paper/misq/build.js), and every number in the text and tables is generated from the resulting JSON files. The public datasets are not redistributed; they are available from their original sources under the licences stated in Section 4.5 and Appendix B (BurstGPT and the outage dataset under CC BY 4.0, the court-case database under CC BY 4.0, and the ticket logs from Mendeley Data and the UCI repository). Generator and verifier checkpoints are the public Hugging Face releases named in Section 4. All simulations and bootstrap draws are seeded.`),
  H1('Appendix E. Use of Generative AI Tools'),
  P(`[Template to be completed by the authors in line with the journal's policy.] Generative AI tools were used in the development of the analysis code and in drafting and language editing of the manuscript. The authors specified the research design, reviewed and verified all code, analyses, numerical results and references, revised the text, and take full responsibility for the content of the paper. The tools are not listed as authors.`),
];
module.exports = { discussion, conclusion, appendix, REFS, appendixEnd };
