const { P, H1, H2, BUL, table } = require('./lib');
const method = [
  H1('4. Empirical Design'),
  H2('4.1 Data, models and ground truth'),
  P('We use the SQuAD 2.0 validation set (Rajpurkar et al., 2018), which combines answerable questions with questions that the supplied passage cannot answer. A random sample of 300 questions (seed 0) is drawn for each model. Each model receives the passage and the question and must reply with a short answer or the token UNANSWERABLE. A response is labelled a **critical hallucination** if it is not an abstention and either (i) the question is answerable and the answer matches no gold answer (normalised containment or token-F1 ≥ 0.6) or (ii) the question is unanswerable. Abstentions are never counted as hallucinations and bypass the guardrails. The generators are Qwen2.5-0.5B-Instruct, SmolLM2-360M-Instruct and Qwen2.5-1.5B-Instruct (Qwen Team, 2024; Allal et al., 2025), run greedily on CPU. We use small open models because they can be run end-to-end with full control and measured latency; their hallucination rate is higher than that of frontier models, so absolute rates should not be transferred (Section 6).'),
  H2('4.2 Guardrail layers'),
  P('The three layers follow the asymmetric architecture of the earlier draft, but each is implemented and executed on every answer:'),
  BUL('**L1, deterministic.** Regular expressions for e-mail, SSN, card and phone patterns; template-token leakage; degenerate repetition; and a grounding heuristic that blocks answers containing a number absent from the evidence passage.'),
  BUL('**L2, classifier.** A small NLI cross-encoder (DeBERTa-v3-small; He et al., 2021) scoring P(passage entails "the answer to Q is A"); the output is blocked if this probability is below 0.5. (The earlier draft named Llama Guard-type models for this layer; these target safety policy violations, not factual grounding, so an entailment classifier is the appropriate classifier for hallucinations.)'),
  BUL('**L3, semantic judge.** An LLM judge (Qwen2.5-1.5B-Instruct) given the passage, question and answer, replying SUPPORTED or UNSUPPORTED (Zheng et al., 2023). It is invoked only when routed: when L2 is present, only if the L2 entailment probability is below 0.9.'),
  P('All layers use the same evidence passage as retrieval-grounded verification. Every layer is run on every example so that any subset or cascade can be evaluated offline from observed flags, without any independence assumption. We record flag, score, wall-clock latency and exceptions per call. Layers fail open; a call that errors or exceeds a 2 s timeout is counted as a system failure, from which we estimate λ_sys_fail rather than assuming it.'),
  H2('4.3 Traffic replay and estimators'),
  P('Production logs are unavailable, so *arrivals* are simulated while *outcomes* are measured. Queries arrive according to an NHPP with a business-hours-shaped 24-slot intensity and a mean of 200 queries/day for 90 days (a Cox variant multiplies each day\'s intensity by a Gamma(1, c²) factor, c = 0.3, to represent bursty demand). Each arriving query replays a uniformly drawn example from the measured pool; it becomes a critical event if it is a hallucination that survives the cascade. For each resulting event stream we estimate λ̂ = events/days and test: (i) the index-of-dispersion test on daily counts; (ii) a chi-square test of constant hourly intensity; (iii) a Kolmogorov-Smirnov test of raw inter-arrival times against an exponential, and of time-rescaled gaps under the fitted hourly intensity (the Lilliefors-type p-value is optimistic); (iv) a negative-binomial fit of daily counts. Uncertainty from the finite evaluation pool is quantified by a 300-draw bootstrap over examples (95% percentile intervals).'),
  P('Because the same pool generates all arrivals, the replay tests whether the *counting process* has the claimed structure given measured per-query outcomes; it does not test whether real users\' queries are independent. That is the main external-validity limit (Section 6).'),
  H2('4.4 Cost model'),
  P('Daily cost is C_h·max(k_min, k*) + compute + false-block cost + residual-harm cost. We set C_h = $150 per capacity unit (as in the earlier draft), compute $0.0001 per classifier call and $0.002 per judge call, and treat the false-block cost c_fp and residual-harm cost c_res as scenario parameters in a sensitivity grid. These are assumptions, not estimates, and are labelled as such wherever used.'),
];
module.exports = { method };
