const { P, H1, H2, BUL, run } = require('./lib');
const { d } = require('./lib');
const S = require('../runs/summary.json');
const R = ['qwen05', 'smol360', 'qwen15'];
const f0 = x => Math.round(x), f1 = x => x.toFixed(1), f2 = x => x.toFixed(2);
const pct = x => (100 * x).toFixed(1) + '%';
const rg = (a, d = 0) => { const lo = Math.min(...a).toFixed(d), hi = Math.max(...a).toFixed(d); return lo === hi ? lo : `${lo}-${hi}`; };
const cfgk = (r, c) => S[r].sla500.configs.find(x => x.config === c);
const T3 = S.triage, FM = S.failure, TC = FM.typed_capacity;
const meanPlan = R.flatMap(r => [...Object.values(S[r].sla500.poisson_checks), ...Object.values(S[r].burst.poisson_checks)].map(v => 100 * v.p_exceed_mean_capacity_observed));
const none3 = R.map(r => 100 * S[r].burst.poisson_checks.none.p_exceed_k_star_observed), none44 = R.map(r => 100 * S[r].burst044.poisson_checks.none.p_exceed_k_star_observed);
const best3 = R.map(r => 100 * S[r].burst.poisson_checks['L1+L2'].p_exceed_k_star_observed), best44 = R.map(r => 100 * S[r].burst044.poisson_checks['L1+L2'].p_exceed_k_star_observed);
const red = R.map(r => 100 * (1 - cfgk(r, 'L2').k_star / cfgk(r, 'none').k_star));
const tcr = TC.scenarios.map(x => 100 * (x.all_classes.k_typed / x.all_classes.k_naive_poisson - 1));
const dsr = R.map(r => S[r].dependence_stats.ratio_no_routing.point), dsrr = R.map(r => S[r].dependence_stats.ratio_with_routing.point);
const ccv = [T3.software_company.arrivals.detrended.implied_daily_rate_cv, T3.italian_helpdesk.arrivals.detrended.implied_daily_rate_cv, T3.servicenow.arrivals.detrended.implied_daily_rate_cv];

const discussion = [
  H1('6. Discussion'),
  H2('6.1 Implications for IS practice and research'),
  BUL(`**Size capacity from a quantile, and fit the dispersion first.** Provisioning at the mean load failed on ${rg(meanPlan)}% of days across the configurations we measured. The Poisson quantile fixes this when daily counts are Poisson, but Proposition 2 and the burst experiments show that a modest day-to-day variation in demand (CV 0.3-0.44) raises the exceedance rate of a Poisson-sized plan from 5% to ${rg(none3)}% (c = 0.3) and ${rg(none44)}% (c = 0.44) without guardrails; real LLM request streams vary far more than that (a stress test, Section 5.6). Dispersion should be estimated from incident logs before the plan is fixed. Over-dispersion matters most for large incident streams (weak guardrails) and least for small ones (Propositions 2 and 3): provider outages at about 0.8 per day and dated hallucination cases at about 6 per weekday were statistically over-dispersed but changed the 95% capacity by at most one or two units, whereas the ServiceNow segment (about 350 tickets per work day) and the unprotected hallucination stream of 100+ events per day were affected strongly.`),
  BUL(`**Guardrail value is an empirical, per-deployment quantity.** The layers' stand-alone clearance, their dependence, their false-block cost and their latency vary strongly by layer and model. In our data one task-specific verifier delivered most of the benefit (a ${rg(red)}% reduction in required capacity at the price of ${rg(R.map(r => 100 * S[r].false_block_share_of_good.L2))}% of correct answers blocked), the deterministic layer was nearly inert, and the judge added a modest, model-dependent gain at about three times the latency. A fixed "three layers" prescription is not supported by these data; the method here selects the stack from measurements. A classifier that is not validated can be actively harmful: our NLI layer had chance-level discrimination and appeared to cut capacity only because it blocked almost everything.`),
  BUL(`**Model the failure classes separately and combine them at the ticket level.** Treating all failures as one Poisson stream misdescribes each class in a different way: hallucination counts are over-dispersed through demand variability, provider incidents are seasonal with a drifting level and at most a weak clustering, serving failures arrive in heavy-tailed episodes (${pct(FM.burstgpt.share_of_failures_in_episodes)} of failed requests fall in ${pct(FM.burstgpt.share_of_minutes_in_episodes)} of the active minutes), and human triage has heavy-tailed service. In our illustrative organisation a typed superposition required ${rg(tcr)}% more daily capacity than a single Poisson on the total across nine scenarios; the gap is driven by the assumed over-dispersion of the hallucination class and by how strongly over-dispersed the serving class is taken to be, so the example shows the size of the single-Poisson error under stated assumptions rather than a validated gain.`),
  BUL(`**Human triage is bursty and heavy-tailed in real organisations.** In public ticket streams the day-to-day coefficient of variation of the arrival rate was ${rg(ccv, 2)} net of trend, a Poisson-sized plan against the in-sample local mean was exceeded on ${rg([T3.software_company.arrivals.detrended.poisson_local_plan_exceeded, T3.italian_helpdesk.arrivals.detrended.poisson_local_plan_exceeded, T3.servicenow.arrivals.detrended.poisson_local_plan_exceeded].map(x => 100 * x))}% of work days instead of 5% (the two long streams: ${f1(100 * T3.software_company.arrivals.causal.poisson_plan_exceeded)}% and ${f1(100 * T3.italian_helpdesk.arrivals.causal.poisson_plan_exceeded)}% with a causal plan), resolution times had coefficients of variation of ${rg([T3.software_company.resolution_calendar_hours.cv, T3.servicenow.resolution_calendar_hours.cv, T3.italian_helpdesk.resolution_calendar_hours.cv], 1)} with decreasing hazards, and in the one stream with handling-time data the 95th percentile of the daily workload was ${f1(T3.software_company.workload.workload_q95_over_mean)} times its mean against ${f1(T3.software_company.workload.count_q95_over_mean)} for the arrival count. Capacity in *arrivals* is therefore not capacity in *hours*, and the tail of the service time needs its own headroom.`),
  BUL(`**Routing is a first-order design choice.** Sending only low-agreement answers to the expensive judge cuts judge calls by roughly an order of magnitude, but it also forgoes catches among answers the classifier rated as consistent; the share of hallucinations passing the L2+L3 cascade was ${rg(dsrr, 1)} times the independence prediction with routing against ${rg(dsr, 1)} times without it (Section 5.2).`),
  BUL(`**Governance.** Because k* converts a detector's precision and recall into headcount, the framework gives IT governance a common unit (units of triage capacity or dollars per day) in which to compare detectors, set the SLA and justify standing on-call capacity.`),
  H2('6.2 Limitations'),
  BUL(`**Simulated arrivals and no operator log of hallucinations.** Outcomes are measured on real model outputs, but arrival times are simulated and each arrival replays a bootstrapped example, so the Poisson and time-rescaling checks of Section 5.3 verify the machinery and are partly by construction. The public traces we use (BurstGPT, the provider incident history, the ticket logs) are real production data but record request arrivals, service incidents and human tickets, not hallucinations. The only dated hallucination log we found is a curated database of court decisions (Section 5.6), which is domain-specific, at day resolution, and subject to strong detection and reporting bias. To our knowledge no public production log of hallucination incidents from an operator exists. The burstiness of the replay is therefore a scenario informed by, not estimated from, real streams. Validation on proprietary incident logs is the main follow-up.`),
  BUL(`**The detection assumption.** The model assumes that every hallucination that passes the guardrails is detected and becomes exactly one human-handled event. In practice only a fraction is noticed or reported, and detection is a failure point of its own; the capacities we report are upper bounds that hold for full detection (Section 3.1).`),
  BUL(`**Small sample, shared questions, post-hoc layer change.** The three generators answered the same 300 questions, so their results are paired and not independent replications, and each layer estimate rests on 141-195 hallucinations and a few to a few dozen residual ones. The extractive-QA verifier was introduced after the NLI classifier proved uninformative, so the L2 choice was made after seeing results on the same data; it is trained on SQuAD, which flatters it relative to a domain-agnostic classifier, and its threshold was not tuned. The judge is Qwen2.5-1.5B in every run, so one arm is self-judged. The analyses should be repeated on a held-out sample with a pre-registered layer configuration.`),
  BUL(`**Dependence estimates are imprecise.** The positive association between L2 and L3 and the excess over the independence formula have wide bootstrap intervals, and for one generator the no-routing excess is not distinguishable from one; the independence prediction is computed from the same sample's marginals.`),
  BUL(`**Typed models are illustrative in combination.** The Hawkes and episode fits use one kernel family (exponential), a fixed seasonal profile estimated from the same data, and, for BurstGPT, an episode definition that matters quantitatively (Table 11) and may split a long outage into fragments; the bootstrap p-values are bounded below by 1/(B + 1). The capacity comparison of Section 5.8 combines classes from different organisations and datasets under independence, with an assumed hallucination dispersion and a single Poisson as the comparator; common-cause dependence between classes would widen the gap.`),
  BUL(`**Ticket data are not LLM incidents.** The ticket streams are customer-support and IT incidents; whether LLM-hallucination tickets share their arrival variability and service times is an assumption (plausible for the daily-rate CV, which is invariant to independent thinning with constant p, less so for service times, which depend on the verification task). Resolution times are calendar times that include waiting for customers or vendors and are not triage effort; the in-progress state time is a closer but still imperfect proxy. Ticket volumes in two of the logs change over their span, which we address by estimating variability against a local mean, the ServiceNow log can be used only for a 12-week segment, and the arrival-variability estimates of Section 5.7 rest on three streams.`),
  BUL(`**Public-trace artefacts.** BurstGPT has no calendar dates, a 104-day gap, near-duplicate day pairs and order-of-magnitude regime changes in daily volume, so its day-level variability reflects growth and logging as well as randomness; we use it as a stress test and its smallest 14-day coefficient of variation as a floor, not as an estimate. The provider incident data are provider-declared, with minute resolution and detection and reporting bias; incident duration is the declared start-to-resolution time, not triage effort.`),
  BUL(`**Small open models and one task.** We study 0.4-1.5B-parameter models on extractive QA with unanswerable questions. Absolute hallucination rates are much higher than for frontier models, and the layers are CPU-bound; latencies on GPU or hosted APIs differ. The *method* transfers, the *numbers* do not.`),
  BUL(`**Label noise and cost parameters.** Ground truth uses string and token-F1 matching against SQuAD gold answers, which can mark valid paraphrases as hallucinations and inflates the base rate. The cost parameters and selection weights are assumptions; only the labour-to-compute ratio and the sensitivity grid are informative, and the grid does not reflect sampling error.`),
  BUL(`**Independent days.** The model treats days as exchangeable apart from the weekly profile, a local level and the Cox-type multiplier; long-run trends, holidays and sudden regime shifts are only handled through the local mean estimates.`),
];
const conclusion = [
  H1('7. Conclusion'),
  P(`Treating human-handled LLM incidents as a counting process turns guardrail performance into a staffing and cost decision. Under the stated assumptions, capacity should be sized from an over-dispersion-aware quantile of the daily count; the multiplicative guardrail formula is an optimistic bound whose gap must be measured; a single Poisson on all failures misdescribes every class (hallucinations are over-dispersed through demand variability, provider incidents are seasonal with a drifting level and weak clustering, serving failures are heavy-tailed episodes); and the cost-minimising number of layers depends on integer capacity effects, the floor on standing staff, latency, the labour-to-compute ratio and the measured clearance, and is not fixed at three. On measured outputs of three small open models answering the same 300 questions, a single task-specific verifier reduced the required capacity by ${rg(red)}% relative to no guardrails while blocking ${rg(R.map(r => 100 * S[r].false_block_share_of_good.L2))}% of correct answers; a routed judge added a further modest reduction for two of the three generators at about triple the latency, and every cascade incurred false blocks and system failures. The share of hallucinations passing a two-layer cascade was ${rg(dsr, 1)} times the independence prediction without routing and ${rg(dsrr, 1)} times with routing, with wide intervals. Mild burstiness (daily-rate CV of 0.3-0.44, a range informed by public ticket streams and a production trace) raised the exceedance rate of a Poisson-sized plan from 5% to roughly ${f0(Math.min(...none3))}-${f0(Math.max(...none44))}% without guardrails and ${f0(Math.min(...best3, ...best44))}-${f0(Math.max(...best3, ...best44))}% with the best cascade. Public production data corroborate the structure: an LLM request trace shows clustered arrivals from the 10-second scale upward, provider incident streams are strongly seasonal with a drifting level and over-dispersion that remains after weekday stratification, a log of dated hallucination cases shows the same mild over-dispersion at about six cases per weekday, and company ticket streams show a net-of-trend daily rate CV of ${rg(ccv, 2)} and heavy-tailed resolution times. Hallucination arrivals themselves are simulated and no operator log of hallucinations is public, so validating the counting-process assumptions on production incident logs is the key next step.`),
];
const refs = [
  'Abraham, S., et al. (2026). AI incident monitoring through a public health lens. arXiv:2604.19914.',
  'Alotaibi, A., Jabbar, M. S., Al-Azani, S., & Ahmed, M. (2026). Layered LLM defenses as an ensemble: Access tiers, inference cost, and the measured failure correlation between defense layers. arXiv:2608.28327.',
  'Bartolucci and Vivo (2026). Queue & AI: When faster tasks slow down the workflow. arXiv:2605.27202.',
  'Besanson (2026). SARC: A governance-by-architecture framework for agentic AI systems. arXiv:2605.07728.',
  'Bhardwaj, Singh, and Bhardwaj (2026). Agent behavioral contracts II: Certifying compositional reliability without assuming independence. arXiv:2608.12895.',
  'Lin, R., & Zhang, J. (2026). When to screen, when to bypass: LLM-judges in resource-scarce AI-human workflow. arXiv:2603.13870.',
  'Tran-Truong and Le (2026). Measuring the unmeasurable: Markov chain reliability for LLM agents. arXiv:2604.24579.',
  'Wang, Y., et al. (2025). BurstGPT: A real-world workload dataset to optimize LLM serving systems. Proceedings of KDD 2025 (arXiv:2401.17644).',
  'Chu, X., Talluri, S., Lu, Q., & Iosup, A. (2025). An empirical characterization of outages and incidents in public services for large language models. Proceedings of ICPE 2025 (arXiv:2501.12469).',
  'Abdellatif, M. (2026). Help Desk Tickets (Version 3) [Dataset]. Mendeley Data. https://doi.org/10.17632/btm76zndnt.3',
  'Amaral, C. A. L., Fantinato, M., & Peres, S. M. (2018). Incident management process enriched event log [Dataset]. UCI Machine Learning Repository (dataset 498).',
  'Verenich, I. (2016). Helpdesk [Dataset: help desk log of an Italian software company]. Mendeley Data, V1. https://doi.org/10.17632/39bp3vv62t.1',
  'Charlotin, D. (2026). AI Hallucination Cases database (court decisions with AI-fabricated content). https://www.damiencharlotin.com/hallucinations/ (CC BY 4.0; accessed 6 October 2026).',
  'Cox, D. R., & Isham, V. (1980). Point Processes. Chapman & Hall.',
  'Daley, D. J., & Vere-Jones, D. (2003). An Introduction to the Theory of Point Processes, Volume I (2nd ed.). Springer.',
  'Hawkes, A. G. (1971). Spectra of some self-exciting and mutually exciting point processes. Biometrika, 58(1), 83-90.',
  'Ogata, Y. (1988). Statistical models for earthquake occurrences and residual analysis for point processes. Journal of the American Statistical Association, 83(401), 9-27.',
  'Allal, L. B., et al. (2025). SmolLM2: When Smol goes big, data-centric training of a small language model. arXiv:2502.02737.',
  'Brown, L., Gans, N., Mandelbaum, A., Sakov, A., Shen, H., Zeltyn, S., & Zhao, L. (2005). Statistical analysis of a telephone call center: A queueing-science perspective. Journal of the American Statistical Association, 100(469), 36-50.',
  'Cameron, A. C., & Trivedi, P. K. (1998). Regression Analysis of Count Data. Cambridge University Press.',
  'Cox, D. R. (1955). Some statistical methods connected with series of events. Journal of the Royal Statistical Society, Series B, 17(2), 129-164.',
  'Esary, J. D., Proschan, F., & Walkup, D. W. (1967). Association of random variables, with applications. Annals of Mathematical Statistics, 38(5), 1466-1474.',
  'Green, L. V., Kolesar, P. J., & Whitt, W. (2007). Coping with time-varying demand when setting staffing requirements for a service system. Production and Operations Management, 16(1), 13-39.',
  'Gregor, S., & Hevner, A. R. (2013). Positioning and presenting design science research for maximum impact. MIS Quarterly, 37(2), 337-355.',
  'He, P., Gao, J., & Chen, W. (2021). DeBERTaV3: Improving DeBERTa using ELECTRA-style pre-training with gradient-disentangled embedding sharing. arXiv:2111.09543.',
  'Hevner, A. R., March, S. T., Park, J., & Ram, S. (2004). Design science in information systems research. MIS Quarterly, 28(1), 75-105.',
  'Inan, H., et al. (2023). Llama Guard: LLM-based input-output safeguard for human-AI conversations. arXiv:2312.06674.',
  'Ji, Z., et al. (2023). Survey of hallucination in natural language generation. ACM Computing Surveys, 55(12), Article 248.',
  'Kingman, J. F. C. (1993). Poisson Processes. Oxford University Press.',
  'Lewis, P., et al. (2020). Retrieval-augmented generation for knowledge-intensive NLP tasks. Advances in Neural Information Processing Systems, 33.',
  'Manakul, P., Liusie, A., & Gales, M. J. F. (2023). SelfCheckGPT: Zero-resource black-box hallucination detection for generative large language models. Proceedings of EMNLP 2023.',
  'Qwen Team. (2024). Qwen2.5 technical report. arXiv:2412.15115.',
  'Rajpurkar, P., Jia, R., & Liang, P. (2018). Know what you don\'t know: Unanswerable questions for SQuAD. Proceedings of ACL 2018, 784-789.',
  'Topkis, D. M. (1978). Minimizing a submodular function on a lattice. Operations Research, 26(2), 305-321.',
  'Whitt, W. (2007). What you should know about queueing models to set staffing requirements in service systems. Naval Research Logistics, 54(5), 476-484.',
  'Zheng, L., et al. (2023). Judging LLM-as-a-judge with MT-Bench and Chatbot Arena. Advances in Neural Information Processing Systems, 36.',
];
const references = [H1('References'), ...refs.sort((x, y) => x.localeCompare(y)).map(r => new d.Paragraph({ children: [run(r, { size: 20 })], spacing: { after: 70 }, indent: { left: 360, hanging: 360 } }))];
module.exports = { discussion, conclusion, references };
