const { P, H1, H2, EQ, BOX, BUL, table } = require('./lib');
const T = require('../runs/paper_tables.json');
const f2 = x => x.toFixed(2), usd = x => '$' + Math.round(x).toLocaleString('en-US');

const intro = [
  H1('1. Introduction'),
  P('Large language models (LLMs) are now embedded in customer-facing and decision-support information systems, where an ungrounded answer is a service incident rather than a quality blemish. IS research has examined adoption and value of generative AI, but the *operations* question that follows deployment has received little formal treatment: how much human triage and verification capacity must an organisation keep on standby, and how many automated guardrail layers should sit in front of the model, when hallucinations arrive at random?'),
  P('Two simple planning heuristics are easy to apply but can be improved on: provisioning triage capacity at the mean incident load, and crediting each additional guardrail layer with its stand-alone effectiveness as if layers failed independently. Provisioning at the mean leaves the system under-provisioned on roughly 30-50% of days in our measurements, and the independence product is, as we show, an optimistic bound.'),
  P('We make four contributions and are explicit about which parts apply known results. **First**, we describe the capacity requirement for LLM incident handling as the quantile of the daily count of human-handled events (Section 3). The quantile rule and the over-dispersion correction are classical (Whitt, 2007; Cameron and Trivedi, 1998); our contribution is to apply them to this arrival stream, to derive how over-dispersion and thinning by guardrails enter the requirement (Propositions 2 and 3), and to check on public request, incident and ticket traces whether the counting-process assumptions hold on comparable real streams. None of these traces is a hallucination log, so hallucination arrivals themselves are assumed or simulated. **Second**, we replace the single-Poisson description of "all failures" by a typed model (Section 3.6): hallucinations as thinned, over-dispersed streams; provider incidents as a seasonal Hawkes process; serving failures as heavy-tailed episodes; human triage with heavy-tailed service; with superposition and clustering results (Proposition 6) and public-data fits (Section 5.8). **Third**, we restate the multiplicative guardrail formula as the independence special case of Fréchet-type bounds on an arrival-rate cascade (Proposition 4). Dependence between guardrail layers has been measured on real defence stacks (Alotaibi et al., 2026) and the independence product is known to over-credit redundancy (Bhardwaj et al., 2026); we add a measurement on hallucination-grounding layers with uncertainty intervals and carry the correction through to the capacity decision. We also show that, once capacity is integer-valued, total cost is generally *not* unimodal in the number of layers, with comparative statics in the labour-to-compute ratio (Proposition 5); this follows from the model structure and is a model property, not an empirical discovery. **Fourth**, we evaluate the pipeline on real model outputs: three small open models answering the same 300 SQuAD 2.0 questions, three guardrail layers executed with measured latency and error behaviour, and traffic replayed through a non-homogeneous arrival process whose daily-rate variability is informed by public traces. Per-query hallucination outcomes, guardrail decisions, layer dependence and latency are measured; arrival times are simulated. To our knowledge, no earlier study combines measured guardrail performance, an incident-count model with dispersion and clustering, and a quantile-based capacity decision in one framework evaluated on real system outputs and public production traces; each ingredient has precedents (Section 2).'),
  P('The paper follows the design-science tradition in IS (Hevner et al., 2004; Gregor and Hevner, 2013): we propose an artifact (a capacity-planning and guardrail-sizing method), ground it in a formal model, and evaluate it on real system outputs. We are explicit about what the evaluation does and does not establish (Section 6).'),
];

const related = [
  H1('2. Related Work'),
  P('**Hallucination and its mitigation.** Surveys document hallucination as a pervasive property of neural text generation (Ji et al., 2023). Mitigation work includes retrieval grounding (Lewis et al., 2020), sampling-based consistency checks (Manakul et al., 2023), safeguard classifiers (Inan et al., 2023) and LLM-as-judge verification (Zheng et al., 2023). This literature evaluates *detectors* by accuracy; it does not ask how detector performance translates into the human capacity an organisation must hold in reserve.'),
  P('**Capacity planning under random demand.** The use of the Poisson quantile to size service capacity is classical in service operations (Whitt, 2007), and time-varying demand is handled by piecewise-stationary staffing (Green et al., 2007). Empirical studies of call centres report that arrivals are well described by a Poisson process only conditional on a random, day-specific rate, i.e. they are over-dispersed (Brown et al., 2005); count-data econometrics offers the negative-binomial remedy (Cameron and Trivedi, 1998). We import these tools to a new arrival stream and test whether the same caveats apply.'),
  P('**Human review capacity for AI outputs.** Queueing models of human review of AI output exist: Poisson escalation arrivals with Erlang-C staffing of human operators for agent escalations (Besanson, 2026), M/G/1 models of reviewing AI drafts (Bartolucci and Vivo, 2026), and fluid-limit routing between an LLM judge and human review (Lin and Zhang, 2026). These use mean-based stability or waiting-time criteria and assume, rather than test, Poisson arrivals. We size capacity at a quantile of the incident-count distribution and test the arrival assumptions.'),
  P('**Counting-process models of AI failures.** Public-health-style monitoring of AI incident counts has found strong over-dispersion relative to Poisson in incident-database counts of vehicle and deepfake incidents (Abraham et al., 2026), and Markov reliability models of LLM agents reduce to the Goel-Okumoto NHPP software-reliability model in the rare-failure regime (Tran-Truong and Le, 2026). Neither concerns hallucination or guardrail-bypass events, nor applies time-rescaling tests or capacity sizing.'),
  P('**Layered defences.** The multiplicative formula for the residual rate of independent safeguards is standard in reliability engineering, and it over-credits redundancy when failures are positively associated (Esary et al., 1967). For LLM defence stacks, Alotaibi et al. (2026) measure positive failure correlation between seven defence layers (φ between 0.30 and 0.75 on JailbreakBench) and call the product a lower bound that no real stack attains; Bhardwaj et al. (2026) give a Fréchet-Hoeffding sandwich and measure high co-failure among same-model LLM components. Our dependence results should be read as additional evidence, in a different setting (hallucination-grounding layers), rather than as a first demonstration.'),
  P('**Gap.** Prior work addresses these pieces separately: arrival models for AI incidents, human-review queueing, measured layer dependence, and guardrail cost-latency trade-offs. We integrate them for LLM hallucination operations and evaluate the integrated pipeline on measured outputs and public traces. The literature on LLM guardrails moved quickly in 2026; our search was not exhaustive and similar work may exist.'),
];

const model = [
  H1('3. Model'),
  H2('3.1 Arrivals of critical hallucinations'),
  P('Users send queries at times governed by an intensity Λ(t) with a daily cycle. Each query independently produces a *hallucination* (a wrong or ungrounded answer) with probability p₀, and the guardrail cascade blocks some of them. We assume that every hallucination that passes all guardrails is detected and becomes exactly one human-handled event that consumes one unit of triage capacity, and call such an event a *critical hallucination*; let q ≤ p₀ be the probability that a query yields one. By the thinning theorem (Kingman, 1993), critical hallucinations form a non-homogeneous Poisson process (NHPP) with intensity qΛ(t). Let X_d be the number of events on day d, with mean λ = q∫_day Λ(t)dt. Then X_d ~ Poisson(λ) regardless of the within-day shape of Λ; the within-day shape matters for *hourly* staffing, where the hour-h requirement is the quantile of Poisson(λ_h). The detection assumption is strong: if only a fraction d of the surviving hallucinations is ever noticed and triaged, the event rate is dλ and, by Proposition 3, the dispersion index is 1 + dλc²; the capacities we report are therefore upper bounds that hold for d = 1, and detection itself is a further failure point that the model does not cover.'),
  P('Inter-arrival times are exponential only under a constant rate. Under the NHPP, the time-rescaled gaps Λ̂(t_i)-Λ̂(t_{i-1}) are i.i.d. Exp(1) (the time-rescaling theorem), which gives a goodness-of-fit test that we use in Section 5. The memoryless property therefore applies to rescaled time: elapsed time since the last event carries no information, but time-of-day does.'),
  P('If the daily rate is itself random, Λ_d = λM with E[M] = 1 and Var(M) = c², the daily count is a mixed Poisson variable with Var(X_d) = λ + λ²c² = λφ, where φ = 1 + λc² is the dispersion index. This is the Cox-process alternative to the pure Poisson null.'),
  H2('3.2 Readiness capacity'),
  P('For reliability target α, the capacity requirement is the generalised inverse of the daily-count distribution:'),
  EQ('k*(α, λ) = min { k ∈ ℕ₀ : P(X_d ≤ k) ≥ α }'),
  BOX('Proposition 1 (Poisson capacity).', 'Let X ~ Poisson(λ). (a) k*(α, λ) is non-decreasing in λ. (b) k*(α, λ) = 0 if and only if λ ≤ -ln α; for α = 0.95 this threshold is ' + T.k_zero_threshold.toFixed(4) + ' events/day. (c) Provisioning at the mean, k = ⌊λ⌋, leaves the system under-provisioned with probability P(X > ⌊λ⌋), which is at least 0.26 for every λ ≥ 1, is about 0.35 at λ = 3 (not 0.42, which is P(X ≤ 2)) and tends to 0.5 as λ grows. (d) k* = λ + z_α√λ + O(1) as λ → ∞.'),
  P('*Proof sketch.* (a) Poisson(λ) is stochastically increasing in λ. (b) P(X = 0) = e^{-λ} ≥ α iff λ ≤ -ln α. (c) On [n, n+1) the probability P(X > n) is increasing in λ, so its minimum over λ ≥ 1 is P(X > 1) = 0.264 at λ = 1, and it is 0.353 at λ = 3 (P(X ≤ 3) = 0.647). (d) follows from the Cornish-Fisher expansion of the Poisson quantile. ∎'),
  BOX('Proposition 2 (over-dispersion inflates capacity).', 'Let X_d | M ~ Poisson(λM) with E[M] = 1 and Var(M) = c² > 0. Then (a) Var(X_d) = λφ with φ = 1 + λc²; (b) X_d dominates Poisson(λ) in the convex order, so E[(X_d - k)⁺] ≥ E[(Y - k)⁺] for every k, where Y ~ Poisson(λ); (c) If φ stays bounded as λ grows, k*_mixed(α) = λ + z_α√(λφ) + O(1). If instead the multiplier has a fixed CV c, then φ = 1 + λc² grows with λ and k*_mixed(α) = λ·F_M⁻¹(α) + O(√λ), where F_M is the distribution of M; in that regime λ + z_α√(λφ) understates the exact quantile by an amount that grows linearly in λ, and √φ is a lower guide for the inflation of the safety stock k* - λ, not an exact factor (e.g. for Gamma M at λ = 120.7 and c = 0.3 the exact ratio of the safety stock to its Poisson value is 3.8 against √φ = 3.4; at c = 0.44 it is 5.5 against 4.9). The exact negative-binomial quantile (Table 1) should be used for planning.'),
  P('*Proof sketch.* (a) is the law of total variance. (b) For Poisson, ∂/∂λ E[(Y - k)⁺] = P(Y ≥ k), which is non-decreasing in λ, hence λ ↦ E[(Y_λ - k)⁺] is convex; Jensen\'s inequality applied to the mixing variable M gives E[(X_d - k)⁺] = E[g(λM)] ≥ g(λ). (c) For bounded φ the count is asymptotically normal with variance λφ. For fixed c, X_d/λ → M in distribution as λ → ∞, so the 95% quantile of X_d is asymptotically λF_M⁻¹(α) and the normal approximation fails. ∎'),
  P('Table 1 evaluates Proposition 2 exactly (negative-binomial mixing). At λ = 10 events/day and c = 0.3, the Poisson plan k* = 15 is exceeded on 11.0% of days instead of 4.9%, and the correct requirement is 18; at λ = 25 and c = 0.3 the Poisson plan of 33 is exceeded on 16.7% of days and 41 is required.'),
  ...table('Table 1. Capacity under over-dispersed arrivals (Gamma-mixed Poisson, α = 0.95)',
    ['λ (events/day)', 'c (CV of daily rate)', 'φ', 'k* Poisson', 'k* mixed', 'P(exceed) Poisson plan'],
    T.overdispersion.filter(r => r.lambda >= 10).map(r => [r.lambda, r.cv, f2(r.phi), r.k_poisson, r.k_negbin, (100 * r.exceedance_prob_poisson_plan || 100 * r.exceed_prob_poisson_plan).toFixed(1) + '%']),
    [1500, 1800, 1100, 1500, 1500, 1960], 'Exact negative-binomial quantiles; computed by paper_tables.py.'),
];

const thinning = [
  H2('3.3 Thinning: guardrails make the incident stream closer to Poisson'),
  P('Requests may be clustered even when incidents are rare. Because critical hallucinations are an independent thinning of requests, the dispersion of the incident stream follows from that of the request stream:'),
  BOX('Proposition 3 (thinning reduces dispersion).', 'Let N be the request count in a window with mean μ and Fano factor F = Var(N)/μ, and let each request independently become a critical event with a constant probability p that does not depend on the request stream. Then the event count N_p has mean pμ and Fano factor 1 + p(F - 1). In particular, a guardrail cascade that reduces the residual probability p pulls the incident stream towards Poisson (Fano factor 1), while the unprotected stream (p large) retains most of the request stream\'s burstiness. Equivalently, for a mixed-Poisson day with rate multiplier of CV c, φ = 1 + λc² in Proposition 2 with λ = pμ. Under independent thinning with constant p the multiplier M, and hence its CV c, is unchanged, so c (rather than φ) is the quantity that can be carried over between streams with different event rates; this transfer requires that p is constant and independent of M, which we assume but do not test for hallucinations.'),
  P('*Proof.* Var(N_p) = p²Var(N) + p(1 - p)μ by the law of total variance for the binomial thinning. Dividing by pμ gives pF + (1 - p) = 1 + p(F - 1). ∎ (We also verified this numerically by simulation.) The practical reading: over-dispersion matters most precisely where capacity is largest, i.e. without or with weak guardrails, and matters less after strong filtering, consistent with the shrinking gap between Poisson and negative-binomial capacity in Section 5.4.'),
];

const typed = [
  H2('3.6 Beyond a single Poisson: typed failure classes'),
  P('LLM operations produce several kinds of failures that violate the Poisson assumptions in different ways, so treating "all failures" as one Poisson stream is a modelling error rather than a simplification. We therefore model each class with the process that matches its mechanism and combine the classes only at the level of the human-handled event (an incident or ticket). Table 4 summarises the mapping, the assumption that fails and the evidence developed in Section 5.8.'),
  ...table('Table 4. Failure classes, mechanisms and models',
    ['Class', 'Mechanism', 'Poisson assumption violated', 'Model used', 'Evidence'],
    [['Hallucination (per answered query)', 'Independent errors of the model given the query, on a clustered, daily-varying request stream', 'Constant rate; independence of requests', 'Cox / negative-binomial thinning of the request stream (Props. 2, 3)', 'Sections 5.4, 5.6, 5.7'],
     ['Provider-declared incidents', 'Outages, possibly followed by further incidents within hours; weekday/hour seasonality and a drifting level', 'Orderliness and independence (self-excitation)', 'Seasonal (level-adjusted) Hawkes process, exponential kernel; NHPP as null', 'Section 5.8'],
     ['Serving errors and timeouts', 'Common-cause episodes (outages, rate limiting) with heavy-tailed size; residual isolated errors (not modelled)', 'Orderliness (batch arrivals), independence', 'Episode process (Hawkes) with heavy-tailed marks; compound Poisson for counts of failed requests', 'Section 5.8'],
     ['Human triage service', 'Mixture of quick and very long tickets', 'Exponential service', 'Heavy-tailed (Weibull / lognormal) service; workload headroom', 'Section 5.7']],
    [1500, 2200, 1700, 2300, 1660]),
  BOX('Proposition 6 (superposition and clustering).', '(a) If the daily counts of independent failure classes j have means λ_j and dispersion indices φ_j = Var/mean, the total daily count has mean Σλ_j and Var = Σλ_jφ_j, so the 95% capacity is approximately Σλ_j + z·√(Σλ_jφ_j). A single Poisson on the total uses φ = 1 and under-states the safety stock by the factor √φ_eff with φ_eff = Σλ_jφ_j / Σλ_j. The superposition of independent classes is Poisson only if every class is Poisson. (b) For a stationary Hawkes process with branching ratio α < 1 (the expected number of direct follow-up events per event), the cluster started by a background event has a Borel size distribution with mean 1/(1 - α), the long-window Fano factor of counts is 1/(1 - α)², and the count variance in a window of fixed length approaches this value as the window grows relative to the excitation time scale 1/β. (c) For a compound Poisson count N = Σ_{i ≤ M} X_i with M ~ Poisson(ν), the Fano factor is E[X²]/E[X], which is unbounded when the mark distribution has an infinite second moment (e.g. a Pareto tail index below 2): the variance of the daily count, and with it the Poisson capacity error, is dominated by the largest episodes.'),
  P('*Proof sketch.* (a) Variances of independent counts add; the normal approximation of the quantile uses the total variance. (b) The Hawkes cluster is a Galton-Watson tree with Poisson(α) offspring; its total progeny is Borel(α) with mean 1/(1 - α) and second moment 1/(1 - α)³, hence E[X²]/E[X] = 1/(1 - α)², and the stationary count variance-to-mean ratio of a Hawkes process equals this value in the long-window limit. (c) is Wald\'s identity for the compound Poisson variance, Var(N) = νE[X²]. ∎ For provider incidents the fitted branching ratio is 0.11-0.22 with a constant level and 0.05-0.09 once a monthly level is allowed (Section 5.8), implying a long-window Fano factor of about 1.3-1.6 and 1.1-1.2 respectively, to be compared with stratified dispersion indices of 1.2-1.5 (Section 5.6); for serving-failure episodes α is 0.5-0.85 depending on the episode definition and the second-moment ratio E[X²]/E[X] of the episode sizes is in the thousands, so the Fano factor of failed-request counts is dominated by a few large episodes and a Poisson description of failed requests is inadequate by several orders of magnitude, also after conditioning on traffic volume.'),
];

const cascade = [
  H2('3.4 Guardrail cascades and dependence'),
  P('A cascade of N layers with stand-alone clearance rates c_i (the share of critical hallucinations layer i blocks) is usually assumed to give λ_N = λ₀Π(1 - c_i). This presumes independent layer decisions. In practice the same ambiguous or adversarial outputs tend to fool all layers.'),
  BOX('Proposition 4 (dependence bounds).', 'For any joint behaviour of the layers, λ₀(1 - Σc_i)⁺ ≤ λ_N ≤ λ₀(1 - max_i c_i). If the layers\' catch indicators, conditional on a hallucination, are positively associated (Esary et al., 1967), then additionally λ_N ≥ λ₀Π(1 - c_i). Consequently the multiplicative formula under-states residual risk and, through Proposition 1(a), under-states required capacity.'),
  P('*Proof sketch.* The bounds are the Fréchet-Bonferroni bounds for the event that no layer fires. For associated indicators, P(∩{I_i = 0}) ≥ ΠP(I_i = 0) (Esary et al., 1967). ∎'),
  P('Table 2 illustrates the width of the identification problem with c_i = 0.63 and λ₀ = 10: without knowing the dependence, three layers could imply anything from 0 to 7 units of capacity, which is why the dependence must be *measured* (Section 5.2).'),
  ...table('Table 2. Residual rate and capacity bounds (λ₀ = 10, c_i = 0.63, α = 0.95)',
    ['N', 'λ_N lower', 'λ_N independent', 'λ_N upper', 'k* lower', 'k* indep.', 'k* upper'],
    T.dependence_bounds.map(r => [r.N, f2(r.lambda_lower), f2(r.lambda_indep), f2(r.lambda_upper), r.k_lower, r.k_indep, r.k_upper]),
    [700, 1500, 1700, 1500, 1200, 1300, 1460]),
  H2('3.5 Cost-minimising guardrail depth'),
  P('Let C_h be the daily cost of one unit of triage capacity, g_i the daily compute cost of layer i, k_min ≥ 0 a minimum standing capacity (an on-call engineer is not removed because incidents are rare), and consider the cost'),
  EQ('f(N) = C_h · max{ k_min, k*(α, λ_N) } + Σ_{i ≤ N} g_i  (+ latency-feasibility: Σ L_i ≤ SLA).'),
  BOX('Proposition 5 (optimal depth).', '(a) f is in general not unimodal in N: because k* is integer-valued with plateaus, f can rise and then fall again. (b) With k_min ≥ 1, let N₀ be the first N with k*(α, λ_N) ≤ k_min; every N > N₀ is strictly dominated, so N* ≤ N₀. (c) Let θ = C_h / g with equal per-layer compute cost g. The minimiser N*(θ) is non-decreasing in θ: when human triage is relatively expensive, deeper cascades are optimal (Topkis, 1978). (d) The latency constraint restricts N to a feasible prefix of the cascade.'),
  P('*Proof sketch.* (a) is shown by the example in Table 3. (b) For N > N₀, labour cost is constant at C_h k_min while compute increases. (c) Write f(N) = g[N + θ K(N)] with K non-increasing; the difference f(N+1) - f(N) = g[1 + θ(K(N+1) - K(N))] is non-increasing in θ, so the largest minimiser is non-decreasing in θ by Topkis\' monotone comparative statics. (d) is immediate. ∎'),
  P('**The number of layers is an outcome of the model, not a constant.** Table 3 uses an illustrative parameter set (λ₀ = 10 events/day, a clearance of 0.63 per layer under independence, $150 per capacity unit, $25 per layer). With k_min = 0 the cost falls from N = 3 to N = 4, rises at N = 5 and falls again at N = 6, where k* reaches zero (λ₆ = 0.026 < -ln 0.95), so the minimum is at N = 6; with a realistic floor of one on-call engineer (k_min = 1) the minimum is at N = 4. A fixed number of layers (for instance three) is therefore not implied by the cost model: the optimum depends on the cost ratio, the clearance rates, the dependence between layers and the latency constraint.'),
  ...table('Table 3. Daily cost by guardrail depth (λ₀ = 10, c = 0.63 independent, C_h = $150/unit, g = $25/layer)',
    ['N', 'λ_N', 'k*', 'Labour', 'Compute', 'Total (k_min = 0)', 'Total (k_min = 1)'],
    T.table1.map(r => [r.N, r.lambda.toFixed(3), r.k_star, usd(r.labour), usd(r.compute), usd(r.total), usd(150 * Math.max(1, r.k_star) + r.compute)]),
    [700, 1200, 800, 1400, 1400, 1930, 1930],
    'Minimum: N = 6 under k_min = 0; N = 4 under k_min = 1. The cost parameters are illustrative assumptions.'),
];
module.exports = { intro, related, model, thinning, cascade, typed };
